### ISSUE TITLE
Edge/14 (in Windows 10 Anniversary Update) is misidentified as Chrome 48

### ISSUE THREAD

**Issue by frankolivier** [browscap/browscap#1006]
See http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F48.0.2564.82+Safari%2F537.36+Edge%2F14.14359

**Comment by mimmi20** [comment]
This was also reported in issue #984 and was solved with PR #988.
