### ISSUE TITLE
Firefox 47

### ISSUE THREAD

**Issue by webIMT** [browscap/browscap#1011]
Hi,

the last release of stable Firefox is missing : Firefox 47.

Thanks for all !
Oli.

**Comment by mimmi20** [comment]
Do you have an actual useragent?

**Comment by webIMT** [comment]
Yes, but you can take the entire Firefox 46 section in browscap.ini and just replace "46" by "47". 
Could you add too Firefox 48 (in beta actually) ?

**Comment by mimmi20** [comment]
@webIMT I would like to have an useragent for testing.

**Comment by ThaDafinser** [comment]
@mimmi20 here u go http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+6.1%3B+WOW64%3B+rv%3A47.0%29+Gecko%2F20100101+Firefox%2F47.0

**Comment by mupsolutions** [comment]
Same with http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%3B+rv%3A47.0%29+Gecko%2F20100101+Firefox%2F47.0

**Comment by webIMT** [comment]
Ok, here it is: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by Crash58** [comment]
agent on a Win 8.1 Pro machine:

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by Crash58** [comment]
Any idea when it will be available on browscap.org?



scot







From: James Titcumb
Sent: ‎Wednesday‎, ‎June‎ ‎15‎, ‎2016 ‎7‎:‎44‎ ‎AM
To: browscap/browscap
Cc: Crash58, Comment





Closed #1011 via e3187a2.
