### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#1017]
https://travis-ci.org/browscap/browscap/builds/138847811

Build seems to be erroring currently - not sure why as it's generating fine, so release of 6015 is not affected.

**Comment by mimmi20** [comment]
It fails because BrowscapPhp was updated.

**Comment by ThaDafinser** [comment]
I run into similar (or same) issue https://travis-ci.org/ThaDafinser/UserAgentParser/jobs/138845522

Will check it with the hopefully soon `v3 release` https://github.com/browscap/browscap-php/issues/119#issuecomment-227081396
