### ISSUE TITLE
Latest IOS detection issue

### ISSUE THREAD

**Issue by nickunderhill** [browscap/browscap#1035]
Hi!

Example:
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1

For user-agents like this one platform_version is unknown.

**Comment by nickunderhill** [comment]
Some more
[FBAN/FBIOS;FBAV/57.0.0.41.136;FBBV/31395714;FBRV/0;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/9.3.2;FBSS/3;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G34

**Comment by asgrim** [comment]
Fixed by #1036
