### ISSUE TITLE
add tests for Lumia devices

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1042]
Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; NOKIA; RM-1010) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14393
Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; Microsoft; RM-1113)

RM-978 Nokia Lumia 630
RM-1027 Nokia Lumia 636
RM-1010 Nokia Lumia 638
RM-1113 Microsoft Lumia 640
RM-1096 Microsoft Lumia 640 XL

**Comment by asgrim** [comment]
Fixed by #1054
