### ISSUE TITLE
KODI (ex XBMC)

### ISSUE THREAD

**Issue by sebbio** [browscap/browscap#1047]
Kodi/16.1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/16.1-Git:20160424-c327c53

This is Kodi Media Center - link https://kodi.tv/

**Comment by sebbio** [comment]
Kodi/17.0-BETA1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.0-BETA1-Git:20160821-81d5d26

**Comment by asgrim** [comment]
Fixed by #1056
