### ISSUE TITLE
Errors for old versions of Chrome, Safari and Edge

### ISSUE THREAD

**Issue by sosek108** [browscap/browscap#1063]
On newest version (6016) there is some sort of problem.

Microsoft Edge 38.14393.0.0
Chrome 52 and older
Safari 9.1.3

We use crossjoin/browscap library and the function getBrowser()->getData() returns null instead of data object.

There is no problem with 6015 version.

Best Regards
Hubert

**Comment by asgrim** [comment]
Could you provide some example UA strings please? Have you tried them out on https://browscap.org/ua-lookup ?

If not, this is something you'd have to raise with the library author to determine the cause (or, of course, you can investigate and post results back here).

**Comment by sosek108** [comment]
Thank you for response!

For this UA error occured: 
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

And for this worked: 
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by asgrim** [comment]
Hmm, the first and second UA both seem to work just fine on https://browscap.org/ua-lookup

I'm wondering if crossjoin/browscap is using a reduced set of files (e.g. lite?)

**Comment by sosek108** [comment]
Default or large set are available in our project.

Pozdrawiam
Hubert Sosiński

2016-09-15 17:10 GMT+02:00 James Titcumb <notifications@github.com>:

**Comment by asgrim** [comment]
Hmm - you may need to contact the authors of crossjoin/browscap then. It's not something we support directly; unless of course you manage to find the issue!
