### ISSUE TITLE
Bump minimum PHP version to 7

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#1067]
This tool is specifically just a generation tool used by contributors. Therefore, I'm fine with updating minimum PHP versions to 7.

I'd also like to look at speed of HHVM vs PHP 7 - currently I generate the files using HHVM, but given PHP 7's improvements, it may now be faster to use PHP 7 (and ditch the HHVM support).

**Comment by asgrim** [comment]
Purely going off these build times, HHVM is still a little faster:

https://travis-ci.org/browscap/browscap/builds/160182210

HHVM - 9m 21s
PHP 7 - 15m 54s
PHP 7.1 (nightly) - 11m 21s

PHP 7.1 may be an acceptable punt though! :)

**Comment by asgrim** [comment]
```
$ time composer up
Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
> BrowscapSite\Tool\ComposerHook::postUpdate
Generating new Browscap build: 6017
  - Creating build folder
  - Log level set to 250
  - Setting up logging
  - Creating writer collection
  - Creating actual build
  - Generating metadata
  - Updating symlink to point to 6017
All done

real	2m59.598s
user	2m50.456s
sys	0m8.556s
```

3 minutes to do the actual generation isn't so bad, that's:

```
$ php -v
PHP 7.0.11-1+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.11-1+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
```

**Comment by asgrim** [comment]
Results from the build https://travis-ci.org/browscap/browscap-site/builds/161875376 on browscap-site are interesting - PHP 7.1 is much faster than PHP 7.0

**Comment by mimmi20** [comment]
Please check, if the tool is installable on HHVM, if you change the requirement to Php 7.

**Comment by asgrim** [comment]
I don't think so (new language features in PHP 7 may not be compatible, but I haven't checked so may be wrong there); but HHVM is pretty much fading out of favour IMO, and if we can get comparable speed out of PHP 7.1, then it makes sense to move to that I think.

**Comment by asgrim** [comment]
@mimmi20 btw do you still use HHVM to generate the files? have you tried PHP 7.1 yet?

**Comment by mimmi20** [comment]
@asgrim At my local system I use PHP 7 at the moment. I did not try the new beta version yet.

**Comment by asgrim** [comment]
Okay. I'm happy to drop both PHP 5 and HHVM support in that case. We'll go to min of 7, and then recommend 7.1

**Comment by mimmi20** [comment]
fine
