### ISSUE TITLE
oneplus devices discover as desktop

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1076]
see serbanghita/Mobile-Detect#568 for more details.

**Comment by asgrim** [comment]
Fixed by #1091

**Comment by sirajulm** [comment]
Oneplus 5 device not detected as `Phone`
User Agent: `Mozilla/5.0 (Linux; Android 8.0.0; ONEPLUS A5000 Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36`

**Comment by mimmi20** [comment]
@sirajulm Please open a new issue.
