### ISSUE TITLE
Missing UAS: Google image proxy

### ISSUE THREAD

**Issue by JohannesWilkeStriata** [browscap/browscap#1108]
Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)

This is an image cache proxy that Google is using when an email is requesting image resources. GMail emails that are viewed on a GMail client receives the emails with the image source attribues rewritten to query Google instead of the hosting server. Google will then ask the hosting server for the resource and use above mentioned UAS.

**Comment by mimmi20** [comment]
Does Google use this UA also when the user does not use a Firefox?

**Comment by JohannesWilkeStriata** [comment]
Yes,

The Firefox in the UAS has nothing to do with the user that is requesting
the image. GoogleImageProxy will use the UAS as I described it, no matter
what the user used. The user UAS is actually lost, but it will be good to
identify GoogleImageProxy as a proxy and not as a firefox windwos browser.

If you use Safari on OS X (macOS) and log onto gmail.com and view your
email. Then the hosting server will receive the GoogleImageProxy UAS as I
described it.


*Johannes Wilke*
*Software Developer*
*Office:* +27 11 530 9600 | *Mobile:* +27(74)588-4099
*Striata on:* Twitter <https://twitter.com/striata> | LinkedIn
<http://www.linkedin.com/company/striata> | Facebook
<https://www.facebook.com/striata.innovation> | www.striata.com
<http://www.striata.com/?signature>

**Comment by mimmi20** [comment]
Thanks

**Comment by JohannesWilkeStriata** [comment]
Plsr

*Johannes Wilke*
*Software Developer*
*Office:* +27 11 530 9600 | *Mobile:* +27(74)588-4099
*Striata on:* Twitter <https://twitter.com/striata> | LinkedIn
<http://www.linkedin.com/company/striata> | Facebook
<https://www.facebook.com/striata.innovation> | www.striata.com
<http://www.striata.com/?signature>

**Comment by JohannesWilkeStriata** [comment]
Hi,

Also found that:
Mozilla/5.0 (Windows; U; Windows NT 5.1; de; rv:1.9.0.7) Gecko/2009021910
Firefox/3.0.7 (via ggpht.com)
<https://udger.com/resources/online-parser?Fuas=Mozilla/5.0%20(Windows;%20U;%20Windows%20NT%205.1;%20de;%20rv:1.9.0.7)%20Gecko/2009021910%20Firefox/3.0.7%20(via%20ggpht.com)>

Was the older UA that Google used for the image cache proxy if you want to
add is also

*Johannes Wilke*
*Software Developer*
*Office:* +27 11 530 9600 | *Mobile:* +27(74)588-4099
*Striata on:* Twitter <https://twitter.com/striata> | LinkedIn
<http://www.linkedin.com/company/striata> | Facebook
<https://www.facebook.com/striata.innovation> | www.striata.com
<http://www.striata.com/?signature>

**Comment by JohannesWilkeStriata** [comment]
Sorry to bother again.

I can give little more info about when GoogleImageProxy UA is used. Any
GMail client (App or webbased gmail.com) will load the linked images in the
email to via GoogleImageProxy. Therefore the GoogleImageProxy currently is
only generated when GMail email client is used.

*Johannes Wilke*
*Software Developer*
*Office:* +27 11 530 9600 | *Mobile:* +27(74)588-4099
*Striata on:* Twitter <https://twitter.com/striata> | LinkedIn
<http://www.linkedin.com/company/striata> | Facebook
<https://www.facebook.com/striata.innovation> | www.striata.com
<http://www.striata.com/?signature>

**Comment by asgrim** [comment]
Fixed by #1114
