### ISSUE TITLE
Samsung Tab A SM-T335Y 8 inch Tab detecting as Phone

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1110]
see serbanghita/Mobile-Detect#590 for more details.

**Comment by hzzg6y** [comment]
Hello,

     Even after adding the Mobiledetect.php file with Samsung Tablet as SM-T335Y, it is still showing as Phone not as  tablet.... Please advice. 

Rgds,

**Comment by asgrim** [comment]
@hzzg6y `Mobiledetect.php` is not part of this project, you'd need to ask whichever project is relevant, thanks
