### ISSUE TITLE
Missing user agents for FB on Android Devices 

### ISSUE THREAD

**Issue by dczaretsky** [browscap/browscap#1125]
I have a significant number of UAs from undetected android devices. Mostly all of them are accessing  FB. 

[android-devices-ua.txt](https://github.com/browscap/browscap/files/591131/android-devices-ua.txt)
[android-devices.txt](https://github.com/browscap/browscap/files/591133/android-devices.txt)

**Comment by mimmi20** [comment]
@dczaretsky Could you provide a PR for this?

**Comment by dczaretsky** [comment]
You might want to have a look at MobileDetect... they keep a more up-to-date list of device detection. It would be great if you guys could integrate all of those devices. Unfortunately, their code does not allow you to pull the make/model... it only tells you if it's mobile. 

You can get the list here:

https://raw.githubusercontent.com/serbanghita/Mobile-Detect/master/Mobile_Detect.json

**Comment by jaydiablo** [comment]
FYI, I'm putting together a PR for this, will take a bit of time, just didn't want anyone else to work on it. :)
