### ISSUE TITLE
Fake MSIE / Trident user agents

### ISSUE THREAD

**Issue by mentor2k1** [browscap/browscap#113]
Hi,

Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; MAFSJS)

this must be an fake agent.

MSIE11 never sends in compatibility mode a trident token, nor a Trident/7.0 token.

This user agent will identify by browscap as an IE11. IE11 also has a Mozilla/5.0 token not a Mozilla /4.0 token.

same with IE9:

Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/6.0)

The trident token is wrong, it´s only Trident/5.0.

Maybe you could add pattern, to identify fake agents and improve the normal pattern for the IE versions.

// Oliver

**Comment by aladin6505** [comment]
I have a problem with IE 11 - goes out as Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0) .
Anybody have a similar problem?

**Comment by mimmi20** [comment]
Maybe the IE8 compatibility mode?
