### ISSUE TITLE
Support for Pinterest bot

### ISSUE THREAD

**Issue by dczaretsky** [browscap/browscap#1132]
Need to support the Pinterest Bot:

Pinterest/0.2 (+http://www.pinterest.com/)

**Comment by mimmi20** [comment]
was part of issue #416.

**Comment by dczaretsky** [comment]
Please reopen. This is not properly supported. The UA above is the Pinterest Bot which originates from Pinterest Servers. Browscap currently has this marked as an app-- not a bot.
