### ISSUE TITLE
Pre-generate the files when running Travis builds for speed

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#1135]
If we pre-generate the files for the build instead of building them whilst running PHPUnit, we can see massive performance increases.

Basically:

 * Use `php -n` to disable any ini files (thus, xdebug does not get loaded) and generate the files
 * THEN run `vendor/bin/phpunit` (but don't generate the files if they already exist).

If the files don't exist, they should still be generated so the existing behaviour is maintained though!

**Comment by mimmi20** [comment]
The second `phpunit` call could be run without xdebug because we call it with the `--no-coverage` option.

**Comment by asgrim** [comment]
Yep, but it's the generation of the files (done in the first `phpunit` run) that takes the time (~10m with xdebug, ~2.5m without)

**Comment by mimmi20** [comment]
@asgrim Is this issue still open? It should be fixed with PR #1222.
