### ISSUE TITLE
Opera user-agent detected as Chrome

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1143]
Saw this user-agent in an Opera proxy report:

>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36 OPR/41.0.2353.69

Typically we only see Opera users on the Opera proxies, so it was odd to see a Chrome user.  I believe this UA is being incorrectly detected as Chrome.  We see similar user agents get detected properly as Opera, like this one:

>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36 OPR/41.0.2353.56

(that one is on Windows though, the one in question is on OSX)

I ran the user agent through the lookup tool on browscap.org, which claims it's using version 6019 and this is the output:

> browser_name_regex 	/^mozilla\/5\.0 \(.*mac os x 10.11.*\) applewebkit\/.* \(khtml.* like gecko\) chrome\/54\..*safari\/.*$/
> browser_name_pattern 	mozilla/5.0 (*mac os x 10?11*) applewebkit/* (khtml* like gecko) chrome/54.*safari/*
> parent 	Chrome 54.0
> comment 	Chrome 54.0
> browser 	Chrome
> browser_type 	Browser
> browser_bits 	32
> browser_maker 	Google Inc
> browser_modus 	unknown
> version 	54.0
> majorver 	54
> minorver 	0
> platform 	MacOSX
> platform_version 	10.11
> platform_description 	Mac OS X
> platform_bits 	32
> platform_maker 	Apple Inc

**Comment by ThaDafinser** [comment]
@jaydiablo this seems really to be a missinterpretion
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_11_6%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F54.0.2840.99+Safari%2F537.36+OPR%2F41.0.2353.69

BrowscapLite is not affected by that issue.

**Comment by mimmi20** [comment]
closed by PR#1145
