### ISSUE TITLE
Epiphany being detected as Safari

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1154]
This user agent string:

>Mozilla/5.0 (Fedora; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.5

Is being detected as Safari as of browscap version 6019, where it should probably be detected as Epiphany instead.

Here's the output from browscap.org:

>browser_name_regex 	/^mozilla\/5\.0 \(.*linux.*x86_64.*\) applewebkit\/.* \(khtml.* like gecko\) .*version\/8\.0.* safari\/.*$/
browser_name_pattern 	mozilla/5.0 (*linux*x86_64*) applewebkit/* (khtml* like gecko) *version/8.0* safari/*
parent 	Safari 8.0
comment 	Safari 8.0
browser 	Safari
browser_type 	Browser
browser_bits 	64
browser_maker 	Apple Inc
browser_modus 	unknown
version 	8.0
majorver 	8
minorver 	0
platform 	Linux
platform_version 	unknown
platform_description 	Linux
platform_bits 	64
platform_maker 	Linux Foundation

**Comment by ThaDafinser** [comment]
It seems to be broken in FULL, but not standard version.
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Fedora%3B+Linux+x86_64%29+AppleWebKit%2F602.1+%28KHTML%2C+like+Gecko%29+Version%2F8.0+Safari%2F602.1+Epiphany%2F3.18.5
