### ISSUE TITLE
Create Gratipay team?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1160]
I noticed you have a Gratipay widget on http://browscap.org, but since Gratipay changed their model a while back (https://gratipay.news/gratipay-2-0-2453d3c53077), I think you have to create a Gratipay team/project to be able to receive payments now.

Any plans/interest in doing this?

I was trying to schedule a payment to the project, but realized you just have an individual account currently.

**Comment by asgrim** [comment]
I should probably just remove it :) we never got anything from it (also, I wondered why it stopped showing but I never bothered checking hah!)

**Comment by asgrim** [comment]
Will be removed from the site in the imminent deployment.
