### ISSUE TITLE
Apache Error

### ISSUE THREAD

**Issue by michael-niniowski** [browscap/browscap#119]
Just looked through the apache error_log file and noticed that ; within [bracketed] user agent fields, the semicolons (';') were logging errors to the error log. Not a biggie, the server still runs, just adds entries on start/restart to error_log. i used:

$sed 's/[^;];[^;]/\\;/g' orig_browscap.ini > browscap.ini

to escape the ';'
this still logs parse errors on line 5318 and 17231.
Platform: Fedora 20 Linux 64, apache-2.4x, php-5.5x

**Comment by asgrim** [comment]
If PHP is not parsing browscap properly, I'd suggest reporting an issue at PHP https://bugs.php.net/

**Comment by sunil15** [comment]
Hi, I am using browscap to get browser and system information and I am getting same error like above in my apache error log file when i start/restart server.

'PHP:  syntax error, unexpected $end, expecting ']' in /etc/php5/apache2/conf.d/php_browscap.ini on line 78'

Can any one help us for it or having

**Comment by asgrim** [comment]
@sunil15 as previously mentioned in this thread, we recommend (and support) using [browscap/browscap-php](https://github.com/browscap/browscap-php) library. I am not sure why the built-in `get_browser()` system is not working, and none of us have been able to investigate yet.

**Comment by Gamesh** [comment]
additional info, if you put browscap.ini into /etc/php.d/ (centos) or other folder on other distributions, that has PHP ini configurations this error happens, as php module tries to load all those configurations and does not interpret browscap.ini correctly. 
Moving browscap.ini to another folder like /etc/browscap.ini solves the error also.

**Comment by ahmadrais** [comment]
Thanks Gamesh...

**Comment by LeonardChallis** [comment]
@Gamesh's work around works for me too. I was finding command line (i.e. cron jobs) were spamming a lot of annoying errors - moving away from /etc/php.d to /etc solved our problems. Thank you!

**Comment by Gamesh** [comment]
Good to hear that it works for you :) 
but I don't think that this is a workaround, I don't believe that this file was meant to be put there. That folder is only meant for php config ini files. And browscap is an ini DB if you can call it that, so it doesn't belong there

**Comment by LeonardChallis** [comment]
When you put it like that, it makes me feel silly I put it there in the first place actually. Of course you're right and it's even better understanding why. Thanks again.
