### ISSUE TITLE
6021 not in Packagist

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1192]
I noticed that after the 6021 release, `composer update` is still pulling down version 6020.

At packagist.org, 6020 is still listed as the latest version: https://packagist.org/packages/browscap/browscap

Is there an automatic hook for this, or do you guys push manually?

https://packagist.org/about

**Comment by asgrim** [comment]
It should be automatic, but fun fact time: I'm not a maintainer on the package. No biggie, I've sent a test hook and it's now up and there :) must've missed the hook or something - thanks for spotting! :)
