### ISSUE TITLE
Opera Mobile incorrectly identified as Android Browser

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1195]
Another on our top 1000 for January:

>Mozilla/5.0 (Linux; U; Android 5.0.2; zh-CN; Redmi Note 3 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 OPR/11.2.3.102637 Mobile Safari/537.36

Browscap is identifying this one as the Android browser, but should probably be Opera Mobile instead due to the "OPR" identifier.

Comparison:

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Linux%3B+U%3B+Android+5.0.2%3B+zh-CN%3B+Redmi+Note+3+Build%2FLRX22G%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+OPR%2F11.2.3.102637+Mobile+Safari%2F537.36

browscap-php 3.0 with 6021 Full.

**Comment by mimmi20** [comment]
This should not be a Opera browser. Opera used the Presto engine until version 12.17 and started with the Blink engine in version 14. The new Opera is Chromium based, but the `Chrome` Token is missing. Aditionally an `Version` token is present, Opera shouldn't have.

see also here: https://dev.opera.com/blog/opera-user-agent-strings-opera-15-and-beyond/

**Comment by asgrim** [comment]
Closed by #1207
