### ISSUE TITLE
FireFox 51.0 identify problem 

### ISSUE THREAD

**Issue by poRAmidol** [browscap/browscap#1200]
Hello!

I use browscap-php (https://github.com/browscap/browscap-php) with full browscap.ini and try to identify my browser.

UserAgent: 
- "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0"

Result: 
[browser_name_regex] => /^mozilla\/5\.0 \(.*mac os x.*\) gecko.* firefox\/.*$/
    [browser_name_pattern] => mozilla/5.0 (*mac os x*) gecko* firefox/*
    [parent] => Firefox Generic
    [comment] => Firefox Generic
    [browser] => Firefox
    [browser_type] => Browser
    [browser_bits] => 32
    [browser_maker] => Mozilla Foundation
    [browser_modus] => unknown
    [version] => 0.0

There is no version.

**Comment by mimmi20** [comment]
see #1177
