### ISSUE TITLE
Wrong browser name

### ISSUE THREAD

**Issue by sebbio** [browscap/browscap#1201]
In base "Second Live Commerce Client" need "Second Life Commerce Client"

**Comment by jaydiablo** [comment]
There's "SecondLive" as well: https://github.com/browscap/browscap/blob/47a9ea952c8bf20c68b806b84693bbcf3257949c/resources/user-agents/apps/second-live/second-live.json#L12 Which should probably be "SecondLife".

We saw that one hit our system with this UA:

>Mozilla/5.0 (Windows; U; Windows NT 5.1; ru-RU) AppleWebKit/533.3 (KHTML, like Gecko) SecondLife/3.7.28.300847 (Second Life Release; default skin) Safari/533.3

We've seen the Commerce Client as well, with this UA:

>Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 6.0 ; .NET CLR 2.0.50215; SL Commerce Client v1.0; Tablet PC 2.0
