### ISSUE TITLE
Firefox 51 MacOS 10.12 missing

### ISSUE THREAD

**Issue by webIMT** [browscap/browscap#1226]
Here is the UA : Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by mimmi20** [comment]
see #1177

**Comment by webIMT** [comment]
It's a 64 bits version (#1177 is about 32 bits). It will be released in 6022 ?

**Comment by mimmi20** [comment]
macOS does not give information, if it has 32 or 64 bits.

**Comment by mimmi20** [comment]
Issue #1177 is part of the 6022 release.

**Comment by mimmi20** [comment]
macOS 10.12 was not added yet for Firefox
