### ISSUE TITLE
Incorrect User Agent Parsing (New Nintendo 3DS)

### ISSUE THREAD

**Issue by zahra-travail** [browscap/browscap#1236]
Using https://browscap.org/ua-lookup, the following user agent is not correctly parsed.

`Mozilla/5.0 (New Nintendo 3DS like iPhone) AppleWebKit/536.30 (KHTML, like Gecko) NX/3.0.0.5.20 Mobile NintendoBrowser/1.8.10156.US`

It is parsed as an iPhone device when the parsing should be similar to 
`Mozilla/5.0 (Nintendo 3DS; U; ; fr) Version/1.7630.US`

Not sure if the device should be "3DS" or "New 3DS".

**Comment by jaydiablo** [comment]
#1240 makes that agent parse similar to the other one, just with the new "New 3DS" device.  However, should there be any distinction between "Netfront NX" and "NintendoBrowser"?

I noticed that the donatj parser does make that distinction, all the others just call it "Netfront NX":

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28New+Nintendo+3DS+like+iPhone%29+AppleWebKit%2F536.30+%28KHTML%2C+like+Gecko%29+NX%2F3.0.0.5.20+Mobile+NintendoBrowser%2F1.8.10156.US

**Comment by zahra-travail** [comment]
To be frank, my main focus is the Device Type. I have data that I must analyze by Device Type and the current result doesn't work for me. The distinction between "Netfront NX" and "Nintendo Browser" is not a material one for my needs. I'll let the ones who need to use that information weigh in on that.
