### ISSUE TITLE
Missing CFNetwork versions

### ISSUE THREAD

**Issue by zahra-travail** [browscap/browscap#1237]
Using https://browscap.org/ua-lookup

The following user agent shows as "Desktop".
`"AppName"/14140 CFNetwork/808.0.2 Darwin/16.0.0`

All CFNetwork > 808.0 show as "Desktop" (as far as our internal data shows).

They should show similar information as any earlier version of CFNetwork. Here's an example of a user agent that's correctly parsed.
`"AppName"/14353 CFNetwork/758.5.3 Darwin/15.6.0`

**Comment by jaydiablo** [comment]
This looks to have been fixed in this commit: https://github.com/browscap/browscap/commit/b99f0d7fceaff121d5ddc27d6e351500e8f73627

Which should be part of the 6022 release (not out yet).

**Comment by mimmi20** [comment]
This was fixed with PR#1185.
