### ISSUE TITLE
Browscap gives Firefox Version 0 back

### ISSUE THREAD

**Issue by hamburger123456** [browscap/browscap#1243]
I get in Win8.1/Win 10/MacOSX the Firefox Version 0 (zero)

**Comment by jaydiablo** [comment]
What useragent string(s) do you see this happen with?

**Comment by hamburger123456** [comment]
Sorry I do not save the useragent-string in my database. I'am using:

        $bc = new Browscap('/www/htdocs/w00b4eb5/huntinggrounds/cache');
        $bc->lowercase = true;
        $bc->silent = true;
        $bc->doAutoUpdate = false;
        // Get information about the current browser's user agent
        $current_browser = $bc->getBrowser(null,true);
        $current_browser[majorver] //this is whats get 0

I have it since 28.01.2017 many times. I think is when firefox >50. 
As I see, I had it formertimes with safari.
I update my browscap-files every day by night.

**Comment by mimmi20** [comment]
@hamburger123456 Please add a dump of the complete result.

**Comment by hamburger123456** [comment]
Sample-Data:


> platform: Win7
> browser: Firefox
> majorver: 0
> ##################################
> array(16) { ["browser_name"]=> string(72) "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0" ["browser_name_regex"]=> string(64) "mozilla/(\d)\.0 \(.*windows nt (\d)\.(\d).*\) gecko.* firefox/.*" ["browser_name_pattern"]=> string(43) "zilla/5.0 (*windows nt 6.1*) gecko* firefox" ["parent"]=> string(15) "Firefox Generic" ["platform"]=> string(4) "Win7" ["comment"]=> string(15) "Firefox Generic" ["browser"]=> string(7) "Firefox" ["browser_maker"]=> string(18) "Mozilla Foundation" ["device_type"]=> string(7) "Desktop" ["device_pointing_method"]=> string(5) "mouse" ```
> ["version"]=> string(3) "0.0" ["majorver"]=> string(1) "0" ["minorver"]=> string(1) "0" ["ismobiledevice"]=> bool(false) ["istablet"]=> bool(false) ["crawler"]=> bool(false) }
> ##################################
> userAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0 
> ```

my PHP:

>         use phpbrowscap\Browscap;
>         $t = "\r\n ";
>         ini_set('memory_limit', '512M');
>         require 'scripts/Browscap.php';
> 
>         $bc = new Browscap('/www/ds/cache');
>         $bc->lowercase = true;
>         $bc->silent = true;
>         $bc->doAutoUpdate = false;
> 
>         // Get information about the current browser's user agent
>         $current_browser = $bc->getBrowser(null,true);
> 
> 
>        echo "platform: ".$current_browser[platform].$t;
>        echo "browser: ".$current_browser[browser].$t;
>        echo "majorver: ".$current_browser[majorver].$t;
> 
>        echo "##################################".$t;
>        var_dump($current_browser);
>        echo $t;
>        echo "##################################".$t;
>        echo "userAgent: ".$_SERVER['HTTP_USER_AGENT'].$t


thx in advance.

**Comment by mimmi20** [comment]
see issue #1177.

**Comment by hamburger123456** [comment]
the issue is closed marked. (asgrim closed this in 940280d 9 days ago)
but the bug is still there.

**Comment by asgrim** [comment]
@hamburger123456 yes, `6022` has not been released yet.
