### ISSUE TITLE
Consider removing the escape character before forward slashes in resource JSON files?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1250]
I've noticed that all of the patterns in the JSON files are escaping "/", which I suspect is an artifact of using php's `json_encode` on the pattern, i.e.:

>UCWEB\/*(#PLATFORM#NOKIA; RM-1045*) U2\/* UCBrowser\/#MAJORVER#.#MINORVER#* U2\/*

Which is the expected output when you do this:

```
php > echo json_encode('UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*');
"UCWEB\/*(#PLATFORM#NOKIA; RM-1045*) U2\/* UCBrowser\/#MAJORVER#.#MINORVER#* U2\/*"
```

However, in the JSON spec, this isn't a requirement, according to this bug filed against PHP some time ago:

https://bugs.php.net/bug.php?id=49366

PHP has this constant, `JSON_UNESCAPED_SLASHES` (implemented as a fix for that bug), that you can pass to `json_encode` which prevents it from escaping the forward slash:

```
php > echo json_encode('UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*', JSON_UNESCAPED_SLASHES);
"UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"
```

As for JSON decoding, PHP doesn't seem to care one way or the other:

Without escaped slashes:
```
php > echo json_encode(['ua' => 'UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*'], JSON_UNESCAPED_SLASHES);
{"ua":"UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"}
php > var_dump(json_decode('{"ua":"UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"}', true));
array(1) {
  ["ua"]=>
  string(77) "UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"
}
```

With escaped slashes:
```
php > echo json_encode(['ua' => 'UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*']);
{"ua":"UCWEB\/*(#PLATFORM#NOKIA; RM-1045*) U2\/* UCBrowser\/#MAJORVER#.#MINORVER#* U2\/*"}
php > var_dump(json_decode('{"ua":"UCWEB\/*(#PLATFORM#NOKIA; RM-1045*) U2\/* UCBrowser\/#MAJORVER#.#MINORVER#* U2\/*"}', true));
array(1) {
  ["ua"]=>
  string(77) "UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"
}
```

IMO, it makes the files more readable/searchable with the slashes un-escaped (saves some bytes too, but that's probably not that important).

Is there a reason that the slashes remain escaped in the resources files?  Could an effort be made (over time) to remove them?

As a test I replaced the escaped slashes in one of the larger files (855 replacements) with an unescaped slash and the tests all passed.

**Comment by mimmi20** [comment]
@jaydiablo If the Escaping is not required, we could remove it. But this should wait, until all open PRs are merged to avoid merge conflicts.

@asgrim Do you have time to review/merge my PRs?

**Comment by asgrim** [comment]
@mimmi20 done. This is a BC break, but it's not exactly like this project follows semver so *shrug* let's do it

**Comment by jaydiablo** [comment]
@asgrim Why is this a BC break if the JSON resources files are never exposed to end-users in the INI/JSON/XML/CSV output?

I'm not suggesting that anything changes with those (though the JSON output file could probably have the same treatment, but you'd have to be more careful with that one since that could break somebody's implementation if they're not using a JSON decoder that ignores the slashes and wrote their own to deal with them).

As shown in my examples above, when PHP reads in the JSON with or without the escaped slashes (when building the files) the slashes are removed by PHP and the decoded JSON is the same:

`["ua"]=> string(77) "UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"`

vs.

`["ua"]=> string(77) "UCWEB/*(#PLATFORM#NOKIA; RM-1045*) U2/* UCBrowser/#MAJORVER#.#MINORVER#* U2/*"`

The escaped slashes should never end up in the INI one way or the other since `json_encode` isn't used for that output (the only place I see `json_encode` being used for writing files is in the JSON writer/formatter.

This should just be an internal change to make the resource files easier to read/search through.

That said, it doesn't have to happen all at once.  As I'm condensing some of the device stuff in these files I could do a quick replace on any in the file I'm working on, and moving forward whenever a file is touched for new/updated agents, the escaped slashes could be removed in the touched files.

If a tool is used to generate/modify these files, then that tool should be modified to use that `JSON_UNESCAPED_SLASHES` constant on the `json_encode` call so that new files aren't created with the escaped slashes.

**Comment by asgrim** [comment]
Ah; sorry I thought we were talking about the "output" JSON :)

**Comment by jaydiablo** [comment]
I can see why you thought that :)  I modified the title slightly.
