### ISSUE TITLE
Pattern test coverage

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1253]
So as I'm condensing some of these patterns in various files (no particular method to the madness at the moment), I was a bit concerned that I may be modifying patterns incorrectly (even though I'm being careful not to). I was (incorrectly) under the assumption that if patterns are added to the resources, they've had a test added as well, but as I realized in #1251 this isn't always the case.

I was curious how many patterns exist in the INI file that aren't touched by a test from the test suite.

I extracted the patterns from the INI, but turned all digits into hash signs (#) in order to make the list a bit more manageable/realistic (I don't think it's terribly important that every possible version of every possible pattern is touched by a test, that would be a bit insane).  I then ran the test suite, and extracted all patterns that were used against the user agents in the suite (again, replacing all digits with "#").

I get 13,811 unique patterns (with digits removed) from the INI file (this is taken from the update step of browscap-php, so it doesn't include the "group" patterns).

[available_patterns.txt](https://github.com/browscap/browscap/files/800795/available_patterns.txt)

And from the test suite I get 3,467 patterns used.

[tested_patterns.txt](https://github.com/browscap/browscap/files/800796/tested_patterns.txt)

If I'm doing this right, that leaves a lot of untested patterns! There are of course a lot of small variations in patterns aside from the version numbers (i.e. minor platform/device differences). And as I understand it, a lot of the files have a sort of "catch-all" pattern(s) that are used to at least identify the browser with basic properties based on the UA containing a certain structure/keywords for that browser.  These probably don't typically have a test UA to go with them.

Anyhow, I was curious what it would look like if I ran browscap-php against a large list of user-agents, and only dumped the patterns/uas that browscap doesn't cover during its own tests.

The list I used comes from various other parsers' test suites (about 47k agents). This dumped 1,761 unique, uncovered patterns (with digits replaced with "#").

[all-suites-uncovered-patterns.txt](https://github.com/browscap/browscap/files/800808/all-suites-uncovered-patterns.txt)

And I've also extracted just one useragent string for each pattern and assembled those into a text file:

[useragents-from-uncovered-patterns.txt](https://github.com/browscap/browscap/files/800810/useragents-from-uncovered-patterns.txt)

If you're at all curious to see **all** of the useragents collected during this process (that were parsed using an uncovered pattern), here's that list, grouped by each pattern:

[all-useragents-from-uncovered-patterns.txt](https://github.com/browscap/browscap/files/800814/all-useragents-from-uncovered-patterns.txt)

Is there much interest in adding some of these useragents to the test-suite to increase the coverage of the patterns?  Certainly a tedious task.

Are there any built-in tools to analyze this better than the approach that I took?

I could do this against a more "real world" list of agents if that seems like a better approach.

**Comment by jaydiablo** [comment]
So doing this with a large set of user-agents from our server logs, and **most** (of what I've looked at, quite a bit of agents to scan) of the patterns that show up are the catch-alls that come up when a version of an agent is missing or something like that.

So they're not really patterns that there should be a test for, because once the version is bumped, or the device is added, the tests would break.

Not all of the patterns I'm looking at are like this, but a lot of them are.

I do have some that should be added to cover some patterns that don't have a test case yet (usually bots/crawlers).

**Comment by mimmi20** [comment]
It depends on the age of the pattern, if a test is available.
When @asgrim started this project some time ago by taking over the old sources and moving/refactoring them, there a lot of pattern existed, but no tests.

**Comment by asgrim** [comment]
Yep, as @mimmi20 said, basically, the test suite was started when we open sourced everything and switched from VB to PHP. I do have a database of a load of user agents from the old VB stuff, but it's been so long since I looked I'm not sure how useful this would be.

**Comment by asgrim** [comment]
It's kinda difficult to measure "coverage" as such; working on the assumption there are essentially infinite user agents, there's no way we can cover them all. That's why we just add newly reported patterns as tests and so on, that prevents regressions of any reports at least.

That said, it'd be nice to have the "major" browsers covered perhaps.

**Comment by jaydiablo** [comment]
I've been thinking a little bit about how this could be done so that at least there's an idea of which patterns in the JSON files have a corresponding test and which don't.

Since the parser that runs the tests runs on the browscap.ini file (and really has no knowledge of the underlying JSON structure), maybe it's possible to add a sort of "pattern id" to the properties in the INI file that would only be inserted when it's built with a certain flag (the file that gets published to browscap.org wouldn't have this data, since it would bloat the file)?

It would obviously be a pain to insert such an id into the resource JSON files manually, so I think it would have to be something that could be built automatically when the files are being parsed.

I haven't tested playing with this at all, so perhaps this is a bit naive, but I was thinking the ID could be something like this:

`<filename>:u<position-in-userAgents-array>:c<position-in-children-array>:p<platform-name>:d<device-name>|dm<device-match-key>`

So, using this structure, here's what an ID might look like for this pattern (which is derived from this entry in the JSON files: https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/chrome/chrome-55-on.json#L53):

`Mozilla\/5.0 (*Linux*Android?4.0*A510 Build\/*) AppleWebKit\/* (KHTML* like Gecko) Chrome\/56.*Safari\/*

`chrome-55-on.json:u0:c3:pAndroid_4_0:dAcer A510`

There may need to be a better way to separate the entries, or maybe some sort of escaping on colons, but just brainstorming at the moment.

If these IDs are collected during the test run, it may be possible to compare them to the same IDs as they are generated from the JSON files (when building the INI file for the test run).

Of course it would be nice if that data could be turned into something that Scrutinizer or other tools can read, but since we're trying to cover a data file, rather than executable code, I'm not sure how feasible something like that would be (those reports typically operate on lines, and with the platform arrays we'd want to be able to look at the position of the line, not just the line itself).

Ideally a coverage report would look something like this:

<img width="977" alt="screen shot 2017-02-26 at 3 25 42 pm" src="https://cloud.githubusercontent.com/assets/136907/23344345/f24da418-fc37-11e6-988b-1b1626a91738.png">

At quick glance you can tell which pattern + device + platform was touched by a test and which are missing test coverage.

I'm intentionally leaving versions out of this, as I think trying to have every pattern for every browser version available covered is unrealistic, but a version chunk of the ID could be added, which may allow the report to color the versions array as well:

<img width="414" alt="screen shot 2017-02-26 at 3 32 51 pm" src="https://cloud.githubusercontent.com/assets/136907/23344396/df9a4a96-fc38-11e6-97af-d2c0de745c78.png">

I'm not sure how useful that would be though, as I bet they'd always end up being yellow/red (partial/no coverage).

**Comment by asgrim** [comment]
That is indeed very interesting! My concern is that this seems like a lot of effort for admittedly a useful report, but do we have the actual resources to go and then add coverage in to follow this up? Maybe being able to visualise it may help folks contribute tests though. Could we start with the "lite" stuff only? I think it'd be fairly important to have good coverage there at least. I'm quite happy to publish this on browscap.org also btw, assuming we can just generate a bunch of HTML; we use CloudFlare so it can be cached heavily by them.

**Comment by asgrim** [comment]
Also, I'd second the use of pre-existing tools to do this; let's not re-invent the wheel.

**Comment by jaydiablo** [comment]
Yeah, may be tricky to get the output of something like this to jive well with something like the HTML coverage report from PHPUnit or something similar.  I may play with it though at some point.

Anyhow, just an initial test of generating the so-called "patternId" for every pattern during the INI build process (and storing in the INI file), and then outputting the same thing during the FULL test run.

51,229 unique pattern ids are generated from the JSON resource files (not doing any sort of version expansion for this).

4,021 unique patterns are encountered during the FULL test run.

7.8% coverage? Perhaps some work to do there ;)

I think having an HTML report to look at would certainly be ideal for being able to tell where the gaps in coverage lie, and if they're in the browsers that are cared about the most (as you said, the "major" browsers).

Here's a small section of one of the UC Browser files that I've recently spent time with (most sections don't look this covered):

<img width="1556" alt="screen shot 2017-02-27 at 11 21 34 pm" src="https://cloud.githubusercontent.com/assets/136907/23393974/a36d40ee-fd43-11e6-92e9-9162ae633d47.png">

I haven't fully vetted these pattern ids, so there could be some bugs in the generation process. Here are some files though for your perusal ;)

Raw pattern ids generated from a build of the INI file (these are stored in the patterns in the INI file as a "PatternId" property):
[patternIds.txt](https://github.com/browscap/browscap/files/805895/patternIds.txt)

Pattern ids that were used to satisfy a user-agent test from the UserAgentTest suite:
[results_dedup.txt](https://github.com/browscap/browscap/files/805894/results_dedup.txt)

Unified diff of those two files:
[patterns_diff.txt](https://github.com/browscap/browscap/files/805893/patterns_diff.txt)

The version numbers in those patternIds is just something I'm using to differentiate two divisions that have the same name  (something like "UC Browser #MAJORVER#.#MINORVER#").  I think the name of the JSON file would work fine here as well, but that's not available in the current classes.  This is just an `implode` of the `Version` property of the division.

**Comment by jaydiablo** [comment]
I modified the pattern ids to have the resource file name instead of the division name + versions and was able to use that to make this little CSV file:

[coverage.csv.zip](https://github.com/browscap/browscap/files/807585/coverage.csv.zip)

Number of unique patterns, number covered and coverage percent by file name.

Here's just a quick snapshot of the files with the most patterns:

![image](https://cloud.githubusercontent.com/assets/136907/23416208/351eae50-fd9f-11e6-8c1f-3cc8ca47abca.png)

**Comment by jaydiablo** [comment]
I have a mistake in that last CSV (the previous comment is affected as well). I was using a parameter to `uniq` to strip out the duplicate patterns in the `results.txt` file I had generated from the test suite that was excluding all patterns that appeared more than once in the file (rather than leaving a single line for those duplicates).

After fixing this, I end up with 4,706 covered patterns, which is 9.2% coverage.

Here's the fixed CSV file:

[coverage.csv.zip](https://github.com/browscap/browscap/files/809215/coverage.csv.zip)

**Comment by jaydiablo** [comment]
As for the HTML report showing the coverage, I've played around a little bit with building a `coverage.json` file (based on Istanbul's coverage report) manually from one of the resource files, and have it working with both istanbul (generates a local HTML report) and codecov.io (hosted coverage processing/comparison tool) and it seems to work fairly well:

Local:
<img width="629" alt="screen shot 2017-03-01 at 12 08 51 pm" src="https://cloud.githubusercontent.com/assets/136907/23476412/ec0101e4-fe77-11e6-9fe1-067045f3dec3.png">

codecov.io
https://codecov.io/gh/jaydiablo/browscap/src/67c3d74f88f12042cb133936689cc987af400b26/resources/user-agents/crawlers/social-networking/friendica.json

The nice thing about codecov.io is that it can use both the coverage report generated for the PHP files as well as a coverage report generated for the JSON files, and combine them all for a total coverage report for the project (Scrutinzer may be able to do this as well, I haven't tested yet).

This particular coverage.json was hand-built as a test (and I lied on some of the data, this JSON file is actually 100% covered, but I wanted to see what a failure line looked like), but it should be feasible to generate it automatically from the pattern ids I'm collecting.

**Comment by jaydiablo** [comment]
I've put together a (crude) script that uses a JSON lexer to step through the resource JSON files and build a coverage.json file using the touched patterns for coverage data.

End result is this: https://codecov.io/gh/jaydiablo/browscap/tree/cbbf140ce4cb6f5bd3301e2f3e6c23cd27eb431e

I made each "match" property of each "child" of the "children" object a function, and then each platform or device (if using the "devices" hash) a branch structure (a switch statement in this case).

That ends up looking like this for a file that uses the "devices" expansion: https://codecov.io/gh/jaydiablo/browscap/src/cbbf140ce4cb6f5bd3301e2f3e6c23cd27eb431e/resources/user-agents/browsers/uc-browser/uc-web-10.json

One side effect of the devices expansion is that you can't tell from a report like this if every platform + device combination for a pattern is touched.  I did notice that the line coverage number on the platform line is only showing "1" test covering it, so I could probably look into that to at least show that a pattern with 5 devices and 1 platform has 5 tests (at least) hitting the platform line.  I don't know if that's all that important though. It's nice to see if a platform and/or device is touched at all by the tests, which may be enough for the purposes of testing for regressions.

One thing I noticed with codecov.io's report vs. the local Istanbul generated report is that on lines that have multiple platforms, but not all of them are covered, it's hard to see the uncovered ones on codecov.io:

## codecov.io:
<img width="1185" alt="screen shot 2017-03-03 at 10 01 21 am" src="https://cloud.githubusercontent.com/assets/136907/23560701/98a51f9e-fff8-11e6-9bba-fb7aa145a75a.png">

## Istanbul:
<img width="1214" alt="screen shot 2017-03-03 at 10 00 21 am" src="https://cloud.githubusercontent.com/assets/136907/23560711/a0c99b50-fff8-11e6-96ef-a3593e891dcc.png">

This may be the result of adding line coverage, which I could possibly remove to see how it changes the reports.

**Comment by asgrim** [comment]
Oh this is really nice! Could you give me a rundown of how to get this set up on the main project so we can see coverage in PRs etc. please?

**Comment by jaydiablo** [comment]
@asgrim working on it, it's still a bit of manual work (capturing line dumps from test runs and such) but I think it could be added to the automatic test runs (when coverage is enabled).  I think that's the next step.

I believe codecov.io can be used in the same way that scrutinizer is (have it run as a hook in PRs).

I did look to see if Scrutinizer supports coverage on multiple languages, and they do, but they only support the clover format for JS.  One issue I noticed with clover is that it doesn't seem to do a good job of reporting coverage of different branches when they occur on the same line (like the "platforms" typically do). 

Either way, codecov.io seems pretty nice for keeping track of coverage change over time and hooking into github workflow. I haven't used it though outside of these tests, so can't vouch for it.

**Comment by jaydiablo** [comment]
Well, I can't quite get the codecov.io report where I want it, but I'll shoot them an email to see if this is becuase it's on JSON files rather than actual JS files or something else, but here's where I'm at with codecov.io:

https://codecov.io/gh/jaydiablo/browscap/tree/a1115f2f76366a0de4cad130ed079855e2dc9b74/resources/user-agents

The local report that Istanbul generates is a bit nicer as it shows the # of tests that hit each line:

<img width="1196" alt="screen shot 2017-03-03 at 7 11 34 pm" src="https://cloud.githubusercontent.com/assets/136907/23575111/4460a8e8-0045-11e7-8576-a6d152533f21.png">

I know that codecov.io is capable of that sort of output, as seen here: https://codecov.io/gh/babel/babylon/src/f46dfc8e466c4e884f023cbb6dcd5e6bd68f8058/src/parser/expression.js

But for some reason it won't trigger that for me.

The only big issue with the way that codecov.io shows the report is that on lines where there are multiple platforms, like here: https://codecov.io/gh/jaydiablo/browscap/src/a1115f2f76366a0de4cad130ed079855e2dc9b74/resources/user-agents/browsers/uc-browser/uc-web-10.json#L392  You can't tell which platform is covered and which is not.  In Istanbul's report this is easy to spot:

<img width="1167" alt="screen shot 2017-03-03 at 7 15 11 pm" src="https://cloud.githubusercontent.com/assets/136907/23575143/c23372a0-0045-11e7-8137-45d165551543.png">

**Comment by jaydiablo** [comment]
I haven't heard back from codecov.io yet about the format of that report, but I do have the coverage being built and submitted to codecov.io in the travis build from my branch.

For example, here's the build that pushed the coverage.clover file to codecov.io (PHP coverage):
https://travis-ci.org/jaydiablo/browscap/jobs/208391675

And here's the build that pushed the coverage.json file to codecov.io (for the pattern coverage):
https://travis-ci.org/jaydiablo/browscap/jobs/208391677

(look down at the bottom of the log to see the codecov command's results).

That resulted in this report at codecov.io:
https://codecov.io/gh/jaydiablo/browscap/commit/00eed1a233564ff4be5243fa6735c1a0b0253af7

If you navigate to the "Files" tab you can see the coverage percentages for the resource files and the PHP src files.

Initially I thought I'd only do the pattern id generation and collecting when coverage was enabled (by looking at xdebug's coverage enabled function) but then I realized that when the useragent tests are ran, coverage is disabled, so it's doing the pattern id generation/collecting whenever the useragent test suite is run.

I've confirmed that the pattern ids are not inserted into the browscap files outside of the useragent test runs.

I'd like to write some tests to cover the new coverage generation class I've added, and to confirm that pattern id generation is only happening when it should be.  Other than that though, does this seem like a good approach?  Should I look at a different coverage service, like coveralls?

**Comment by jaydiablo** [comment]
I committed a couple of tests to cover a previously uncovered file in my branch, and codecov shows the coverage difference in the coverage report:

<img width="457" alt="screen shot 2017-03-06 at 5 43 49 pm" src="https://cloud.githubusercontent.com/assets/136907/23636864/4d6abaf8-0295-11e7-9204-1e1a39f5aacd.png">

Also, as a test, I enabled the codecov integration to see what it would do with a pull request, and here's what it did to a PR I did against my master branch:

<img width="837" alt="screen shot 2017-03-06 at 5 53 43 pm" src="https://cloud.githubusercontent.com/assets/136907/23636966/022d1652-0296-11e7-885b-dfda33bb9618.png">

Can be seen here:

https://github.com/jaydiablo/browscap/pull/1

It'll probably be more interesting when new resource files are added/updated, but seems pretty cool.

**Comment by asgrim** [comment]
Let's stick with codecov.io :) seems ideal, and really useful feedback :) nice!

**Comment by jaydiablo** [comment]
I did peek at coveralls, but it seemed a bit cumbersome to submit coverage reports to them (have to do it in application code, so would probably have to write a small PHP command/script and/or a Node app to submit the coverage files).  codecov.io makes that process pretty easy with their generic coverage uploader.

Anyhow, I think I'm about ready to put all of this into a PR.  It's going to require a very small change to browscap-php as well (so that the pattern ids are visible during the test run).  I'll wrap up the necessary changes for that first, and submit a PR.  Once that's merged in, I can put together the PR for this project which is the bulk of the changes (that way when it pulls down browscap-php dev-master in the PR run, the travis builds will pass).

**Comment by mimmi20** [comment]
for coveralls I use this command to publish a coverage report 'wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php -n coveralls.phar --verbose --coverage_clover=clover.xml`

**Comment by jaydiablo** [comment]
@mimmi20 nice, perhaps a similar technique could be done with the JSON coverage using something like this:

https://github.com/nickmerwin/node-coveralls

However, looks like coveralls wants LCOV data, which I do notice Istanbul outputs when I locally process the coverage.json file I'm writing.  Might be possible to install Istanbul during the travis build, process the report with it, then send up the LCOV data.

I'm not sure the extra steps are worth it, probably would depend on benefits that coveralls can provide over codecov.io.  I'm willing to test it though.

**Comment by jaydiablo** [comment]
That wasn't too bad, it did add quite a bit of time to the `COMPARE` build though as the `istanbul report` command takes a bit of time to run (it's necessary to convert the coverage.json file into LCOV report format).

Here's that UC Browser file I've been looking at in the various reports:

https://coveralls.io/builds/10482071/source?filename=resources%2Fuser-agents%2Fbrowsers%2Fuc-browser%2Fuc-web-10.json

Unfortunately, coveralls also doesn't render the uncovered statements on the same line differently from the covered ones:

https://coveralls.io/builds/10482071/source?filename=resources%2Fuser-agents%2Fbrowsers%2Fuc-browser%2Fuc-web-10.json#L259

So no advantage there over codecov.io.  However, it is showing the proper counts on each line, which is nice.

The PHP upload failed due to a Symfony Console exception, so the total coverage percentage isn't correct here: https://coveralls.io/github/jaydiablo/browscap  I can try to resolve that though to get a full coverage report for comparison.

As far as I can tell, coveralls.io also has thresholds you can set that would trigger a build failure, and has a bot that will comment on a PR after it processes the coverage, which seems par for the course for these tools.

I'm open to either system really, do either of you prefer one over the other?

**Comment by jaydiablo** [comment]
Ok, fixed the issue with the PHP coverage uploader, here's the merged stats at Coveralls:

https://coveralls.io/github/jaydiablo/browscap

[![Coverage Status](https://coveralls.io/repos/github/jaydiablo/browscap/badge.svg?branch=pattern-coverage-coveralls)](https://coveralls.io/github/jaydiablo/browscap?branch=pattern-coverage-coveralls)

**Comment by mimmi20** [comment]
Before yesterday I did nothing with codecov, so I dont know much about them.

**Comment by jaydiablo** [comment]
I like the way that codecov.io allows you to browse through directories, showing you the coverage percentage of all files in a directory:

https://codecov.io/gh/jaydiablo/browscap/tree/a1115f2f76366a0de4cad130ed079855e2dc9b74/resources/user-agents

https://codecov.io/gh/jaydiablo/browscap/tree/a1115f2f76366a0de4cad130ed079855e2dc9b74/resources/user-agents/browsers

This makes it easier to look for files/directories that need some work on the coverage front.

Coveralls' file browser doesn't group the files by directory, it's just a listing, so is less effective for that IMO.

The local Istanbul report could be used for this though, if Coveralls seems like the better service for other reasons.

Could run with both for a little while to see how each handles PRs and other updates.
