### ISSUE TITLE
Spotify Useragents detecting as "Default Browser"

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1287]
Have a handful of useragents that detected as "Default Browser" that have "Spotify/1.0" in them:

>Mozilla/5.0 (Windows NT 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.11.134 Safari/537.36
Mozilla/5.0 (Windows NT 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.3.101 Safari/537.36
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.10.107 Safari/537.36
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.4.90 Safari/537.36
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.5.186 Safari/537.36
Mozilla/5.0 (Windows NT 5.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.10.107 Safari/537.36
Mozilla/5.0 (Windows NT 5.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.10.107 Safari/537.36
Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.1.1060 Safari/537.36
Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.10.107 Safari/537.36
Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.9.133 Safari/537.36
Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.11.129 Safari/537.36
Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.4.90 Safari/537.36
Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.7.157 Safari/537.36
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.11.134 Safari/537.36
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.7.157 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; ; NCLIENT50_AAPAAA7A4B736F; ; 11sungb_AAP7A7082C5C2C) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.7.157 Safari/537.36
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/0.9.15.27.g87efe634 Safari/537.36
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.11.129 Safari/537.36
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.3.101 Safari/537.36
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Spotify/1.0.5.178 Safari/537.36

I noticed that there is a spotify rule in the media-players section of the apps resource files: https://github.com/browscap/browscap/blob/ab390ea1804c468d85aa9093c4180cd58f397a88/resources/user-agents/apps/media-players/media-players.json#L461  Which appears to have been added for issue #993 which references an un-merged PR for UA Parser.  That said, UA parser does detect these agents as "Spotify" because of this regex: https://github.com/ua-parser/uap-core/blob/6e91b2dfc1f2b8c0775a5e37166b31144171f80a/regexes.yaml#L294 (there are test cases for this as well: https://github.com/ua-parser/uap-core/search?utf8=%E2%9C%93&q=spotify)

Browscap doesn't detect these as Spotify because there's no leading asterisk on the Spotify rules in the media-players.json file. Should that be changed to detect these properly?

**Comment by mimmi20** [comment]
This hould be changed.
