### ISSUE TITLE
Firefox 52 & 51 are not properly recognized (MajorVer==0)

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#1299]
For example:

> Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

Is recognized as majorver "0", where 52 is expected.

**Comment by mimmi20** [comment]
see issue #1177.

**Comment by paulrutter** [comment]
Ah thanks, i was under the impression that closed (and fixed) issues would automatically become available on the files on browscap.org?
Or do i have to use a different source?

**Comment by asgrim** [comment]
@paulrutter hi Paul; at the moment the process is manual; and sorry I haven't had a chance to do it for a while - it's not forgotten don't worry!

**Comment by paulrutter** [comment]
Good to know that browscap.org still is the one source to be used 👍 
Thanks, i'll wait until 6022 is released.
