### ISSUE TITLE
Add iOS 10.3

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1303]
I mentioned this in #1302, but we're starting to see iOS 10.3 versions in our logs (most likely users using the Beta version of the OS).

Sounds like it should be released pretty soon, but isn't out yet (outside of the beta program).

Should probably consider adding it soon no?

**Comment by mimmi20** [comment]
We dont need to wait until the release.

**Comment by jaydiablo** [comment]
I'm searching through our logs right now to see what browsers/apps are most prevalent. I'm not sure how you typically bump an iOS version (apply to all that already have 10.2 defined? Wait until you see Useragents using it?), but figured it may be useful to see what browsers/apps are starting to show up with that OS version.

**Comment by jaydiablo** [comment]
Here's what we've seen so far, more or less (I made some tickets that have agents that should probably be broken out from these):

* Facebook App
* Safari     
* Mobile Safari UI Webview
* Chrome      
* Google App  
* Firefox         
* Pinterest App
* Twitter App       
* UC Browser
* Opera Mini

**Comment by mimmi20** [comment]
We dont really have a system for adding new platform versions.

**Comment by jaydiablo** [comment]
I'll go ahead and add it for browsers/apps that already have iOS 10.2, and add some tests to go with the changes where I have applicable useragents.
