### ISSUE TITLE
Separate Facebook App and Facebook Messenger App?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1304]
When looking at some useragents for #1303 I noticed that of the ones that were detected as Facebook by Browscap, there are some that are detected as Facebook Messenger by WhichBrowser:

>Mozilla/5.0 (iPad; CPU OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E5260b [FBAN/MessengerForiOS;FBAV/108.0.0.36.70;FBBV/51642321;FBDV/iPad4,7;FBMD/iPad;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/;FBID/tablet;FBLC/en_US;FBOP/5;FBRV/0]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/102.0.0.25.70;FBBV/48148560;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/MetroPCS;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/102.0.0.25.70;FBBV/48148560;FBRV/0;FBDV/iPhone9,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/3;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/103.0.0.29.70;FBBV/48707033;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/103.0.0.29.70;FBBV/48707033;FBRV/0;FBDV/iPhone7,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/103.0.0.29.70;FBBV/48707033;FBRV/0;FBDV/iPhone8,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/104.0.0.28.69;FBBV/49236804;FBRV/0;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/3;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e [FBAN/MessengerForiOS;FBAV/105.0.0.24.69;FBBV/49825185;FBRV/0;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/3;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E5260b [FBAN/MessengerForiOS;FBAV/108.0.0.36.70;FBBV/51642321;FBDV/iPhone5,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E5269a [FBAN/MessengerForiOS;FBAV/108.0.0.36.70;FBBV/51642321;FBDV/iPhone7,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/3;FBCR/AT&T;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E5273a [FBAN/MessengerForiOS;FBAV/109.0.0.6.70;FBBV/52431868;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/2;FBCR/Simple;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E5277a [FBAN/MessengerForiOS;FBAV/109.2.0.9.70;FBBV/52747312;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3;FBSS/3;FBCR/Sprint;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]

These are mostly all the same, they just differ in build/version numbers.  The key differentiation between these and normal Facebook App appears to be the presence of this string (for iOS agents anyhow, I haven't looked for the Android equivalent):

>MessengerForiOS

**Comment by mimmi20** [comment]
We did not separate these two apps.

**Comment by jaydiablo** [comment]
Here's what the Android ones look like:

>Mozilla/5.0 (Linux; Android 4.4.4; Z793C Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/97.0.0.13.71;]
Mozilla/5.0 (Linux; Android 5.0; SM-G900V Build/LRX21T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/110.0.0.14.69;]
Mozilla/5.0 (Linux; Android 5.1.1; KFFOWI Build/LVY48F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/49.0.2623.105 Safari/537.36 [FB_IAB/MESSENGER;FBAV/109.0.0.24.70;]
Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG-SM-G530A Build/LMY48B; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/110.0.0.14.69;]
Mozilla/5.0 (Linux; Android 5.1.1; SM-J320P Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/109.0.0.24.70;]
Mozilla/5.0 (Linux; Android 5.1.1; VS425PP Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/110.0.0.14.69;]
Mozilla/5.0 (Linux; Android 5.1; HTCD100LVWPP Build/LMY47O; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/108.0.0.20.70;]
Mozilla/5.0 (Linux; Android 5.1; Z820 Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/54.0.2840.68 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/109.0.0.24.70;]
Mozilla/5.0 (Linux; Android 6.0.1; LGLS450 Build/MXB48T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/50.0.2661.86 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/100.0.0.29.61;]
Mozilla/5.0 (Linux; Android 6.0.1; SM-J320V Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/108.0.0.20.70;]
Mozilla/5.0 (Linux; Android 6.0.1; Z981 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/106.0.0.23.70;]
Mozilla/5.0 (Linux; Android 6.0; HTC One A9s Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/104.0.0.13.69;]
Mozilla/5.0 (Linux; Android 6.0; LG-H901 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/100.0.0.29.61;]
Mozilla/5.0 (Linux; Android 7.0; LG-H830 Build/NRD90U; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/107.0.0.18.70;]
Mozilla/5.0 (Linux; Android 7.0; SAMSUNG-SM-G935A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/106.0.0.23.70;]

Just have the "MESSENGER" keyword.

**Comment by jaydiablo** [comment]
There's another Android app showing up, but not sure which app it is:

>Mozilla/5.0 (Linux; Android 7.0; SM-G920F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36[FBAN/EMA;FBLC/sr_RS;FBAV/37.0.0.4.69;]

https://play.google.com/store/apps/developer?id=Facebook

Anyone with an Android device want to figure it out? :)  I'll make sure it gets caught as Facebook App for now.
