### ISSUE TITLE
Instagram App being detected as Mobile Safari Web View

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1307]
These should probably be detected as Instagram App, no?

>Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e Instagram 10.3.0 (iPhone8,1; iOS 10_3; en_US; en-US; scale=2.00; gamut=normal; 750x1334)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e Instagram 10.6.0 (iPhone8,2; iOS 10_3; en_US; en-US; scale=2.61; gamut=normal; 1080x1920)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e Instagram 10.7.0 (iPhone8,1; iOS 10_3; en_US; en-US; scale=2.00; gamut=normal; 750x1334)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.20 (KHTML, like Gecko) Mobile/14E5230e Instagram 10.8.0 (iPhone9,4; iOS 10_3; sv_SE; sv-SE; scale=2.61; gamut=wide; 1080x1920)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.23 (KHTML, like Gecko) Mobile/14E5239e Instagram 10.8.0 (iPhone7,2; iOS 10_3; en_US; en-US; scale=2.00; gamut=normal; 750x1334)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.29 (KHTML, like Gecko) Mobile/14E5249d Instagram 10.11.0 (iPhone8,4; iOS 10_3; ar_QA@numbers=latn; ar-QA; scale=2.00; gamut=normal; 640x1136)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.29 (KHTML, like Gecko) Mobile/14E5249d Instagram 10.9.0 (iPhone7,1; iOS 10_3; ar_IQ@numbers=latn; ar-IQ; scale=2.88; gamut=normal; 1080x1920)
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E5260b Instagram 10.12.0 (iPhone8,2; iOS 10_3; en_US; en-US; scale=2.61; gamut=normal; 1080x1920)

**Comment by jaydiablo** [comment]
Question about how this should be named.

Initially I was just going to change the name of the existing Instagram app file to `instagram-app-1-0-to-7-8.json` which is the version range it contains. Then this new file I was going to call `instagram-app-8-0-on.json` that has the newer format. However, I have examples of this format that go back as far as version 7.3:

>Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C92 Instagram 7.3.0 (iPhone6,2; iPhone OS 10_2; en_US; en)

So it seems like there was possibly some overlap between the "Instagram *" format and this "mozilla-like" format that I'm adding patterns for.  Should I start at the earliest version I've seen (7.3) and name the file `instagram-app-7-3-on.json`?

FTR, all of the Android new-format useragents I pulled are in the 10.x range, it's only the iOS ones that go pre-10.x. There aren't many that are pre-8.x (I have 6).

Maybe I should do a file that is 7.3 - 9.9 or whatever (pre-10.x) that just contains iOS patterns, and then do a 10-on that includes the Android patterns. There were pre-10.x versions released for Android, just hard to say which format the older versions used: https://instagram.en.uptodown.com/android/old

I'll dig a bit more in our logs, let me know what you think.

**Comment by jaydiablo** [comment]
Actually, I do have Android versions with the Mozilla format as far back as version 7.2.

**Comment by jaydiablo** [comment]
An interesting side effect here.

The pattern I'm using is very similar to what's used for Android browser and Android WebView, but has "Instagram" at the end.  I tried setting up a generic pattern to catch any versions that aren't defined in the main file. This works for most Android user agents, but the ones that have a device defined in either the Android Browser or Android Webview files won't get detected as Instagram App since the pattern + device replacement cause the Android Browser/Android Webview pattern to be longer, thus taking priority.

I bumped out the generic pattern a little bit to deal with this, but there are still some that have a long device identifier (match) that cause them to match to Android Browser/Webview.

Of course, this can be fixed by adding these devices to the instagram app file, just thought it was worth mentioning as it could happen to other useragents that I'm not looking at.

I think it sort of raises the question if we should look at duplicating some of those device lists across different (but similar in structure) browsers/apps, particularly for these android apps. I do fear that doing that (and maintaining it) would cause the full browscap file to grow considerably.

**Comment by mimmi20** [comment]
If we had a command for this, we could do that. Otherwise it would be too much work to do that.

**Comment by jaydiablo** [comment]
Yeah, it's something I've been thinking about dealing with better. I did put together a little script that just analyzes the different devices (if they're in the `devices` property of a child) and spits out what sort of matches have been used for that device as well as what platforms it has been found being used with.  More curiosity than anything else, but could possibly expand on that to build a command that could do such a thing.

Anyhow, one other thing I wanted to discuss with Instagram. Here are the versions that I've found in our logs (using the "new" Mozilla format):

```
["10.13", "10.12", "10.11", "10.10", "10.9", "10.8", "10.7", "10.6", "10.5", "10.4", "10.3", "10.2", "10.1", 10, "9.8", "9.7", "9.6", "9.5", "9.4", "9.3", "9.2", "9.1", 9, "8.5", "8.4", "8.3", "8.2", "8.1", 8, "7.21", "7.20", "7.19", "7.18", "7.17", "7.16", "7.15", "7.14", "7.13", "7.12", "7.11", "7.10", "7.9", "7.8", "7.7", "7.6", "7.5", "7.4", "7.3", "7.2"]
```

That seems like quite a bit of versions. Should I reduce this down to just the Major version, like how Chrome is done?  That would make it just:

```
[10, 9, 8, 7]
```

**Comment by mimmi20** [comment]
I don't know the differences between the minor versions of the Instagramm App.

**Comment by mimmi20** [comment]
Chrome only releases Major versions.

**Comment by mimmi20** [comment]
For the Instagram App we may reduce the versions.
