### ISSUE TITLE
UCbrowser being detected as Android

### ISSUE THREAD

**Issue by 00niko** [browscap/browscap#1313]
Next useragents is UCbrowser, not Android:
> Mozilla/5.0 (Linux; U; Android 5.1; en-US; m2 Build/LMY47D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.8.945 U3/0.8.0 Mobile Safari/534.30
> Mozilla/5.0 (Linux; U; Android 4.4.2; en-US; TZ43 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.5.932 U3/0.8.0 Mobile Safari/534.30
> Mozilla/5.0 (Linux; U; Android 4.3; en-US; Prime S Build/JLS36C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.0.915 U3/0.8.0 Mobile Safari/534.30
> Mozilla/5.0 (Linux; U; Android 6.0; en-US; LG-H422 Build/MRA58K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.0.915 U3/0.8.0 Mobile Safari/534.30

**Comment by jaydiablo** [comment]
These all parse correctly against current master branch (which will be released as version 6022):

[issue-1313.csv.zip](https://github.com/browscap/browscap/files/872744/issue-1313.csv.zip)

I believe this PR fixed them: https://github.com/browscap/browscap/pull/1241
