### ISSUE TITLE
Missing bots

### ISSUE THREAD

**Issue by dczaretsky** [browscap/browscap#1320]
We have been seeing a lot of traffic from these bots that are currently missing:

Crowsnest/0.5 (+http://www.crowsnest.tv/)
datagnionbot (+http://www.datagnion.com/bot.html)
iCoreService (unknown version) CFNetwork/807.2.14 Darwin/16.3.0 (x86_64)
Jetty/9.3.z-SNAPSHOT, SMUrlExpander
longurl-r-package
Mediatoolkitbot (complaints@mediatoolkit.com)
Mozilla/5.0
Mozilla/5.0 (compatible; AdlesseBot/1.0; feedback@adlesse.com) v1490676842.3287
Mozilla/5.0 (compatible; AdlesseBot/1.0; feedback@adlesse.com) v1490715782.0961
Mozilla/5.0 (compatible; AndersPinkBot/1.0; +http://anderspink.com/bot.html)
Mozilla/5.0 (compatible; Faveeo/1.0; +http://www.faveeo.com)
Mozilla/5.0 (compatible; LinkisBot/1.0; bot@linkis.com)
Mozilla/5.0 (compatible; um-LN/1.0; mailto: techinfo@ubermetrics-technologies.com)
Mozilla/5.0 AppEngine-Google; (+http://code.google.com/appengine; appid: e~finscience-1253)
Nuzzel
Ruby, Twurly v1.1 (http://twurly.org)

**Comment by jaydiablo** [comment]
As part of #1344 I have a lot of bots to add.  I'll roll these into that list and make a PR.
