### ISSUE TITLE
New Safari Version + iOS 10 for Mobile Safari Web View

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1323]
Saw this today: https://webkit.org/blog/7477/new-web-features-in-safari-10-1/

Looks like a new Safari version for desktop mac OS (10.1).

I also noticed that the mobile Safari UI Web view is lacking the iOS 10.x versions.

I have a PR nearly ready for this, just wanted an issue number to name the test case.

**Comment by jaydiablo** [comment]
In my search for useragents that detect as Safari but don't have a version number (or don't have a platform version) I found agents like these:

>%e7%99%be%e5%ba%a6HD 5.3.0 rv:5.3.0.0 (iPad; iPhone OS 9.3.2; zh_CN)
com.google.GoogleMobile/23.0.0 iPad/8.0 hw/iPad2_2
com.google.GoogleMobile/23.0.0 iPad/9.3.5 hw/iPad2_1
com.google.GoogleMobile/23.0.0 iPad/9.3.5 hw/iPad2_5
com.google.GoogleMobile/23.0.0 iPhone/10.2.1 hw/iPhone8_1
com.google.GoogleMobile/23.0.0 iPhone/9.2.1 hw/iPhone5_2
QQ%e6%b5%8f%e8%a7%88%e5%99%a8 6.1.1 (iPhone; iPhone OS 7.1.2; zh_CN)
QQ%e6%b5%8f%e8%a7%88%e5%99%a8 6.6.1 (iPhone; iPhone OS 7.1.2; zh_CN)

Which browscap is detecting as "Mobile Safari UIWebView".  This appears to be because of these patterns:

https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/mobile-safari-uiwebview/mobile-safari-uiwebview.json#L82

Should these patterns remain? Or, should patterns be added for these agents?

**Comment by mimmi20** [comment]
We could add a pattern for `com.google.GoogleMobile`, but I dont know which Google App this is. We can ignore the others and remove these generic pattern, I think.

**Comment by jaydiablo** [comment]
There is one UA in the tests that touches those generic patterns:

>Alizee iPod 2005 (Beta; Mac OS X)

It comes from #780.

**Comment by mimmi20** [comment]
Then we should leave the `iPod` pattern and remove these generic `iPhone` pattern.
