### ISSUE TITLE
If the INI file can't be built, useragent tests should abort?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1333]
I'm not sure if this is possible within the way that PHPUnit operates without using something like `die` or `exit` but it would be nice if when the INI build step of the tests fails, that the useragent tests would abort at that point (and output the error message that the INI builder dumps).

There are times where I mess up a JSON file when making a change, kick off tests, switch windows, come back and see that each test is just erroring out.  Usually I then run the `build` command manually to see why the test failed (if the JSON error isn't obvious in my editor).

**Comment by asgrim** [comment]
Can use the `--stop-on-failure --stop-on-error` flags maybe?

**Comment by jaydiablo** [comment]
Can, I typically don't run the tests like that though when working on the patterns, as I like to see all of the tests that fail in a single run, so I can address them all with a single update, rather than running tests, stopping on error, fixing single test, running again (this would slow things down considerably since it takes a while to build the INI file on each run).

I have a PR though that I think addresses this well enough.
