### ISSUE TITLE
bump PHP version to 7.1

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1338]
With BrowscapPHP bumped to PHP 7.1, the builds are failing on travis. To solve this, Browscap should be bumped too.

**Comment by asgrim** [comment]
#1336 (fixing #1335) fixes the failing builds for now, but yes, I agree we should bump to 7.1 minimum :)

**Comment by jaydiablo** [comment]
I believe this was bumped in #1543 no?

**Comment by mimmi20** [comment]
Fixed in PR#1543.
