### ISSUE TITLE
majorver in iOS 10.3.1 useragent not parsed

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#1339]
When using "Mozilla/5.0 (iPad; CPU OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1", which is an iPad Air 2, the majorver is not returned.

The "10_3_1" notation is not recognized yet, where this is the case for "10_2_1" for example.

I guess this is as to be expected, as it's just released (http://www.gottabemobile.com/ios-10-3-update-iphone-ipad/).

**Comment by jaydiablo** [comment]
iOS 10.3 was add in this PR: https://github.com/browscap/browscap/pull/1312

Which just missed the 6022 release.

I just tested that useragent against the `master` branch and it does parse properly:

```
"browser_name_regex": "\/^mozilla\\\/5\\.0 \\(ipad.*cpu os 10_3.* like mac os x.*\\).*applewebkit.*\\(.*khtml.*like.*gecko.*\\).*version\\\/10\\.0.*safari\\\/.*$\/",
    "browser_name_pattern": "mozilla\/5.0 (ipad*cpu os 10_3* like mac os x*)*applewebkit*(*khtml*like*gecko*)*version\/10.0*safari\/*",
    "parent": "Mobile Safari 10.0",
    "comment": "Mobile Safari 10.0",
    "browser": "Safari",
    "browser_type": "Browser",
    "browser_bits": "32",
    "browser_maker": "Apple Inc",
    "browser_modus": "unknown",
    "version": "10.0",
    "majorver": "10",
    "minorver": "0",
    "platform": "iOS",
    "platform_version": "10.3",
    "platform_description": "iPod, iPhone & iPad",
    "platform_bits": "32",
    "platform_maker": "Apple Inc",
```

10.3 should show up properly when 6023 is released.

**Comment by paulrutter** [comment]
Ah sorry, i looked at the open issues but didn't check the already closed ones.
My bad. I'll wait until 6023 is released 👍
