### ISSUE TITLE
Missing user-agents

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1344]
I'm going through our logs for March and pulling out any useragents that parsed as "Default Browser" and trying to decipher the valid ones.

I want to break it out in to a series of tickets/PRs rather than just one huge one, so using this as a meta issue of sorts (though I'll probably make an issue for a lot of the smaller/obscure browsers and attach them to this issue number).

You can assign this to me.

**Comment by WhiteLoti** [comment]
Browscap doesn't seem to detect the linux 64 bit desktop user agent string "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

**Comment by mimmi20** [comment]
@WhiteLoti Did you update your browscap.ini file to the newest version?

**Comment by WhiteLoti** [comment]
Yes I downloaded it about 20 minutes ago and cached it.

**Comment by jaydiablo** [comment]
@WhiteLoti the useragent appears to parse fine for Browscap 6022 (the latest version):

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%3B+rv%3A52.0%29+Gecko%2F20100101+Firefox%2F52.0

Can you confirm that you're using version 6022?
