### ISSUE TITLE
update agent as bot?

### ISSUE THREAD

**Issue by martenkoetsier** [browscap/browscap#1368]
I was recently plagued with a lot of form submission spam by many hosts, all using the same agent, with ua-string: `Mozilla/5.0 (Windows NT 5.1; rv:7.0.1) Gecko/20100101 Firefox/7.0.1`
I have now blocked this agent on the offended site.
Looking up this agent in the current version 6022 reveals nothing special (no crawler, not fake).

Might it be possible that this agent is actually a bot? Or is it a compromised OS/browser (judging from the many ip's from all over the world)? Requests come in on all hours, but more between 14:00 and 22:00 GMT+1.

A few of my sites were visited, although only one was victim (having a simple form on the home page). I have not seen "normal" traffic from this agent. The first request was on April 10, 01:59h GMT+1. The last so far was on April 11, 23:11h GMT+1.

**Comment by mimmi20** [comment]
This UA is a Firefox Browser in version 7.0 running on windows XP. This is not a bot and we cant mark this as one.
If the systems are compromised or if someone is faking the useragent, we cant detect.

**Comment by jaydiablo** [comment]
It's certainly possible that it's a bot, but it's hard to tell from a useragent alone if the bot has spoofed the UA to look real.

The only suspect thing about that UA is the Gecko build date `20100101`.  Firefox 7 was released in 2011:

https://en.wikipedia.org/wiki/History_of_Firefox#Version_7

So you'd expect that Gecko build to be in 2011, not 2010. I've seen a lot of Firefox useragents use that same `20100101` build date, but I don't think it's enough to definitively say it's a bot or spoofed, at least not in a useragent parsing library like browscap.  It may be something you should look at in your own app though.

For the record, other UA parsing libs parse this one the same as browscap does, without any indicator of bot/fake: http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+5.1%3B+rv%3A7.0.1%29+Gecko%2F20100101+Firefox%2F7.0.1

**Comment by jaydiablo** [comment]
Actually, looking at my own useragent on Firefox 52, that `20100101` gecko build number is present, so it seems that Mozilla must've locked that number in the useragent at some point.

>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by mimmi20** [comment]
According to the info on site https://developer.mozilla.org/de/docs/Gecko_user_agent_string_referenz:
> On Desktop, geckotrail is the fixed string "20100101"

**Comment by jaydiablo** [comment]
Yeah, so definitely no way to differentiate on the useragent alone.

**Comment by martenkoetsier** [comment]
Sigh, if everyone would be honest for a change...
Anyway, thanks a lot for the confirmation that this UA is a genuine browser.

> Yeah, so definitely no way to differentiate on the useragent alone.

So I guess it comes down to behavior detection and the like.

> I have now blocked this agent on the offended site.

Above statement was a bit incomplete (for the sake of the question), I just don't handle the form submission on this specific form for this UA and instead give a warning, so that real users are kindly invited to contact us in an alternative way.
