### ISSUE TITLE
Add Reddit App UA

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1369]
This is part of #1344 

We've seen a few instances of a Reddit UA that appears that it could be their iOS app:

>Reddit/Version 2.6.0/Build 200033/iOS Version 10.0.2 (Build 14A456)
Reddit/Version 2.6.0/Build 200033/iOS Version 10.1.1 (Build 14B100)
Reddit/Version 2.6.0/Build 200033/iOS Version 10.2.1 (Build 14D27)

https://itunes.apple.com/us/app/reddit-official-app-all-thats-trending-and-viral/id1064216828?mt=8

However, when I download the Reddit app on my iPhone and look at the UA, I get a generic webview UA:

>Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304

(this was with version 2.7 of the app)

I suppose it's possible that those three useragents were from the 2.6 version of the app, and then in 2.7 (or even in a later build of 2.6) switched to the more generic webview agent. Or possibly it's a sort of pre-fetch request that the app does.

The data in those three UAs seem to match up, for example, there was a 2.6 version of the app: https://www.reddit.com/r/changelog/comments/60idiu/reddit_for_ios_version_26_now_available/

The second build number on that `10.2` iOS version appears to match the build number seen from other iOS 10.2 useragents, like this Firefox iOS one I pulled from my phone before upgrading to iOS 10.3:

>Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) FxiOS/7.0b2330 Mobile/14D27 Safari/602.4.6

I can put a PR together to add a Reddit App that matches those three useragents, just curious what you think is the best approach here.

There is an official Android app as well, but not seeing anything related to that in our logs:

https://play.google.com/store/apps/details?id=com.reddit.frontpage&hl=en

**Comment by mimmi20** [comment]
Some iOS Apps are using a Darwin useragent to download some icons.

**Comment by jaydiablo** [comment]
Yeah, digging around a bit, when an iOS app makes a background HTTP request, the default useragent apparently is some variation of this:

`MyApp/17 CFNetwork/758.0.2 Darwin/15.0.0` (from https://burgers.io/better-user-agent)

But seems like that's totally customizable, as explained in that article.  So perhaps that's the case here, the Reddit iOS app is making a background request for something and they've modified the default Darwin useragent.

Should we add patterns for this?  

If so, should it be categorized as an application?  

Should we just do a generic pattern that captures the iOS version (and ignores the Reddit version)?

**Comment by mimmi20** [comment]
We could add a pattern for the Reddit app and caterize it as application.
