### ISSUE TITLE
Firefox platform versions

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1381]
I was looking for useragents in our logs that had a browser name, but were lacking a browser version. The browser that this seemed to happen to the most was Firefox, so I extracted just Firefox useragents that didn't have a version to dig around a bit to see if they should have a version (and planning to make necessary changes so they get the proper version).

Which brings me to my question.  This has sort of come up before when dealing with Samsung browser (and whether or not to add versions of the browser that apparently haven't been released), and with Safari and OSX versions.

I was curious which versions of Firefox supported which versions of different platforms. It seems that some of this research has been done already, as I noticed that the platforms change a bit as you progress through Firefox versions, but it doesn't seem to be quite exact.  For example, Firefox 2.0 is the last version of Firefox that will run on Windows 98 (officially, more on this in a bit), here's the ticket where Windows 9x support was removed: https://bugzilla.mozilla.org/show_bug.cgi?id=330276

However, Browscap currently has Windows 98 as a platform for Firefox up to, and including version 3.8. There are 2 tests in the test suite which test for this (which I added as part of #1360, before doing any of this research).

Above I said "officially", and the reason for that is that there are projects out there that patch older versions of windows so that they'll be able to run newer versions of software, like browsers. This project is one such project and it allows Windows 98 users to run newer Firefox versions: http://kernelex.sourceforge.net/wiki/Mozilla_Firefox (though it doesn't seem to work reliably for all versions of Firefox, that wiki page claims that Firefox 3.6 runs pretty well, Firefox 10 should run pretty well, but anything else suffers from bugs/glitches, or may not run at all).

Most useragent parsers don't seem to care too much about this, since they're just looking for certain patterns in the string to determine which OS/version and Browser/version the agent is. Few look at all of the properties together when deciding how to parse.  For example, here's a string I crafted that has Firefox 42 running on Windows 98, which probably isn't possible even with the very best kernel extensions. :)

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows%3B+U%3B+Win98%3B+bg%3B+rv%3A1.9.0.19%29+Gecko%2F20090624+Firefox%2F42.0

So my question is, how should Browscap behave in these situations?  Aside from the parsing aspect, removing some platforms from versions of the browser that aren't supported would reduce the number of patterns in the Browscap file, which I think is a good thing.

As for the parsing, most likely the generic patterns would end up picking up agents like the one above (it doesn't happen in this case, because the Generic file for Firefox doesn't have "Win98" in it, but that should probably be added), so they would still be parsed as Firefox on whichever platform, but they wouldn't have a Firefox version number.

Or, we could try to treat these as invalid patterns (like how browscap 6022 treats that fake pattern above), but that may be more difficult because that generic pattern file wouldn't be able to pick up these agents (which may mean that most patterns would have to be removed from it, or we'd at least have to be selective about which platforms show up in that file (like no Win98 for example, since we know that only certain version ranges of Firefox support Win98)).

If we choose not to allow these platforms in version files where they shouldn't be, what should be done with the Kernel extension projects?

IMO, I think the best approach may be to drop the platforms from the files for the versions that Firefox officially stopped supporting that platform, and make sure the generic file has all of the platforms in it so that the UAs still parse as Firefox, but will be version-less. (this is the approach I've been taking with recent changes I've been making).

Thoughts?  What's the official stance here?

**Comment by jaydiablo** [comment]
Oh, and if going the route of removing the platforms so that the agent parses as "Firefox" but doesn't have a version (the generic pattern), should we start a file that contains tests for this (that explicitly test that the version isn't present and generic pattern is used) similar to the "invalids" file that has comments above each test case?

That way people like me won't come in and start adding platforms that shouldn't be there. ;)

**Comment by mimmi20** [comment]
We should not care about custom build versions of firefox, only the official ones. This is already enough work to do.

**Comment by mimmi20** [comment]
We could handle these versions in the default section as fallback to detect them as firefox, or use the gecko version to map them.

**Comment by jaydiablo** [comment]
Another question with some of these patterns, and if they should remain or not.

As part of #900, these two patterns were added:

https://github.com/browscap/browscap/commit/5582240307fd18fd0ce3666cbf561f68a87ca72a#diff-0e9ef780f6891d4a92387ca4421c50ccR104

(that one and the one below it)

Should these remain as legit Firefox useragents?  Would Firefox ever legitimately use `Mozilla/3.0` or `Mozilla/6.0`?

Here's the UA in the tests for the `Mozilla/3.0` pattern:

>mozilla/3.0 (Windows NT 6.1; rv:2.0.1) Gecko/20100101 Firefox/5.0.1

We see that exact user agent in our logs as well, but only for that one platform (Windows 7). I suspect that the agent is a fake used by some sort of bot (just based on traffic patterns we see for that UA).

For the `Mozilla/6.0` pattern, here's the UA in the tests:

>Mozilla/6.0 (Macintosh; I; Intel Mac OS X 11_7_9; de-LI; rv:1.9b4) Gecko/2012010317 Firefox/10.0a4

We've seen that one once (this year), and the request it made doesn't seem like something a legitimate user would have done (RSS feed URL basically, out of the blue).

We have seen other `Mozilla/6.0` Firefox URLs, but not very many. Some on Windows, some on OSX.

**Comment by mimmi20** [comment]
I think, we can remove these pattern. The Gecko and Firefox token do not match. I dont remember why I added these tests.

**Comment by jaydiablo** [comment]
Bit of an interesting situation here. As part of this issue I'm trying to add useragents to the tests that cover as much of the patterns in the Firefox files as I can.  I was just working through one of the more recent Firefox version files and noticed that the pattern I'm expecting to see get covered by all of these different Windows versions, wasn't getting covered at all.

Here's a screenshot of the local coverage report after running all of these tests for the pattern I was expecting to be covered:

<img width="798" alt="screen shot 2017-04-17 at 10 46 31 pm" src="https://cloud.githubusercontent.com/assets/136907/25114953/d515013e-23bf-11e7-8d45-9dad28138fbc.png">

I'm positive that I added tests that are being parsed properly in this file.  Turns out that the agents are being picked up by this pattern instead:

<img width="755" alt="screen shot 2017-04-17 at 10 46 56 pm" src="https://cloud.githubusercontent.com/assets/136907/25114969/f5a349f6-23bf-11e7-9fab-ef0d5146fb39.png">

I assume that the pattern that uses the `rv:#MAJORVER#.#MINORVER#*` syntax ends up just being a bit longer than the other one, which is why it's always selected by the parser.

As things are now, the earlier pattern that doesn't get covered at all is pretty much redundant, unless the `rv` version doesn't match the file (or any other firefox files), then it may check the other pattern.  This probably shouldn't happen with legit Firefox versions, since the `rv` and `Firefox/` versions should match.

This `rv` pattern seems to have been added to catch agents like this one:

>Mozilla/5.0 (Windows NT 10.0; WOW64; rv:41.0) Gecko/20100101 Firefox/AA5D

Where the Firefox version is a seemingly random mixture of letters and numbers (this one comes from `issue-814`).  We've seen a lot of this style pattern in our logs, but I always discard them as fakes since they don't have a proper Firefox version.  Should these patterns that are trying to detect on the `rv` version alone remain?  If so, should the other pattern be removed?  It seems pretty redundant at this point.

Should these agents that have a random alpha-numeric Firefox version be considered valid?

Most other parsers do see it as being Firefox, but don't have a version (or use that alpha-numeric string as the version, which is bad, IMO): http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+WOW64%3B+rv%3A41.0%29+Gecko%2F20100101+Firefox%2FAA5D

UAParser is the only one that outright rejects the UA, and Browscap is the only one that captures the `rv` version as the Firefox version.

**Comment by asgrim** [comment]
Do we have any evidence `AA5D` isn't legitimate? Could it be a build number perhaps? I guess the best way to investigate is to check how Firefox generates the UA in the source code. `rv:` could be an alternative way to denote the true version perhaps. Not trying to be awkward, just trying to separate right from wrong.

**Comment by jaydiablo** [comment]
Fair question, here's a list of just XP (NT 5.1) useragents that have that style of Firefox version that I pulled from our logs when I started looking into this:

>Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/FE61
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/FDC8
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/FBC6
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/FA4C
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/F466
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/F321
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/ED42
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/EC93
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/EBC1
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/E7D7
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/E6B6
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/DFFA
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/DAE1
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/D99F
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/D864
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/D768
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/D31D
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/CF13
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/CACC
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/CA6A
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/C676
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/C4C9
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/BCC7
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/BB0D
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/B6FF
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/B68F
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/B40B
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/B3B6
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/B350
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/B33F
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/AF0C
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A9C9
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A946
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A72E
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A70E
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A65B
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A497
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/A0C5
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/9E20
Mozilla/5.0 (Windows NT 5.1; rv:39.0) Gecko/20100101 Firefox/9DE3

That's just a small sample, this particular list is 1,700+ unique useragents.

There doesn't seem to be any correlation between that random-looking string on the end and the platform, rv version or anything else present in the string.

We see this format across all platforms (mac/windows/linux/bsd) and all versions (from 2.0 to 52.0).

Mozilla's reference for their Useragent format mentions that the gecko version (the value after `rv:`)  and Firefox version (value after `Firefox/`) should be the same in newer versions of Firefox:

>rv:geckoversion indicates the release version of Gecko (such as "17.0"). In recent browsers, geckoversion is the same as firefoxversion.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox

The alphanumeric string seems hexadecimal in nature (letters never exceed the letter F). Most of the time they are 4 characters long but I'm seeing instances where they are only 3 characters, and also 6 (but not 5).

The source of this traffic spans a lot of different IPs and ISPs/hosts so it's difficult to pin it on a single bot source or something like that, but the traffic does look bot-like.

**Comment by jaydiablo** [comment]
As for Firefox's source code, I did find this file, which seems to do a lot of the Useragent building for HTTP requests, and on this line it does appear to assign the version number to both the `rv:` piece and the `Firefox/` piece:

https://github.com/mozilla/gecko-dev/blob/7a670cdd01c320e0fe6c8908ae17090be5cc1a9d/netwerk/protocol/http/nsHttpHandler.cpp#L321

Appears to assemble the useragent string in this function: https://github.com/mozilla/gecko-dev/blob/7a670cdd01c320e0fe6c8908ae17090be5cc1a9d/netwerk/protocol/http/nsHttpHandler.cpp#L679

**Comment by jaydiablo** [comment]
And as for that `MOZILLA_UAVERSION` variable, I think it comes from this build script:

https://github.com/mozilla/gecko-dev/blob/ab87252d1af2f9b1e1dc4e318bf7a7d10243a102/old-configure.in#L778

Though it's named "old" so perhaps that has changed.

That python script does this:

https://github.com/mozilla/gecko-dev/blob/master/python/mozbuild/mozbuild/milestone.py#L54

Which should look for the first line that begins with a number in this file:

https://github.com/mozilla/gecko-dev/blob/master/config/milestone.txt

Which is `55.0a1` right now, and that's what I get when I try to download the Nightly:

<img width="347" alt="screen shot 2017-04-18 at 12 53 25 am" src="https://cloud.githubusercontent.com/assets/136907/25117983/84412104-23d1-11e7-84ab-10aaadd4129c.png">

I certainly can't claim to know the Firefox source at all, but it really seems like official builds should not be sending Firefox versions like that.

**Comment by mimmi20** [comment]
The `rv:` token is connected to the gecko version, the `Firefox` token should have the browser version. As I understand Mozillas version changes started with Firefox 5 both versions should be the same.

The second pattern was added as fallback for the first to capture these useragents with illegal firefox versions.

Can we add the `rv:` token with version to the first pattern to make it longer?

**Comment by mimmi20** [comment]
@jaydiablo Did you see the illegal firefox versions in other windows versions than XP or with other OS?

**Comment by jaydiablo** [comment]
@mimmi20 I could make the other pattern longer, but I'm concerned it will then make it harder to match other Gecko/Firefox based browsers, like Waterfox (they may have to be made longer too).

We do see these alphanumeric versions for other windows platforms, and other platforms entirely, here's a sample:

>Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/FA52
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/950E
Mozilla/5.0 (X11; U; SunOS i86pc; ru; rv:1.8.1.5) Gecko/20100513 Firefox/305BD
Mozilla/5.0 (X11; U; FreeBSD i386; ru; rv:1.8.1.12) Gecko/20090706 Firefox/5BE3CB
Mozilla/5.0 (Windows; U; Windows NT 6.1; de; rv:1.9.1.3) Gecko/20090824 Firefox/A93D7
Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/6DB9
Mozilla/5.0 (Windows NT 6.4; WOW64; rv:36.0) Gecko/20100101 Firefox/4651
Mozilla/5.0 (Windows NT 6.3; rv:39.0) Gecko/20100101 Firefox/3CE2
Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/3BC5
Mozilla/5.0 (Windows NT 6.1; rv:51.0) Gecko/20100101 Firefox/8921
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:12.0) Gecko/20100101 Firefox/C0F6
Mozilla/5.0 (Android; Tablet; rv:34.0) Gecko/34.0 Firefox/3A9B
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:48.0) Gecko/20100101 Firefox/12D6
Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10.4; tr; rv:1.8.0.5) Gecko/20090407 Firefox/3CE21

**Comment by jaydiablo** [comment]
FWIW, we see this happen to Chrome too, but on the Safari version:

>Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/4E423F
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/917137
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/0162FC
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/2CA94B
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/A5E656
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/C4F56B
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/607F93	
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/449B1A	
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/6C556F
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/820A15	
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/C2480F
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/51EDC8
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/AAB330

**Comment by mimmi20** [comment]
Then we should remove this pattern.

**Comment by jaydiablo** [comment]
I think it's probably fine to have a Generic pattern pick these up and detect as Firefox but with an unknown version number.

We're doing some more analysis on these agents, and it does seem suspicious, almost like a botnet behind a proxy.  They occur almost exclusively on non-HTTPS traffic and we've seen a number of them switch to the "valid" version (with a proper, matching Firefox version) when the same "user" makes an HTTPS request.
