### ISSUE TITLE
Missing user agent for A510F

### ISSUE THREAD

**Issue by Giorgi** [browscap/browscap#1392]
Samsung A5 2016 (and probably A3 2016 and A7 too) is missing from ini file.

Version: 6022
Parsing: manually, I tested my user agent with http://browscap.org/ua-lookup

Here is the full user agent:

> Mozilla/5.0 (Linux; Android 6.0.1; SM-A510F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36

Device details: [A510F](http://www.gsmarena.com/samsung_galaxy_a5_(2016)-7789.php)

**Comment by jaydiablo** [comment]
Thanks @Giorgi, this update should be in the next release.
