### ISSUE TITLE
Opera Mobile version segmentation

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1396]
I'm condensing Opera Mobile devices, and I noticed that versions 14+ are split up among 5 different files:

* opera-mobile-14-26.json
* opera-mobile-27-31.json
* opera-mobile-32-36.json
* opera-mobile-37-41.json
* opera-mobile-42-on.json

I understand that this is typically done to make sure only the most recent versions appear in the Lite files, or when a browser changes engines or other properties from one version to the next. Or even when support for certain platforms is dropped from one version to the next.

However, in this case the only difference between the 5 files is the version numbers, the `sortIndex` and one pattern that gets removed after version 26:

>Mozilla/5.0 (#PLATFORM#genm14 Build/*) applewebkit* (*khtml*like*gecko*)*Chrome/*Safari/* OPR/#MAJORVER#.*

(this is excluding the Samsung devices I added in #1395 which only got added to the more recent files)

Is there any particular reason these are broken up this way?

I'm looking to add some coverage for these files, but it ends up being a lot of duplicate useragents (that only differ by the Opera version) since the same patterns/devices exist in all 5 files.

I've also found some useragents that are getting caught by Chrome that I wanted to add the devices to these files, but it requires copying/pasting the additions across several files.

Can these ones be combined to a single `14-on` file since nothing really changes between them?

**Comment by mimmi20** [comment]
The files are split this way based on the underlying chrome version (Opera 42  is based on Chrome 55). The only reason to create these 5-version-blocks was to kick them out of the lite file easier.

**Comment by mimmi20** [comment]
If we merge the Opera files together, we could do the same with Chrome. I do not know if there is any list, which Chrome/Opera version supports a Andoid version to split the files based on the supported andoid versions.

**Comment by jaydiablo** [comment]
I see, I'll dig around some.

First bit of info is that Google Chrome on Android doesn't support anything lower than Android 4.0:

https://productforums.google.com/forum/#!topic/chrome/9IqkWN3vGQY

In that same thread though, there are people mentioning that they were able to get Opera Mobile to work on their 2.x device.

Also, there probably shouldn't be versions 19-24 of Chrome (unless they're pre-releases), as the version was bumped from 18 (the first release for Android) to 25 to get the version numbers in sync with the desktop version.

https://en.wikipedia.org/wiki/Google_Chrome_version_history (Notice that 19-24 don't have an Android release date), also this on version 25:

>Android version (update from 18):

However, I do see some tests hitting the 19-24 file (for Android): https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/chrome/chrome-19-24.json#L722

Here are the UAs in the tests:

>Mozilla/5.0 (Linux; Android 4.4.2; SM-P600 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; HTC One_M8 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.2; SCH-I545 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; Nexus 5 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Mobile Safari/537.36

All are version `19.77.34.5`. Same in this list here: https://www.handsetdetection.com/properties/browsers/Android%20Chrome/19.0

I searched our logs for that version range of Chrome on Android and found **two** hits from two different useragents (just searched this year):

>Mozilla/5.0 (Linux; Android 4.1.1; Nexus S Build/KTU84Q) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/23.0.351.216 Mobile Safari/535.19	
Mozilla/5.0 (Linux; Android 4.4.4; E2003 Build/25.0.A.2.31) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/19.77.34.5 Mobile Safari/537.36	

Again that `19.77.34.5` version and then a `23.0.351.216` version.

I also searched our logs for Chrome on Android with an Android version less than 4.0 and only a handful of hits came up for this year, across just 5 useragents:

>Mozilla/5.0 (Linux; U;Android 2.0; en-us; pandigital9hr) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/535.19
Mozilla/5.0 (Linux; U;Android 2.3; en-us; MID Build/GRH55) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/535.19

Nothing too interesting about these two, I tried looking for that `pandigital9hr` device, but not a lot comes up, just wanted to confirm what Android versions it runs.  The other one is a generic "Mobile Internet Device" MID device, so no help there.

>Mozilla/5.0 (Linux; U;Android 4.0.4; en-us; HTC Desire Build/MIUIAndroid 1.5.13) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/535.19

This one is actually a mis-detection since it should be seen as Android 4.0, not 1.5.

>Mozilla/5.0 (Linux; U;Android 2.0; en-us; Droid Build/ESD20) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/535.19 FirePHP/0.4

This one is odd due to the `FirePHP/0.4` bit on the end there. The Motorola Droid is an Android 2.0 device, so that matches up, but I wouldn't expect any of the FirePHP extensions that you can install in desktop chrome to be available for Android, but maybe it's possible. I noticed there's a 0.4 version of this one: https://chrome.google.com/webstore/detail/firephp-chrome/aleccmdjeoaihoekgpohjfombpekdghf?hl=en-US

>Mozilla/5.0 (Linux; U;Android 2.3; xx-xx; SonyEricssonR800i Build/3.0.A.0.326) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/535.19

The SonyEricsson R800i appears to be an Android 2.3 device, so that matches up (https://www.handsetdetection.com/properties/devices/SonyEricsson/R800I).  Nothing else of interest here.

I would say it's probably safe to remove Android < 4.0 from the Google Chrome files. These useragents may be fakes, or someone using a modified build.

As for Chrome versions 19-24 on Android, I think it's probably safe to remove those as well (and either let the generic fallback catch them without a version, or maybe add version 19 as a beta perhaps).

I can't find much with regards to Opera Mobile on Android though. It sounds like it will install on older than 4.0 Android (but may be lacking some features, like Flash).  I'd vote to merge the Opera Mobile 14+ files into a single file, unless we want to add it back to the Lite file (as far as I can tell, Opera Mobile isn't in the lite file currently), then maybe keep the 42+ file separate (and set the Lite property to `true`) and merge 14-41 into a single file.

**Comment by mimmi20** [comment]
Shouldn't the mobile chromes split from the desktop chromes into separate files then? This would make version handling easier.

**Comment by jaydiablo** [comment]
For Chrome, possibly, those files may be split because of addition/removal of OSX or Windows versions as well, I haven't looked at them under that context much yet.

But yes, if adding a version 19 (for android), to mark as a beta (if that's the direction we want to go), but removing versions 20, 21, 22, 23, 24 for Android, it may be nicer to have android separated from desktop/iOS, otherwise there would have to be an 18 file, 19, 20-24, 25+, etc...

**Comment by jaydiablo** [comment]
I was also curious if we have seen pre-18 versions of Chrome on Android much.  We have, but the frequency is very low and only spans these useragents:

>Mozilla/5.0 (Linux; Android 4.05; Galaxy Nexus Build/IMM76B) AppleWebKit/535.25 (KHTML, like Gecko) Chrome/17.0.1025.133 Mobile Safari/536.19
>TBDG773 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24
>TBD1083 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24	
>TBDC1093 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24 	
>TBDB863 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24	
>Mozilla/5.0 (Linux; Android 4.0.3; ThL W2 Build/IMM76I) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/16.0.1033.171 Safari/535.19 	
>Mozilla/5.0 (Linux; Android 4.2.2; GT-P3110 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.62 Safari/534.30
>Mozilla/5.0 (Linux; Android 4.3; C5303 Build/12.1.A.1.205) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.58 Mobile Safari/534.30

I can't find any info about Chrome Beta for Android version numbering.  Everything I see about Android Chrome is that it was released starting at version `18.0.1025` when it came out of Beta on 2012-06-27.

**Comment by jaydiablo** [comment]
Here's Opera's official stance on which versions of Android it supports, from their FAQ (http://www.operasoftware.com/press/faq)

<img width="722" alt="screen shot 2017-04-24 at 2 04 56 pm" src="https://cloud.githubusercontent.com/assets/136907/25356386/31a29088-28f7-11e7-9160-2e57e0a170c5.png">

So since moving to use Chromium instead of Presto (which was version 14) it should only support 4.0 and up (like Chrome).

There are only two tests in the Browscap suite that hit < 4.0 android versions on Opera Mobile 14+:

>Mozilla/5.0 (Linux; Android 2.3.4; HTC Ruby Build/GRJ22) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.58 Mobile Safari/537.31 OPR/14.0.1074.57768
>Mozilla/5.0 (Linux; Android 2.3.6; Liquid MT Build/GRK39F) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.58 Mobile Safari/537.31 OPR/14.0.1074.57768
