### ISSUE TITLE
Yandex Browser on Iphone 

### ISSUE THREAD

**Issue by anton-okolelov** [browscap/browscap#1404]
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 YaBrowser/17.4.1.576.10 Mobile/14E304 Safari/602.1`

browscap says it's Mobile Safari, but it's Mobile Yandex Browser

**Comment by jaydiablo** [comment]
It seems that the `Version/10.0` piece of the UA was added in more recent versions of iOS (I think 10.3+).

I have a PR coming to address this.
