### ISSUE TITLE
Samsung Device Condensing + Coverage, CrossApp?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1408]
I was looking to wrap up the remaining samsung browser files and noticed some useragents in our logs that have `SamsungBrowser` in them but parsed as `Android Webview`:

>Mozilla/5.0 (Linux; Android 6.0.1; SM-G930R4 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 Mobile Safari/537.36 SamsungBrowser/CrossApp/0.1.88 

Notice that "CrossApp" string where the version should be.

This appears to be a cross application webview of sorts that Samsung released with Android 6.0 devices:

https://www.sammobile.com/2016/02/17/android-6-0-for-galaxy-devices-brings-new-samsung-browser-cross-app-and-more/

Thoughts on naming this?  Should it be "Samsung CrossApp"?

**Comment by mimmi20** [comment]
This looks fine to me.
