### ISSUE TITLE
Android Webview/Browser cleanup

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1413]
As part of this April 2017 update I'm working on, I tend to run into cases where the Android Webview 4.0 file's patterns are just a tad too long so they end up capturing some other patterns that they shouldn't.

I've taken some time to combine some of the patterns into a shorter pattern that works for most of the variations in the file. Coverage isn't great on this file, so I decided to grab some useragents from our logs to cover as many of the devices/patterns as I can before making drastic changes.

This revealed a couple of issues that I wanted to bring up before doing anything too drastic. ;)

1) I don't believe that Android < 4.0 will have webview agents with "Chrome" in them. This article mentions that Android 4.4 added the "Chrome" syntax to the webview useragents: https://developer.chrome.com/multidevice/user-agent#webview_user_agent  However, I have found agents in our logs for Android 4.0 -> 4.3.  That said, I **have not** found **any** useragents that parse as "Android Webview" on Android less than 4.0 in our logs. I suggest that any Android platforms less than 4.0 be removed from this file (I think most of it was copied over from earlier versions of the webview, or even from the Android Browser files).  There are no tests in the Browscap Suite that cover Android platforms less than 4.0 (https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/android-webview/android-webview-4-0.json) It's hard to tell from that coverage report since it doesn't highlight which platforms are covered, but I have removed all of the < 4.0 platforms in my local copy and the tests pass without modifications.

2) I can't find any useragents that parse as Android Webview version > 4.0 (this file: https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/android-webview/android-webview-4-1-on.json). Based on that Google Developers article linked to above, I don't think that version number will change (will always be 4.0, even in newer versions of android).  I suggest we remove this file (which will reduce the browscap file sizes quite a bit since there are a lot of platform/devices in this file multiplied by 5 different versions). No tests in the browscap suite hit this file.

**Comment by mimmi20** [comment]
The Android was added as a copy of the Android Browser

**Comment by jaydiablo** [comment]
Actually, to that second point, I did find a few useragents with Android Webview version > 4.0.

Mostly 4.2, a few others:

>Mozilla/5.0 (Linux; U; Android 4.4; en-us; LGL34C/V100 Build/KRT16S.L34CV10c) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; LG-D800/D80020y Build/KOT49I.D80020y) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; hr-hr; LG-D802 Build/KOT49I.D80220b) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; ko-kr; LG-F320L Build/KOT49I.F320L21y) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; LG-D415 Build/KOT49I.D41509j) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; fr-fr; LG-F320K/21w Build/KOT49I.F320K21w) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; en-za; LG-F320S Build/KOT49I.F320S22h) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; tr-tr; LG-D802/D80220a Build/KOT49I.D80220a) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.2 Chrome/30.0.1599.103 Mobile Safari/537.36

>Mozilla/5.0 (Linux; Android 4.4.2; itel it1407 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.4 Chrome/30.0.0.0 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.4.2; pl-pl; Lenovo TAB S8-50L Build/BMAIN) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.4.2 Chrome/30.0.0.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; en-gb; Lenovo TAB S8-50F Build/BMAIN) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.4.2 Chrome/30.0.0.0 Mobile Safari/534.30

>Mozilla/5.0 (Linux; Android 5.0; Micromax P480 Build/KOT49H)  AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 Chrome/30.0.0.0 Mobile Safari/537.36

According to that Google Developers article, this one should have the `wv` piece after the build since it's on Android 5.0.

>Mozilla/5.0 (Linux; U; Android 2.3; ar-il; HTC Build/5W7DLI5V) AppleWebKit/562.87 (KHTML, like Gecko) Version/9.7 Chrome/55.0.2883.87 Mobile Safari/562.87

That last one there seems like it's been spoofed (Version 9.7 on Android 2.3 and just "HTC" as the device identifier).

Extremely low volume here compared to Webview 4.0.
