### ISSUE TITLE
Unnecessary iOS patterns

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1417]
I started doing this in some recent updates, like in this file: https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/yabrowser/yabrowser-15-on.json#L331

But I've noticed that Browscap has iOS_A and iOS_C patterns for all three main Apple devices (iPod, iPad, iPhone).

Generally, iPhone and iPod use the iOS_A pattern (`CPU Iphone OS`) and iPad uses the iOS_C pattern (`CPU OS`).  I was curious if the iOS_C patterns could be removed for iPod/iPhone and the iOS_A patterns removed for iPad in all iOS browsers/apps with a `Mozilla/` pattern.

I dumped all useragents from our logs that either parse as "iOS" or contain "iPod/iPhone/iPad" and ran them through a version of browscap with the patterns separated as I've described vs. current master.

There are a few exceptions to the "iOS_A for iPhone/iPod, iOS_C for iPad" rule but they're pretty rare.

The 1password browser appears to always use the `iOS_C` pattern, even for iPhone (I've confirmed this with my own phone).

We do see some Mobile Safari agents that mix up the iOS pattern with iPhone/iPad, but the frequency of these is very low. I suspect that they're spoofed but that's always hard to prove.

My main goal with removing these is to reduce the number of patterns in the browscap files, which has the potential to speed up parsing, as having A and C patterns for all three devices in all browser/app versions can increase the pattern count quite a bit where it's not necessary.

I'm planning to add a lot of tests to cover the various iOS patterns in browscap that aren't covered already to confirm that mixing these patterns isn't generally necessary.

Any strong objections to this? I'll have a PR shortly that I've been testing pretty extensively, benchmarks are looking good at this point, and "accuracy" looks good except for some very rare exceptions. I'll discuss more in the PR.

**Comment by mimmi20** [comment]
This will help to clear up some pattern, so I have nothing against this.
