### ISSUE TITLE
Remove deprecated properties from tests?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1433]
I noticed that the list of deprecated properties defined in the Wiki (https://github.com/browscap/browscap/wiki/Resource%3A-User-Agents-Database#deprecated-properties) are still tested for.

As the test suite grows, it may be nice to not assert on these properties anymore, which could see some performance benefits. 

Here's a full run against a branch I'm working on without any modifications to which properties are asserted.

```
Time: 2.77 minutes, Memory: 467.63MB

OK (26652 tests, 1336853 assertions)
```

Here's the same test suite, but with a small bit of test code added to the test runner to ignore that list of deprecated properties (in each file version's run):

```php
$oldProps = ['AolVersion' => 1, 'Crawler' => 1, 'isMobileDevice' => 1, 'isTablet' => 1, 'Win64' => 1, 'Win32' => 1, 'Win16' => 1];

if (isset($oldProps[$propName])) {
    continue;
}
```

```
Time: 2.57 minutes, Memory: 467.63MB

OK (26652 tests, 1125377 assertions)
```

Not an astronomical reduction in execution time, I'll admit (it may reduce a tad more if the properties are removed from the fixtures entirely), perhaps more importantly though, it would reduce some of the maintenance when building/modifying the test fixtures.

Thoughts?

**Comment by mimmi20** [comment]
These properties are defined in the sources too. All of these properties (expect AolVersion) can be generated from other properties (e.g. Crawler from Browser_Type, isMobileDevice/isTablet from Device_Type).
As long the properties are defined in the sources and not generated, we should test them.

**Comment by jaydiablo** [comment]
Is there a plan/timeline to start removing them from the sources?

Should the ones that can be generated be removed first (and code be added that generates them)?

**Comment by mimmi20** [comment]
There is no timeline yet.

**Comment by mimmi20** [comment]
@jaydiablo I would like to extract browser related properties (e.g. `Browser`, `Browser_Maker`, `Browser_Type`, `Frames`, ...) from the useragents into a separate file in the first step. Do you have new Browsers to add? I would wait until these are merged.

**Comment by mimmi20** [comment]
Getting this change working to build browscap files would need some days.

**Comment by jaydiablo** [comment]
I have been running into a fair amount of new browsers as I dig through some useragents for #1448.

I can take a break though if you need.

I don't fully understand what you mean by extracting the browser related properties into a separate file.

Do you mean that the browscap.ini file wouldn't contain this information, but would need to be looked up elsewhere?

**Comment by mimmi20** [comment]
No. Like the platforms or the engines, they are stored in a separate file within the sources. I would like to move these information for browsers into a file like ` browsers.json`. Changing this strcture and adding new browsers at the same time would cause a lot of merge conflicts.

**Comment by jaydiablo** [comment]
I see, that could actually be helpful with an issue that I was going to create a ticket for.

For #1473 I wanted to have most of those properties (Frames/IFrames/Cookies/etc...) be equivalent to the Browser that's being used by the bot, but didn't want to have to re-define them in each child.

Initially I thought they should be attached to the Rendering Engine (perhaps Frames and IFrames should be), but most of the others aren't really layout related.

In theory, with your changes, I could define a `"browser": "Chrome"` but then override the `Browser` property?

**Comment by mimmi20** [comment]
I would implement it that way, that you can define a new `browser` property to a child. This would make it easier if not just the browser name changes, but also the browser maker or the browser type.
