### ISSUE TITLE
Chrome clean-up + coverage

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1448]
The more recent versions of Chrome have very little test coverage, and I assume this is mostly because they've been copied from earlier versions.

I noticed that there are some odd, almost duplicate patterns in these files, like these two in `chrome-55-on.json`:

https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/chrome/chrome-55-on.json#L849
https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/chrome/chrome-55-on.json#L859

Then there's also this one that doesn't have "Chrome" in it at all:

https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/chrome/chrome-55-on.json#L835

And all of these without "Safari":

https://codecov.io/gh/browscap/browscap/src/master/resources/user-agents/browsers/chrome/chrome-55-on.json#L1025

I was hoping to clear out some of these patterns, so looked for Chrome 55+ UAs in our logs, and ran them through the script I've been using to generate tests for uncovered patterns.

After processing 20,000+ UAs (Just Chrome 55+), these patterns remained uncovered.  The only ones that showed any coverage were a couple of the "Safari-less" patterns in the Desktop group and this was because the UAs were truncated (some had "Saf" at the end, or just "S"). An equivalent, full length UA was found in the list when I searched for the partial.

I'd like to remove many of these patterns, starting with Chrome 55+, and I would like to add tests to cover these files, but wanted to bring that up, as it has the potential to add a lot of tests to the suite (I think for Chrome 55+ I have about 400 valid UAs that would get added as tests).

Thoughts?

**Comment by jaydiablo** [comment]
A couple of things I'm planning to do for this.

1) Separate the Android/iOS/Desktop platforms of Chrome into different files. I think this makes it easier to split the files at various breakpoints that are specific to the platform, and requires less copying of Android devices (There would only be a couple of splits in the android files when going this route, 16 (beta), 18 (version is bumped from 18 to 25), 25 - 27 (changes to Blink rendering engine at 28), 28 - 42 (Android 4.0 is dropped at 43), 43-on).  It's less important to split iOS and Desktop, since there isn't so many devices to copy from file to file, but I think it might make it more clear. I haven't fully researched which versions of iOS are dropped from support and when yet though, so I don't know what the splits would look like, other than the first iOS version was Chrome 19.

2) Remove old/unreleased versions of Chrome for Android.  Chrome 18 was the first Android release (stable).  There was no 19-24 version (officially) because they bumped the version number from 18 to 25 to get in-sync with the desktop versions.  There was a Beta release previous to 18, which was 16, which I'll keep, but anything else I'm planning to remove (11, 12, 13, 14, 15, 17, 19, 20, 21, 22, 23, 24).  The only "maybe" in there is a specific version of Chrome 19 (`19.77.34.5`) which apparently belongs to "Chrome Content Shell". Not sure if it's worth adding a pattern just for that or not.

**Comment by mimmi20** [comment]
Its nothing to complain about removing unreleased versions. I would not add this specific version of Chrome.

Additionally to that, I would remove some more versions from the lite (keep the last 10 versions) and the standard (keep the last 20 versions) file.

**Comment by jaydiablo** [comment]
Another thing that I'm planning to do after analyzing a lot of UAs and digging through Chrome release history a bit.

I think that the "#MINORVER#' token should be added to the Chrome patterns so that `.0` is added to the version match. From what I can tell, Chrome doesn't ever release with a minor version other than 0 (this has only happened once, and it was on version 4.1). They don't even bump that minor version in the dev/beta channel updates.

I noticed that the Comodo Dragon browser has some patterns for "as chrome" that do have these minor versions other than 0 defined (and are a chrome pattern).  I did download the Dragon browser to try and test this, but couldn't find a setting to enable that behavior.

The generic patterns will still catch these versions of course (unless the Comodo Dragon patterns have the exact version defined).  I'm not planning to add these versions that I'm seeing to the Comodo versions list (since I can't replicate that behavior in that browser).  I could collect them all though for further analysis if it seems worth it. At this point I'm assuming they're spoofed.

**Comment by jaydiablo** [comment]
I have a PR that's just about ready to tackle a lot of what's mentioned here.  I did decide to end up splitting the chrome files into three different sets of files, one for Desktop, Android and iOS.  This makes splitting the files at various version breakpoints a bit easier, and reduces the number of splits overall, which reduces the number of tests needed for coverage, and eliminates a lot of the android device copying.

Here are the breakpoints I've come up with based on research I've done.

## Desktop

These splits mostly come from google's release blog (https://chromereleases.googleblog.com)

* **0.2 - 0.4**: Beta releases on Windows
* **1.0 - 3.0**: Stable releases for Windows
* **4.0**: Stable release for Windows, Beta releases for Linux and Mac
* **4.1**: And unusual non-*.0 release for Windows (I've confirmed this in the chrome release blog)
* **5.0**: First stable release of Linux and Mac
* **6.0 - 9.0**: 5.0 could probably be merged into this, but there were a few differences, like the addition of a couple of Ubuntu patterns.
* **10.0**: I didn't modify this split, could probably be merged with the 6-9 file, the ubuntu patterns didn't exist in this file however.
* **11.0**: This one has some Chrome on Google TV patterns that 10 and earlier don't have (and later versions don't either).
* **12.0 - 13.0**: Also didn't modify the split here, no google TV patterns, so I kept it separate.
* **14.0 - 21.0**: Compared to 12-13 has some newer platforms in it, like OSX 10.12 and Windows 10, so kept the split.
* **22.0 - 27.0**: At Chrome 22 OSX 10.5 is dropped.
* **28.0 - 36.0**: Chrome switches to the Blink rendering engine at version 28.
* **37.0 - 49.0**: Version 37 was the first 64 bit version of the browser.
* **50.0 on**: At version 50, Windows XP and OSX < 10.9 are dropped. 

## iOS

I primarily used archive.org's snapshots of the Apple App Store for the Chrome browser to determine when certain versions of iOS were dropped, which is the only reason for the splits here.

* **19.0 - 25.0**: First release was 19, which supported iOS 4.3 and higher.
* **26.0 - 29.0**: Minimum iOS version is bumped to 5.0 at version 26.0
* **30.0 - 37.0**: Minimum iOS version is bumped to 6.0 at version 30.0
* **38.0 - 47.0**: Minimum iOS version is bumped to 7.0 at version 38.0
* **48.0 on**: Minimum iOS version is bumped to 9.0 at version 48.0

## Android

There aren't too many splits here, this comes from the google release blog mainly:

* **16.0**: I believe there was a beta release with the 16 version (first stable release was 18.0)
* **18.0 - 27.0**: First stable release of Android Chrome.  This technically doesn't include every version between 18 and 27 because there was no 19, 20, 21, 22, 23 and 24, which is how the versions are defined in this file. 
* **28.0 - 42.0**: Chrome is updated to use the Blink rendering engine at Chrome 28.
* **43.0 on**: At version 43.0, support for Android OS 4.0 is dropped.

I've removed a lot of patterns that were added to catch some odd formats of UAs, like missing the "Safari/" part at the end (from what I've seen, these are UAs that have been truncated, and not actually a UA that Chrome would generated). I made it so that the generic pattern will still catch a lot of these, so that they don't go undetected, but these patterns won't bloat the pattern count in the versioned files.

I also decided to add the `#MINORVER#` tag to the version in the patterns so that only *.0 releases are caught by the versioned files, this helps with detecting spoofed UAs, or UAs that should actually be detected as other browsers. The only Chrome release (Stable, Beta or Dev) that I've seen that doesn't have a 0 minor version has been the 4.1 release on Windows (which is currently detecting as Comodo Dragon, but my branch fixes this).

There were also some other little cleanup things I did, like removing the `Linux_32` platform from the files since it really didn't add much other than extra patterns to the files for no obvious gain (the `Linux` platform would catch any that the `Linux_64` pattern didn't, and the data for both `Linux` and `Linux_32` are the same, so it seemed redundant).

As per @mimmi20's suggestion, I also made it so that the Lite file only includes the last ~10 versions and the Standard file only includes the last ~20 versions (for each platform). This reduces the pattern count/file size in those two files quite a bit.

INI file size comparison:

File|Line Count (my branch)|Line Count (master)|Difference|Pattern Count (my branch)|Pattern Count (master)|Difference
-----|-----|-----|-----|-----|-----|-----
full_php_browscap.ini|2,307,526|2,325,715|-18,189|209,372|210,919|-1,547
php_browscap.ini|379,856|412,940|-33,084|82,152|89,325|-7,173
lite_php_browscap.ini|12,814|13,927|-1,113|2,790|3,090|-300

I've also added a lot of tests to cover everything that I have useragents for. Overall it'll add about 1,200 tests to the Full suite.  I was a bit OCD about which UAs got added as tests, and made sure that the version numbers of the UA looked legit (I used version numbers from the chrome releases blog, and then also made sure that any that didn't match those versions exactly at least were in the right "version range" (the third set of digits in the version string)).  Anything else was discarded as it's most likely a spoofed UA.

I'll wait until #1521 is merged before submitting the PR so that I can resolve all of the conflicts.  I'll also perform some comparison tests of my branch to `master` to be sure everything is still detecting well (and the only differences are expected).

**Comment by mimmi20** [comment]
@jaydiablo Please submit your PR. Maybe @asgrim need more time to review and approve PR #1521.
