### ISSUE TITLE
Add AOL Desktop

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1469]
Found a lot of UAs that resemble this:

>Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.0 AOL/9.7 AOLBuild/4343.3026.US Safari/537.1

When I was looking at UAs for #1448.

This is apparently the "AOL Desktop" product: https://discover.aol.com/products-and-services/aol-desktop-for-windows

There is also a Mac version, but it has a different useragent: https://discover.aol.com/products-and-services/aol-desktop-for-mac?icid=daol%257caoldsktpmac2

>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko, Safari/12603.1.30.0.34) ADM/784

(That's a test I did from my Mac. Currently Browscap parses that as the "Adobe Dialog Manager", which is incorrect, I'll fix that)

There are also some Trident based versions of this product which have a UA like this:

>Mozilla/5.0 (compatible; MSIE 10.0; AOL 9.5; AOLBuild 4337.156; Windows NT 6.2; Trident/8.0)

According to Wikipedia, at version 9.8 AOL moved to a Chromium based engine for the browser component of AOL Desktop (https://en.wikipedia.org/wiki/AOL#AOL_Desktop), but there also was a 10.x version of the Trident engine based Desktop.

The UAs I've found seem to coincide with this (though I do see a lot of 9.7 versions with the Chromium pattern, which might be because of a transition phase, or a beta release).

**Comment by mimmi20** [comment]
The version of the `AOL` token in this UA
>Mozilla/5.0 (compatible; MSIE 10.0; AOL 9.5; AOLBuild 4337.156; Windows NT 6.2; Trident/8.0)
was used as `AolVersion` property some years ago. But we should not use that property again.

**Comment by jaydiablo** [comment]
I agree, seems redundant.
