### ISSUE TITLE
Incorrect Version Number on Firefox for Mac

### ISSUE THREAD

**Issue by ibewa** [browscap/browscap#1524]
Firefox for Mac v54 is reported as v52

**Comment by jaydiablo** [comment]
Please provide a sample useragent.

**Comment by ibewa** [comment]
True version:





User agent:

'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:51.0) Gecko/20100101 Firefox/51.0'



Here is the complete array returned:

array (
  'browser_name_regex' => '~^mozilla/5\\.0 \\(.*mac os x 10.11.*\\) gecko.* firefox/51\\.0.*$~',
  'browser_name_pattern' => 'Mozilla/5.0 (*Mac OS X 10?11*) Gecko* Firefox/51.0*',
  'parent' => 'Firefox 51.0',
  'browser_bits' => '32',
  'platform' => 'MacOSX',
  'platform_version' => '10.11',
  'platform_description' => 'Mac OS X',
  'platform_bits' => '32',
  'platform_maker' => 'Apple Inc',
  'device_name' => 'Macintosh',
  'device_maker' => 'Apple Inc',
  'device_code_name' => 'Macintosh',
  'device_brand_name' => 'Apple',
  'comment' => 'Firefox 51.0',
  'browser' => 'Firefox',
  'browser_type' => 'Browser',
  'browser_maker' => 'Mozilla Foundation',
  'version' => '51.0',
  'majorver' => '51',
  'frames' => '1',
  'iframes' => '1',
  'tables' => '1',
  'cookies' => '1',
  'javascript' => '1',
  'javaapplets' => '1',
  'cssversion' => '3',
  'device_type' => 'Desktop',
  'device_pointing_method' => 'mouse',
  'renderingengine_name' => 'Gecko',
  'renderingengine_version' => '51.0',
  'renderingengine_description' => 'For Firefox, Camino, K-Meleon, SeaMonkey, Netscape, and other Gecko-based browsers.',
  'renderingengine_maker' => 'Mozilla Foundation',
  'browser_modus' => 'unknown',
  'minorver' => '0',
  'alpha' => '',
  'beta' => '',
  'win16' => '',
  'win32' => '',
  'win64' => '',
  'backgroundsounds' => '',
  'vbscript' => '',
  'activexcontrols' => '',
  'ismobiledevice' => '',
  'istablet' => '',
  'issyndicationreader' => '',
  'crawler' => '',
  'isfake' => '',
  'isanonymized' => '',
  'ismodified' => '',
  'aolversion' => '0',
)

**Comment by mimmi20** [comment]
@ibewa This is a useragent and a result for Firefox 51. Do you have the useragent for the Firefox 54?

**Comment by ibewa** [comment]
That is my problem. The user agent seems wrong.

The data I sent to you is indeed the user agent string I get back from PHP 7.0 and latest download of browscap on Firefox 54.

**Comment by ibewa** [comment]
I found a clue to the problem. Until now I have been updating Firefox using it’s standard self updating model.

I deleted Firefox , re-downloaded it and now it is reporting correctly.

Thanks for your help.

**Comment by holtkamp** [comment]
>I deleted Firefox , re-downloaded it and now it is reporting correctly.

@ibewa so this issue can be closed?

**Comment by ibewa** [comment]
Yes my issue is resolved.
Please close the ticket.
Thanks
