### ISSUE TITLE
Version Number on Opera for Mac missing.

### ISSUE THREAD

**Issue by ibewa** [browscap/browscap#1525]
Opera for Mac v45 is reported as 0.0.

**Comment by jaydiablo** [comment]
We'd need a sample useragent to confirm, but version 45 for OSX is present in the data files:

https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/opera/opera-42-on.json#L3

But it may depend on which version of OSX is in the UA.  Please provide a sample useragent.

**Comment by ibewa** [comment]
User Agent:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 OPR/45.0.2552.898

**Comment by jaydiablo** [comment]
This parses properly against `master`:

```
{
    "browser_name_regex": "\/^mozilla\\\/5\\.0 \\(.*mac os x 10.11.*\\) applewebkit.* \\(.*khtml.*like.*gecko.*\\).*chrome\\\/.*safari\\\/.*opr\\\/45\\.0.*$\/",
    "browser_name_pattern": "mozilla\/5.0 (*mac os x 10?11*) applewebkit* (*khtml*like*gecko*)*chrome\/*safari\/*opr\/45.0*",
    "parent": "Opera 45.0",
    "comment": "Opera 45.0",
    "browser": "Opera",
    "browser_type": "Browser",
    "browser_bits": "32",
    "browser_maker": "Opera Software ASA",
    "browser_modus": "unknown",
    "version": "45.0",
    "majorver": "45",
    "minorver": "0",
    "platform": "MacOSX",
    "platform_version": "10.11",
    "platform_description": "Mac OS X",
```

Looks like version 45 was added as part of this commit: https://github.com/browscap/browscap/commit/787871f5617bb23d0126f597038ace73939acf9d#diff-6d2249f8ce04df3d46f7dafb08f84ab7R3

Which hasn't been released yet.  When `6024` is released, the version number will be populated correctly.

**Comment by ibewa** [comment]
Great !!! Thanks.

**Comment by jaydiablo** [comment]
This parses correctly with the release of 6024, confirmed on browscap.org.

This ticket can be closed.
