### ISSUE TITLE
Add YandexBot/3.0

### ISSUE THREAD

**Issue by clund** [browscap/browscap#1530]
: Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)

Note the colon prefix.

Spotted from: 178.154.189.202

**Comment by jaydiablo** [comment]
We've also seen that variation of the Yandex bot from that IP, but only briefly in June, perhaps a mis-configured bot.  Doesn't hurt much to add the UA though.

May want to make sure that all variations of the Yandex bots (including the one in this issue) are covered:

https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html
