### ISSUE TITLE
Snapchat user agent 

### ISSUE THREAD

**Issue by dczaretsky** [browscap/browscap#1532]
Please add support for Snapchat's bot for scraping websites:

Snapchat/10.12.0.2 (iPhone8,1; iOS 10.3.2; gzip)

**Comment by jaydiablo** [comment]
Some more variations:

>Snapchat/10.11.1.0 (iPhone6,1; iOS 10.2.1; gzip)
>Snapchat/10.2.0.2 (iPhone5,1; iOS 10.1.1; gzip)
>Snapchat/9.45.10.0 (iPhone6,1; iOS 10.1.1; gzip)

Based on the IP addresses we saw on these, it seems that it's the user's device making the request, and not a true "bot" that snapchat sends out from their data centers.  Seems like they're probably preview requests though.

#1526 is sort of related in that do we flag these as a bot, or as an app?

**Comment by mimmi20** [comment]
If this is for scraping websites, in my opinion it should be a bot.

**Comment by jaydiablo** [comment]
I assume it's used to generate a preview image/content or something like that. Sort of like the Skype URI preview. I can try to test it out later to confirm.
