### ISSUE TITLE
APUS Browser android-only?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1534]
Browscap has the "APUSBrowser" defined here:

https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/apus-browser/apus-browser.json

Which appears to have been added because of some UAs from #712.

I've searched through our logs (from this year) for "APUSBrowser" and this is the only UA that comes up:

>Mozilla/5.0 (Windows; U; Windows NT 5.2; en) Chrome/37.0.2049.0 (KHTML, like Gecko) Version/4.0 APUSBrowser/1.1.720 Safari/

Which is similar to the UAs in the test suite:

https://github.com/browscap/browscap/blob/master/tests/fixtures/issues/issue-712.php#L1012
https://github.com/browscap/browscap/blob/master/tests/fixtures/issues/issue-712.php#L2231

This is the earliest snapshot of the APUS website (apusapps.com) at archive.org: https://web.archive.org/web/20141025041329/http://www.apusapps.com/#APUS which is from October of 2014. It **seems** that from the beginning they've always focused on Android apps.  Their current site only provides an Android download link for the browser: http://www.apusapps.com/en/browser/

Unfortunately I don't have an Android device handy to test what the android browser's UA is, but I'll try to get my hands on something and give it a test.

That said, should these UAs be trusted? Was there ever a windows version of this browser?

**Comment by mimmi20** [comment]
I sent an email to `APUSBrowserEcho@gmail.com` and asked about the UA.

**Comment by jaydiablo** [comment]
I just downloaded the browser through google play store onto an Android x86 VM and looked at both the regular UA and the "Desktop Site" UA, both of them are just generic Chrome UAs (regular one was Webview on Android, desktop site one was Chrome on Linux).

**Comment by mimmi20** [comment]
I installed the browser and looked into the headers. The browser sends a `x-requested-with` header additional to the normal `user-agent` header. The normal header does not show any information about Apus.
