### ISSUE TITLE
incorrect display for User Agent

### ISSUE THREAD

**Issue by KyKyIIIKuH** [browscap/browscap#1536]
Hello,
When I go to the browser "Google Chrome", UA Lookup wrote that I went to the browser chrome.
But if to come to the browser "Amigo Browser", UA Lookup wrote that I went to the browser chrome, instead of to write browser "Amigo Browser".
Also, if I log in from the browser "UC Browser", UA Lookup writes that I went with the browser chrome, instead of writing a browser "UC Browser:".
____
Когда я захожу с браузера "Google Chrome", UA Lookup пишет что я зашел с browser chrome.
Но если зайти с браузера "Amigo Browser", UA Lookup пишет что я зашел с browser chrome , вместо того чтобы написать browser "Amigo Browser".
Также если зайти с браузера "UC Browser", UA Lookup пишет что я зашел с browser chrome , вместо того чтобы написать browser "UC Browser:".
____
User Agent:
- Amigo Browser:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.197 Amigo/56.0.2924.197 MRCHROME SOC Safari/537.36

- UC Browser:
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.2909.1402 Safari/537.36

- Google Chrome:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by jaydiablo** [comment]
These parse properly in `master`, which most likely means they were addressed in commits that haven't been released yet. When the next release is made (6024), these should parse correctly.

> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.197 Amigo/56.0.2924.197 MRCHROME SOC Safari/537.36
```
"browser_name_regex": "\/^mozilla\\\/5\\.0 \\(.*windows nt 10\\.0.*wow64.*\\) applewebkit.* \\(.*khtml.*like.*gecko.*\\) chrome\\\/56\\..* amigo\\\/56\\..* safari\\\/.*$\/",
    "browser_name_pattern": "mozilla\/5.0 (*windows nt 10.0*wow64*) applewebkit* (*khtml*like*gecko*) chrome\/56.* amigo\/56.* safari\/*",
    "parent": "Amigo 56.0",
    "comment": "Amigo 56.0",
    "browser": "Amigo",
```

>Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 UBrowser/6.1.2909.1402 Safari/537.36
```
{
    "browser_name_regex": "\/^mozilla\\\/5\\.0 \\(.*windows nt 10\\.0.*wow64.*\\) applewebkit.* \\(.*khtml.*like.*gecko.*\\) chrome\\\/.* ubrowser\\\/6\\.1.* safari\\\/.*$\/",
    "browser_name_pattern": "mozilla\/5.0 (*windows nt 10.0*wow64*) applewebkit* (*khtml*like*gecko*) chrome\/* ubrowser\/6.1* safari\/*",
    "parent": "UC Browser 6.1 for Desktop",
    "comment": "UC Browser 6.1",
    "browser": "UC Browser",
```

>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36
```
{
    "browser_name_regex": "\/^mozilla\\\/5\\.0 \\(.*windows nt 10\\.0.*win64. x64.*\\) applewebkit.* \\(.*khtml.*like.*gecko.*\\) chrome\\\/60\\..*safari\\\/.*$\/",
    "browser_name_pattern": "mozilla\/5.0 (*windows nt 10.0*win64? x64*) applewebkit* (*khtml*like*gecko*) chrome\/60.*safari\/*",
    "parent": "Chrome 60.0",
    "comment": "Chrome 60.0",
    "browser": "Chrome",
```

I'll look at adding these as regression tests though.

**Comment by jaydiablo** [comment]
There are already tests that cover the patterns for these three UAs, so no need to add these as tests.

Once 6024 is released, these will parse correctly for you.

Thanks!

**Comment by jaydiablo** [comment]
6024 has been released, and I've confirmed that these three UAs parse correctly on browscap.org.

This ticket can be closed.
