### ISSUE TITLE
`Device_Type` in Lite file but not Standard

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1544]
I ran into this when making some changes for #1528 and wanted to verify that this is the expected behavior.

I have some tests failing due to the `Device_Type` property being a different value than what is expected, but only the Lite tests fail (Full and Standard pass fine).  Both the Lite and Standard files have the same `Device_Type` here, but `Device_Type` isn't available in the Standard file, due to this function:

https://github.com/browscap/browscap/blob/master/src/Browscap/Data/PropertyHolder.php#L162

But is available in the Lite file:

https://github.com/browscap/browscap/blob/master/src/Browscap/Data/PropertyHolder.php#L146

I assume this is expected, since that's how the code is, but I wanted to double check. It seems odd to me that a "lesser" file (the Lite file) contains more properties than the Standard file.

**Comment by jaydiablo** [comment]
Also, I've noticed that a lot (almost all) of the Tablet devices have `"standard": true`, is this just causing the standard file to be unnecessarily large if there is no device information returned?

**Comment by mimmi20** [comment]
This is an error that I found while working on Issue #1433 (I try to fix it there).

The tablets are set for the standard file, to have the right information in the `isTablet` and `DeviceType` properties. But I do not remeber why we defined these proprties for the Lite mode.
