### ISSUE TITLE
Android tablets detected as phone

### ISSUE THREAD

**Issue by lloydmurray** [browscap/browscap#1564]
The following android tablets (useragents) are being categorized as mobile phones.  Request that a slightly more restrictive rule be developed to classify them as a tablet.

Galaxy Tab S3 | Mozilla/5.0 (Linux; Android 7.0; SM-T820 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Safari/537.36

Galaxy Tab S | Mozilla/5.0 (Linux; Android 6.0.1; SM-T807V Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36

Galaxy Tab 4-8.0 | Mozilla/5.0 (Linux; Android 5.1.1; SM-T337V Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Safari/537.36

Google Nexus 9 | Mozilla/5.0 (Linux; Android 5.1.1; Nexus 9 Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Safari/537.36

**Comment by jaydiablo** [comment]
#1548 changed some browsers (Chrome was included in that list) to detect UAs without the "Mobile" keyword as "general Tablet" if the device isn't detected explicitly, which I've confirmed does happen to these 4 UAs now (this change hasn't been released yet).

That said, I think we should still add these devices.
