### ISSUE TITLE
GrepCommand, DiffCommand

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1567]
These two commands are actually not working. Browscap is called there in the V1 syntax.

Does anyone use these commands? If not I would prefer to remove them.

**Comment by asgrim** [comment]
If they're not working, they're probably not used :laughing:

**Comment by jaydiablo** [comment]
I've never used either.

I think the `diff` command is referenced in wiki/readme: 

https://github.com/browscap/browscap/blame/master/README.md#L47
https://github.com/browscap/browscap/wiki/Diff-Command
