### ISSUE TITLE
macOS High Sierra

### ISSUE THREAD

**Issue by tobiashinz** [browscap/browscap#1600]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

Platform is wrong with Mac OS X (should be macOS).
Version should be 10.13 instead of 10.

**Comment by jaydiablo** [comment]
This macOS version was added in #1575 and will be available in the next release of browscap INI file (6025).

Thanks!
