### ISSUE TITLE
Sparrow

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1620]
It seems like [Sparrow](https://aploader.com/publisher/sparrowmailapp) is not available.
Here are some user-agents, i found:

<pre>
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Sparrow/1172
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Sparrow/1178
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.7 (KHTML, like Gecko) Sparrow/1178
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Sparrow/1178
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Sparrow/1178
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Sparrow/1176
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Sparrow/1173
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Sparrow/1178
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Sparrow/959.4
</pre>

**Comment by jaydiablo** [comment]
This is a duplicate of #1527

**Comment by jaydiablo** [comment]
I moved the UAs from this ticket to #1527.
