### ISSUE TITLE
Zimbra Desktop

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1621]
It seems like [Zimbra Desktop](https://www.zimbra.com/zimbra-desktop/) is not available.
Here are some user-agents, i found:

<pre>
Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.5
Mozilla/5.0 (Windows; U; Windows NT 6.1; fr; rv:1.9.0.1) Gecko/2008072406 Prism (zdesktop/1.0.4)
Mozilla/5.0 (Windows; U; Windows NT 6.1; fr; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.7
Mozilla/5.0 (Windows; U; Windows NT 6.1; fr; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.8
Mozilla/5.0 (Windows; U; Windows NT 6.2; fr; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.7
</pre>

**Comment by jaydiablo** [comment]
A few others we've seen in our logs:

```
Mozilla/5.0 (Windows; U; Windows NT 6.2; en-US; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.5
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.16pre) Gecko/20110902 Prism zdesktop/7.1.2
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.8pre) Gecko/20100725 Prism zdesktop/2.0.1
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-AU; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.5
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.5
```

I tried downloading it and seeing if I could verify the UA, but apparently I don't have a Java Runtime Environment installed.

**Comment by jaydiablo** [comment]
The most recent version of Zimbra does not identify itself in the UA:

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36`

**Comment by mmorel-35** [comment]
The archived version can still be found [here](https://www.zimbra.com/downloads/zimbra-desktop/archives/)

**Comment by jaydiablo** [comment]
I can confirm that 7.2.8 has the "zdesktop" UA:

>Mozilla/5.0 (Windows; U; Windows NT 6.2; en-US; rv:1.9.2.19pre) Gecko/20110902 Prism zdesktop/7.2.8

**Comment by jaydiablo** [comment]
Thanks @mmorel-35 !
