### ISSUE TITLE
The "other" Sparrow browser

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1623]
While looking for UAs for #1527, I noticed a handful of UAs on Linux and Windows with the "Sparrow" keyword in them:

```
Mozilla/5.0 (X11; Linux x86_64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.2469  Safari/537.36 Sparrow/0.1
Mozilla/5.0 (X11; Linux x86_64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.2950  Safari/537.36 Sparrow/0.1
Mozilla/5.0 (Windows NT 6.1; WOW64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.7011  Safari/537.36 Sparrow/0.1
Mozilla/5.0 (X11; Linux x86_64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.308  Sparrow/0.0.308.0 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; WOW64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.2950  Safari/537.36 Sparrow/0.1
```

As far as I know, the Sparrow email client mentioned in #1527 was only available for iOS and Mac.  These might belong to this "other" Sparrow browser that came up in a google search:

http://www.browser.exede.net/

Unfortunately, can't verify this one yet.

**Comment by mmorel-35** [comment]
Take a look on [this page](https://udger.com/resources/ua-list/browser-detail?browser=ViaSat+Sparrow).
I hope it helps
