### ISSUE TITLE
Samsung Devices

### ISSUE THREAD

**Issue by gitdamn** [browscap/browscap#1630]
It seems many user agents don't properly get mapped to "Samsung"

for example:
SAMSUNG-C6625/1.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) Profile/MIDP-2.0 Configuration/CLDC-1.1
SAMSUNG-GT-S3350/1.0 NetFront/3.5 Profile/MIDP-2.0 Configuration/CLDC-1.1
SAMSUNG-GT-I9008L_TD/1.0 Android/2.2.1 Release/12.15.2010 Browser/AppleWebKit533.1 Profile/MIDP-2.1 Configuration/CLDC-1.1
SAMSUNG-GT-S7550/S7550XXIK5 SHP/VPP/R5 NetFront/3.5 SMM-MMS/1.2.0 profile/MIDP-2.0 configuration/CLDC-1.1
SAMSUNG-GT-C3590/1.0 NetFront/4.2 Profile/MIDP-2.0 Configuration/CLDC-1.1
Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG-SGH-I337 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG-SM-G800A Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 5.0; SAMSUNG-SM-N900A Build/LRX21V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.1.2; pl-pl; SAMSUNG SM-T211/T211XXAML5 Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 2.3.6; nl-nl; SAMSUNG GT-B5510/B5510XXLL1 Build/GINGERBREAD) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

All of the above are either unknown or have maker as unknown.

Can this be addressed?

thanks,

**Comment by jaydiablo** [comment]
As part of this issue I'm pulling all UAs I can find that have those devices in them, and making sure the devices only have the Android versions linked to them that they're known to support.  That brings up one issue that I wanted to discuss:

I noticed that the `Samsung GT-I9300` device had `Android_2_3` linked to it in the UC Browser 10.x file, so I removed that, which causes a test to fail (`issue-635-AW`).

As far as I can tell, the `GT-I9300` shipped with Android 4.0 and is upgradeable to Android 4.4:

https://www.gsmarena.com/samsung_i9300_galaxy_s_iii-4238.php (claims 4.0 and 4.3)
http://www.samsung.com/africa_en/consumer/mobile-devices/smartphones/galaxy-s/GT-I9300RWDXFA/ (shows 4.0)
https://www.phonegg.com/phone/2590-Samsung-Galaxy-S-III-GT-i9300-16GB (shows 4.0)
https://en.wikipedia.org/wiki/Samsung_Galaxy_S_III (shows Android 4.0 -> 4.4 in sidebar, excluding the 7.1 custom OS mention. Also mentions that it launched with 4.0.4 in the intro section and is upgradeable to 4.4 (if the phone has 2gb of ram)).

It seems possible to upgrade to newer versions of the OS using custom ROMs (as mentioned in the wikipedia sidebar, and this article: https://www.androidpit.com/galaxy-s3-android-update). But I haven't seen mention of the phone ever supporting Android 2.3.

The UA in our test suite is this one:

>Mozilla/5.0 (Linux; U; Android 2.3.6; en-US; GT-I9300 Build/MocorDroid2.2.2) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.2.0.535 U3/0.8.0 Mobile Safari/534.30

The interesting bit there is "MocorDroid" which I believe is a custom Android ROM, here's a guide that mentions rooting a "Chinese GT-I9300", though it shows that the phone is running 4.0 initially: https://forum.xda-developers.com/showthread.php?t=2141663

So all of that said, should I remove this android version and the test (can move it to invalid versions file perhaps)?  It's just one platform multiplied by 11 versions (so only 11 patterns removed), but it does beg the question, should we add android versions that aren't officially supported by the device?

Seems like it's similar to trying to support desktop platforms for browsers that don't support them (but it's possible to run them on with kernel extensions or whatever).

**Comment by mmorel-35** [comment]
It depends on what you want to do. Is the goal of this project to be able to translate the informations in a user agent? (then you should) if on the other hand tge goal is to check the validity of a UA then you probably shouldn't.

**Comment by jaydiablo** [comment]
Yeah, it's a balance.

Every platform/version/device we add to the useragent files adds patterns to the INI files, which increases the size of the file and can also affect parsing performance. I've been trying to limit what I add to just "valid" platform/browser/device/version combinations where possible.

A lot of other parsers break out the UA pattern into capturable sections, so it's not as expensive for them to detect something like Chrome 10 on Android 2.0 on a Samsung Galaxy S8 (which technically shouldn't be possible, for a lot of reasons ;) ).  If this project tried to detect every possibly combination, the INI/CSV/XML files would grow out of control and parsing performance would suffer drastically.

**Comment by jaydiablo** [comment]
Yeah, it's a balance.

Every platform/version/device we add to the useragent files adds patterns to the INI files, which increases the size of the file and can also affect parsing performance. I've been trying to limit what I add to just "valid" platform/browser/device/version combinations where possible.

A lot of other parsers break out the UA pattern into capturable sections, so it's not as expensive for them to detect something like Chrome 10 on Android 2.0 on a Samsung Galaxy S8 (which technically shouldn't be possible, for a lot of reasons ;) ).  If this project tried to detect every possibly combination, the INI/CSV/XML files would grow out of control and parsing performance would suffer drastically.

**Comment by jaydiablo** [comment]
I'm also not sure what this should be parsed as:

>SAMSUNG-GT-I9008L_TD/1.0 Android/2.2.1 Release/12.15.2010 Browser/AppleWebKit533.1 Profile/MIDP-2.1 Configuration/CLDC-1.1

Most other parsers parse this one as Android Browser with an unknown version number (http://useragent.mkf.solutions/?userAgent=SAMSUNG-GT-I9008L_TD%2F1.0+Android%2F2.2.1+Release%2F12.15.2010+Browser%2FAppleWebKit533.1+Profile%2FMIDP-2.1+Configuration%2FCLDC-1.1).

This site lists the platform for that device as "Borqs OPhone OS 2.0" (http://phonedb.net/index.php?m=device&id=2585&c=samsung_gt-i9008_galaxy_s)
This forum post seems to agree with that: https://forum.xda-developers.com/showthread.php?t=917187
The more general model (GT-I9000) version of the Galaxy S is claimed to support Android 2.1 -> 2.3 (https://www.gsmarena.com/samsung_i9000_galaxy_s-3115.php)

So I think the platform version is probably correct here (Android 2.2), but I'm not sure about the browser version. Currently there isn't anything in the resources for Android Browser < 3.0.  Should we put UAs like this one in the generic Android file? Should a 2.2 version of the Android Browser be added?  Should this go in the 4.0 version file, as that's where most of the 2.x Android devices live?

**Comment by mmorel-35** [comment]
If you want to avoid the growth of the files, the starting point would be to define the attributes(platform, browser...) you want in them (arbitrary decided or dynamically by the final user). Then based on those criteria the file is generated with the optimal size of pattern to give at least one of those intel.

**Comment by jaydiablo** [comment]
@mimmi20 The only one I found that would work for this UA is this pattern:

`#DEVICE#/1.0 Android/#MAJORVER#.#MINORVER#* Release/* Browser/*applewebkit*`

This one lives in the `android-browser-4-4.json` file. I'd have to add an android-browser 2.2 version to be able to match the browser version to the platform version (which seems too low of a version for the Android browser since we have patterns for 3.0 browser version being used on Android 1.x devices.

Best to make it a version-less pattern and store in `android-browser-generic.json`?

**Comment by mimmi20** [comment]
I did not look into the versions of the android browser. Please add this to the generic file.

**Comment by gitdamn** [comment]
My issue is more they don't identify as "Samsung" we use this to determine content.
Is this something which can be fixed/updated?

**Comment by jaydiablo** [comment]
@gitdamn, yes, I'm working on it, should have a PR soon.
