### ISSUE TITLE
Thunderbird 52.3

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1642]
Latest version of [Thunderbird ](https://www.mozilla.org/fr/thunderbird/) is available and it seems undetected : 

<pre>
Mozilla/5.0 (X11; SunOS i86pc; rv:52.0) Gecko/20100101 Thunderbird/52.3.0
</pre>

**Comment by jaydiablo** [comment]
I believe the reason that that one goes undetected is because of the OS (`SunOS`).

The version number does need to be added as well, but that wouldn't prevent it from being detected at all (Should still detect as `Thunderbird`, but with the `0.0` version number).

**Comment by jaydiablo** [comment]
The Thunderbird site doesn't list Solaris as an official supported platform, but it does seem that a tarball gets uploaded to their FTP server at some point. The last one I saw was for version 52.0:

https://ftp.mozilla.org/pub/thunderbird/releases/52.0/contrib/

Of course, anyone can build from source for their OS.

Should we consider adding Solaris to Thunderbird patterns?

**Comment by mimmi20** [comment]
We could add this to the generic section. Is `SunOS` in the useragent really Solaris?

**Comment by jaydiablo** [comment]
/quote The SunOS name is usually only used to refer to versions 1.0 to 4.1.4, which were based on BSD, while versions 5.0 and later are based on UNIX System V Release 4, and are marketed under the brand name Solaris.

https://en.wikipedia.org/wiki/SunOS

I'm not sure if apps installed on Solaris identify themselves differently in the useragent or not.
