### ISSUE TITLE
Missing browser/app versions for October

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1664]
Trying to make this a monthly thing to keep up on browser releases.

**Comment by mmorel-35** [comment]
When do you intend to release the next version as the 6026 is 3 months old now ?

**Comment by jaydiablo** [comment]
@asgrim is in charge of that process currently, probably about time eh James?  When you have time of course.

**Comment by asgrim** [comment]
Yes, the release schedule is "when people bother me enough" :grin:

**Comment by asgrim** [comment]
6027 is released \o/

**Comment by mmorel-35** [comment]
Thank you @asgrim 😊!
