### ISSUE TITLE
Folder by Browser_Type

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1675]
Under  "browscap/resources/user-agents/" are four folder representing different browser types.
But it seems that it's a bit messy for now.
How do you feel about having a strict differentiation?
For example 
"resources/user-agents/apps/barca-mail-client.json" and "resources/user-agents/browsers/kontact/kontact-generic.json" would move to 
"resources/user-agents/email-clients/barca-mail-client.json" and "resources/user-agents/email-clients/kontact/kontact-generic.json".

I'm taking the example of "Email Client" but it can be applied with caution to the rest of the browser types.

**Comment by jaydiablo** [comment]
I'm in favor of this, I think having that organization would be nice.

I think it's rare enough that a useragent switches Browser_Type that we shouldn't have to worry about extra maintenance.

@mimmi20 ?

**Comment by mimmi20** [comment]
The is not really a system how the useragents were split into these groups.

You may look over the useragents, if the browser type is matching to what the application does.
You should not add new browser types because this would require changes in the browscap-php library.

**Comment by mmorel-35** [comment]
I'm not offering to create new browser types. What I'm suggesting is a standardisation of the arborescence of the resources.
Would it haave a real impact on browwscap-php ?

**Comment by mimmi20** [comment]
Just changes the structure inside the user-agents directory does not have any impact to browscap-php.
