### ISSUE TITLE
Add Stumble Upon Bot

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1677]
>Mozilla/5.0 (Windows NT 6.1; stumbleupon.com) Chrome/58.0.3029.110 Safari/537.36

Confirmed that this one is coming from StumbleUpon servers.

**Comment by mmorel-35** [comment]
You also noticed one UA from StumbleUpon in #1219 

> Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.6) Gecko/20040206 Mozilla/5.0 StumbleUpon/1.904
