### ISSUE TITLE
Suggestion : Generate ini file with "just enough" information

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1686]
When you use the browscap files you necessarily need all the informations that can be read from a user agent. The patterns used in the file need more or less precision in their definition.
Let's take an example with resources/user-agents/browsers/chrome/chrome-50-on.json and take those three children with the same match and different attributes : 
<pre>        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "Windows Desktop",
          "platforms": [
            "Win7_x64", "Win7_64", "Win7_32",
            "Win8_x64", "Win8_64", "Win8_32",
            "Win8_1_x64", "Win8_1_64", "Win8_1_32",
            "Win10_x64", "Win10_64", "Win10_32", "Win10_x64_B", "Win10_64_B", "Win10_32_B"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_13", "OSX_10_12", "OSX_10_11", "OSX_10_10", "OSX_10_9",
            "OSX"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "general Desktop",
          "platforms": [
            "FreeBSD_64", "FreeBSD_64_2", "FreeBSD",
            "OpenBSD_64_3", "OpenBSD_64_2", "OpenBSD_64", "OpenBSD",
            "NetBSD"
          ]
        }</pre>
If I don't need the version #MAJORVER#.#MINORVER# can be replaced with a star
If I don't need every intel on the platform but just the "Platform_Maker" attribute, the "Windows" platform would be enough for the first child as it is the parent of all of them. "OSX" for the next and "FreeBSD","OpenBSD" and "NetBSD" for the last.

So, based on the criteria needed and their place in the hierarchy of the elements, the number of patterns needed by file could be adapted.

The Version would be replaced by a star and the element (device, platform,...) by the expression that holds "just enough" information.

**Comment by mimmi20** [comment]
> If I don't need the version #MAJORVER#.#MINORVER# can be replaced with a star

We do this in the `generic` files.

> If I don't need every intel on the platform but just the "Platform_Maker" attribute, the "Windows" platform would be enough for the first child as it is the parent of all of them. "OSX" for the next and "FreeBSD","OpenBSD" and "NetBSD" for the last.

How would you filter these requierements?

**Comment by mmorel-35** [comment]
When you create the different files lite,standard and full don't you filter some fields ?

**Comment by jaydiablo** [comment]
Yes, which is based on a couple of things.

Each `userAgent` has a `lite` and `standard` property which can be `true` or `false`. When building the Lite file, if the userAgent has `lite` set to `false` then all of the patterns in that file are ignored for that file.

This also happens at the device and platform level, again, if set to `false`, then any patterns that use that device or platform are not included in the file.

As for which properties end up in the patterns that do get included, that's based on this class:

https://github.com/browscap/browscap/blob/master/src/Browscap/Data/PropertyHolder.php#L126

The patterns themselves aren't modified at all based on these filters, it just determines which patterns are included, and which properties of those patterns are included.

**Comment by mmorel-35** [comment]
Then how do you choose what is in which version, can't it be automatically determined by it's attributes or parent.
For example, if you have windows, windows64, and then windows8.1. Windows8.1 64. 
How do you choose?

**Comment by jaydiablo** [comment]
The `platforms.json` file has `lite` and `standard` properties defined on each platform, for example here is the `Windows` platform:

https://github.com/browscap/browscap/blob/master/resources/platforms.json#L2109

And here is `Win8_64`:

https://github.com/browscap/browscap/blob/master/resources/platforms.json#L2835

It's set to `false` for both `lite` and `standard` so patterns with that platform defined won't show in the Lite and Standard files (if the same patterns have a `Windows` platform, then those patterns will probably still be included in the Lite and Standard files, but just with that `Windows` platform).

Patterns that have that platform will be included in the Lite and Standard files (if the main useragent and the device is also set to be included in the Lite and Standard files).

Here is the `Windows Desktop` device (which most `Windows` platforms will use):

https://github.com/browscap/browscap/blob/master/resources/devices/desktop/unknown.json#L15

I noticed that doesn't have a `lite` property, I'm not sure why that is, perhaps the Lite file doesn't include device info at all, so it's not important to have that property defined on the devices.

Hopefully that made sense, and answers your question. :)

**Comment by mimmi20** [comment]
> For example, if you have windows, windows64, and then windows8.1. Windows8.1 64.
How do you choose?

The difference between `windows` and `windows64` is the `Platform_Bits` property. This property is only available in the full file. Because of the missing property in the lite or standard file, a match against a `windows64` rule would give the same result as the `windows` rule. For this reason the `windows64` rules are disabled in the lite or standard mode.

> Then how do you choose what is in which version, can't it be automatically determined by it's attributes or parent.

When a build is run, all output files are written at the same time. Writing these files one after another would require much more time, because a lot of time is required to validate the sources and expanding the versions, platforms and devices arrays.
Because we write all files at the same time, we should have always all properties available. We only remove properties with the same value as in the parent entry, but this is not version specific.
