### ISSUE TITLE
Galaxy A5 not in the DB?

### ISSUE THREAD

**Issue by negram** [browscap/browscap#1688]
Hey guys, this UA isn't matched, even by full version of DB. IT looks like it must be Samsung Galaxy A5 (2015)
`Mozilla/5 (Linux; Android 6; SM-A500W Build/MMB29M) AppleWebKit/537 (KHTML, like Gecko) Chrome/59 Mobile Safari/537`

**Comment by mimmi20** [comment]
This UA looks strange. Normal UAs have for example the Tokens `Mozilla/5.0` or `Chrome/59.0`, but here all the minor and micro versions are missing.

**Comment by negram** [comment]
Yeah, you're right. We internally cut out minor version.
Here are the 2 UAs I took from our request log:

`Mozilla/5.0 (Linux; Android 6.0.1; SM-A500W Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36`

`Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-A500W-parrot Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36`
