### ISSUE TITLE
Add Seznam Android

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1694]
While collecting some UAs for #1688 I noticed a couple of useragents that were detected as Android Webview but contained the "SznProhlizec" identifier (from Seznam browser).

>Mozilla/5.0 (Linux; Android 6.0.1; SM-A500FU Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 SznProhlizec/4.1.0a
Mozilla/5.0 (Linux; Android 6.0.1; SM-A500FU Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36 SznProhlizec/4.1.2a

I assume it's this: https://play.google.com/store/apps/details?id=cz.seznam.sbrowser&hl=en

I'll dig around in our logs some more to see if there are other formats, and what the version range looks like.

**Comment by mmorel-35** [comment]
Linked to #1640
