### ISSUE TITLE
Trying to add Galaxy S7 on Android 6,7

### ISSUE THREAD

**Issue by negram** [browscap/browscap#1727]
Hey folks,

I tried to ask in the forum but was directed with this question here.

So far I have three questions:
1. I have to create tests/issues/* file first. Does it mean that I should raise an issue first?
2. Is there a tool to create such entry? All files look pretty much the same
3. What's the right way to run regression tests, especially just added one? `phpunit --filter=issue-xxxx tests/` works not quite fast :(

**Comment by negram** [comment]
So far I added this way:
https://github.com/negram/browscap/commit/d2cd829f70b0347ccb0620e90a90f5302b34fc19

if everything is okay, I will make a pull-request

**Comment by mimmi20** [comment]
@negram 
> I have to create tests/issues/* file first.

No

> Does it mean that I should raise an issue first?

Please use the number of this issue.

> Is there a tool to create such entry?

No. Just copy another test and modify it.

> What's the right way to run regression tests, especially just added one?

Please look into the `.travis.yml` file for the stages `integration test`.

**Comment by negram** [comment]
> Please use the number of this issue.
Ok, thanks.
What about next time? I should open an issue each time, right?

**Comment by mimmi20** [comment]
> I should open an issue each time, right?

Its better that way.

**Comment by negram** [comment]
thanks! will try :)
