### ISSUE TITLE
browscap.org Cloudflare

### ISSUE THREAD

**Issue by theflu** [browscap/browscap#1729]
Once a month we would update Lite_PHP_Browscap.ini with curl via a cron. Now that Cloudflare was added we can no longer automatically update browscap.

**Comment by mimmi20** [comment]
What is the issue? You may download the file and copy it to your server.

**Comment by rrdd** [comment]
wget "http://browscap.org/stream?q=PHP_BrowsCapINI" is not possible cause of cloudfare. so you can not update automatically

**Comment by asgrim** [comment]
Duplicate of browscap/browscap-php#228
