### ISSUE TITLE
Change some patterns to fix some get_browser differences

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1755]
This is related to https://github.com/browscap/browscap-php/issues/179.

I ran a comparison on 50,000 useragents from our logs for November of 2017, which revealed ~1,100 useragents that didn't parse the same (!). Most of these were due to a couple of patterns in the Android Browser 4.0 and Android Webview 4.0 files that started with an asterisk. These patterns take priority in `get_browser` (if they're longer overall) but not in `browscap-php` (for reasons mentioned in the issue there). `get_browser` was parsing these useragents as a Mobile Phone device and `browscap-php` was parsing them as a Tablet (due to the lack of the `Mobile` keyword in the UA).

There were a couple of other ones (including a couple that were being mis-detected by `browscap-php`).

After making some minor changes, I was able to reduce the difference list to just 8 useragents. These 8 are probably un-fixable since they contain two different version strings in different places in the UA (this is discussed some in https://github.com/browscap/browscap-php/issues/179).

I have some tests to add, so will do that and attach them to this issue number.

**Comment by mimmi20** [comment]
> These patterns take priority in `get_browser`

This was the sorting strategy in v2 of browscap-php too.

**Comment by jaydiablo** [comment]
Yeah, and it's possible to change this in `browscap-php` 3.x (4.x too) but it does slow down the parser some, as I outlined in my tests in https://github.com/browscap/browscap-php/issues/179.

Overall modifying the patterns to reduce the differences is a band-aid, IMO, but I'm not sure the performance hit is worth fixing this (usually) minor issue.  The trick is keeping up on it and making sure the differences aren't major.
