### ISSUE TITLE
Emulated Internet Explorer 9 cannot be detected

### ISSUE THREAD

**Issue by nyon** [browscap/browscap#1769]
When using this list for detection of different Internet Explorer versions, it fails for an emulated Internet explorer 9 or 10. A *real* Internet Explorer 9 would send the following user agent:

    Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)

while an emulated one sends the following

    Mozilla/5.0(compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)

Note the missing space between `Mozilla/5.0` and `(compatible; ...`.

Is it possible to enhance this list to also detect the emulated Internet Explorer 9 and 10?

**How to reproduce:**

Open a *real* Internet Explorer 11 and press F12. Then go to the tab "Emulation" and set document mode and user agent string to Internet Explorer 9 or 10. Now the user agent, that is being sent to the web server, misses a space.

**See also:**

Used library: https://github.com/blueconic/browscap-java/issues/8

**Comment by asgrim** [comment]
Thanks @nyon for the detailed report.

@mimmi20 is this related #113 ?

**Comment by mimmi20** [comment]
@asgrim I dont think its related.
@nyon Could you tell us how do you emulate the IE? Can you edit the emulated UA?

**Comment by jaydiablo** [comment]
FWIW, my IE 11 does not do this.

![ie_11_9_emulation](https://user-images.githubusercontent.com/136907/34495856-49d47a98-efb4-11e7-96be-95f3ea141095.png)

![ie_11_10_emulation](https://user-images.githubusercontent.com/136907/34495859-4d7d3202-efb4-11e7-9dc0-4a189a7162d6.png)

Version info of IE:
>Version: 11.786.15063.0
>Update Versions: 11.0.49 (KB4052978)

This is on Windows 10:
> Version: 10.0.15063 Build 15063

**Comment by nyon** [comment]
Ok that is weird. I'll add more information + screenshots to reproduce my issue tomorrow. Thanks for the quick reply.

**Comment by nyon** [comment]
Version info of IE:

> Version: 11.786.15063.0
> Update Version: 11.0.49 (KB4052978)

Version info of Windows 10 (`ps> [System.Environment]::OSVersion`):

    Platform ServicePack Version      VersionString
    -------- ----------- -------      -------------
    Win32NT             10.0.15063.0 Microsoft Windows NT 10.0.15063.0

Additional information from "About":

* Edition: Windows 10 Enterprise
* Version: 1703
* OS Build: 15063.786
* System type: 64-bit operating system, x64-based processor

**Internet Explorer 11 (no-emulation):**

![image](https://user-images.githubusercontent.com/3247445/34510728-c9d367d4-f056-11e7-9ec7-33447842369e.png)

**Internet Explorer 10 (emulation):**

![image](https://user-images.githubusercontent.com/3247445/34510744-fe767a08-f056-11e7-8064-a9226ddbbcc4.png)

**Internet Explorer 9 (emulation):**

![image](https://user-images.githubusercontent.com/3247445/34510759-19b60f4a-f057-11e7-80c5-ae8ff1243f0f.png)

**Comment by mimmi20** [comment]
@nyon Which site did you use? I want to try this too.

**Comment by nyon** [comment]
http://whatsmyua.info/

**Comment by mimmi20** [comment]
I can not reproduce this.

![image](https://user-images.githubusercontent.com/1120192/34514792-4ff164f2-f06f-11e7-8ab7-982f29553869.png)

![image](https://user-images.githubusercontent.com/1120192/34514810-6a877f9a-f06f-11e7-93a0-9659ea3162a6.png)

**Comment by jaydiablo** [comment]
Yeah, doesn't do it for me on that site either.

The only difference I see between your version of IE/Windows is that you're on "Windows 10 Enterprise" (I'm on "Windows 10 Pro").  I can try downloading a Windows 10 Enterprise VM from Microsoft and see if that makes a difference.

Thanks for the screens and info, any other odd extensions you might have installed?

**Comment by nyon** [comment]
I deactivated all extensions, but it did not change anything (used `iexplore.exe -extoff`).

I analysed the network packages that the internet explorer sends to the given host. It contained the right user agent (with a space inbetween). 

![image](https://user-images.githubusercontent.com/3247445/34553672-1df3082e-f129-11e7-8f92-b0a9ae934ee6.png)


So I thought it must be some software fiddling with the user agent. When I visit https://www.whoishostingthis.com/tools/user-agent/, a site that is using SSL encryption and thus is not mangled by any software, is also showing the missing-space-behaviour.

![image](https://user-images.githubusercontent.com/3247445/34553683-32695bb4-f129-11e7-9670-509d98b6f152.png)


This is very odd. I don't know anything else I could test. I worked around this issue by simply inserting a space where it should be in our backend. 

Since this is very edge case and not a problem of this project itself, I would recommend to close this issue. If someone has any idea on how to debug this problem, I will appreciate it.

Anyways, thanks for all your help.

**Comment by jaydiablo** [comment]
Hmm, interesting, so it seems that it sends the right UA, but then removes the space in any website that outputs the UA?

I haven't been able to test that Windows 10 Enterprise VM yet, but I did search our logs and I couldn't find any hits with that style of useragent (with either emulated version) in the past 12 months (not that I'd expect to see many of our users emulating IE versions though).
