### ISSUE TITLE
User agent incorrect parsing

### ISSUE THREAD

**Issue by merlin-zaraza** [browscap/browscap#1778]
Next user agent is parsed incorrect: `Mozilla/5.0 (Linux; Android 5.0.1; G1 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36`

Browser version is parsed as `4.0`, but should be `30.0`

**Comment by jaydiablo** [comment]
In browscap, that useragent is parsed as `Android Webview` which uses the `Version/x.x` bit as the version number.

We could look at re-naming the ones that have `Chrome/xx` in them as `Chrome(ium) Webview` or something like that (which is what a lot of other parsers do: http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Linux%3B+Android+5.0.1%3B+G1+Build%2FKOT49H%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F30.0.0.0+Mobile+Safari%2F537.36) and then use the Chrome version number as the version number.

Thoughts @mimmi20 ?

The versions seem like they would mostly mirror the Chrome version (which is probably more informative than the old "Version/4.0" version number).

**Comment by mimmi20** [comment]
@jaydiablo We could change this.

**Comment by jaydiablo** [comment]
I can take a crack at this, should we name the browser "Chrome Webview"?

**Comment by mimmi20** [comment]
I dont know what the offitial name is. But "Chrome Webview" sounds fine.

**Comment by jaydiablo** [comment]
A lot of other UA parsers use "Chrome Webview" or "Chromium Webview", though I don't think that's the official name.

Here's the app on the Play Store as "Android System Webview": https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en (I don't think the most recent versions of Android, i.e. 7.0+, use this APK if Chrome is installed on the device: https://developer.android.com/about/versions/nougat/android-7.0.html#webview)

On Google's Chrome release blog they call it "Android WebView": https://chromereleases.googleblog.com/search/label/Android%20WebView

Google just calls it "WebView for Android" on this page: https://developer.chrome.com/multidevice/webview/overview

Similar here, "WebView on Android": https://developer.chrome.com/multidevice/user-agent#webview_user_agent

I was thinking to keep "Android WebView" for pre-4.4 Android and use "Chrome WebView" for everything after Android 4.4. I still have some research to do, but that's where I'm at right now.

**Comment by mimmi20** [comment]
> I was thinking to keep "Android WebView" for pre-4.4 Android and use "Chrome WebView" for everything after Android 4.4. I still have some research to do, but that's where I'm at right now.

We call it `Android Browser` for pre-4.4 Android.

**Comment by mimmi20** [comment]
@jaydiablo Did you start here?

**Comment by jaydiablo** [comment]
I did, it's been a while since I've touched it, but I did start moving UAs out of "Android Webview" and into "Chrome Webview".

**Comment by mimmi20** [comment]
@jaydiablo May I take over this issue?

**Comment by jaydiablo** [comment]
I could push my branch up, I haven't made a ton of progress, but may be a good starting point.
