### ISSUE TITLE
Missing Google Chrome V64

### ISSUE THREAD

**Issue by Cnwangli** [browscap/browscap#1787]
Hi 

current browsercap has missed Google Chrome V64 and V65 and it's the top #3 browser used by our customers...
Is there any ETA a new browsercap containing Chrome V64/65 can be released?

Some sample user agents from Chrome V64/65
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.51 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by jaydiablo** [comment]
Chrome 64 is in the current release of the browscap file (6027):

From http://browscap.org/ua-lookup

For your second UA in that list:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36`

field|value
---|---
browser_name_regex | /^mozilla\/5\.0 \(.*mac os x 10.13.*\) applewebkit.* \(.*khtml.*like.*gecko.*\) chrome\/64\.0.*safari\/.*$/
browser_name_pattern | mozilla/5.0 (*mac os x 10?13*) applewebkit* (*khtml*like*gecko*) chrome/64.0*safari/*
parent | Chrome 64.0
comment | Chrome 64.0
browser | Chrome
browser_type | Browser
browser_bits | 32
browser_maker | Google Inc
browser_modus | unknown
version | 64.0
majorver | 64
minorver | 0
platform | macOS
platform_version | 10.13
platform_description | macOS

And third:

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36`

field|value
---|---
browser_name_regex | /^mozilla\/5\.0 \(.*windows nt 10\.0.*wow64.*\) applewebkit.* \(.*khtml.*like.*gecko.*\) chrome\/64\.0.*safari\/.*$/
browser_name_pattern | mozilla/5.0 (*windows nt 10.0*wow64*) applewebkit* (*khtml*like*gecko*) chrome/64.0*safari/*
parent | Chrome 64.0
comment | Chrome 64.0
browser | Chrome
browser_type | Browser
browser_bits | 32
browser_maker | Google Inc
browser_modus | unknown
version | 64.0
majorver | 64
minorver | 0
platform | Win10
platform_version | 10.0
platform_description | Windows 10

Chrome 65 **is not** in the current browscap file, but was added in this commit: https://github.com/browscap/browscap/commit/7d3bd6621e6ebbd722de1c236750e252098bf014#diff-05c494b5188a12170327619fb9f47d8c So will be in the next release of the file (6028).

**Comment by Cnwangli** [comment]
Hi Jay,

Thank you for the update!

I'm a bit confused, I thought Chrome V64 was released from Jan 25th 2018
according to Chrome release notes ( and start showing in the traffic
capturing of our website )
6027 was released Dec 27th 2017
How come 6027 would include V64?
Is there any ETA for 2028 to be released?

Thank you so much!

Michelle

**Comment by jaydiablo** [comment]
@Cnwangli The first beta release of Chrome 64 on Windows/Mac/Linux was on December 14th, 2017 (https://chromereleases.googleblog.com/2017/12/beta-channel-update-for-desktop_14.html) and actually, 64 was available in the "Dev Channel" since October of 2017 (https://chromereleases.googleblog.com/2017/10/dev-channel-update-for-desktop_27.html).

We try to keep the major browsers (Chrome/Firefox/Opera/Safari) a version or two ahead of the "Stable" release to account for users that are on Beta/Dev channels, and also so the browscap file doesn't have to be updated so much.

There's not a set schedule for browscap releases, but usually they're a couple of months apart depending on how many changes are ready to go and when @asgrim has time to put a release together. 🙂

**Comment by Cnwangli** [comment]
Hi Jay,

Good to know browsercap is ahead of major browsers' official releases.
One more questions if you don't mind, is there a way I can subscribe to a
mail list and be notified whenever a new browsercap is released?

Thanks!

Michelle

**Comment by asgrim** [comment]
@Cnwangli I'm afraid at the moment we don't have a mail list or anything. 

Maybe subscribing to the `releases.atom` for the project might help? https://github.com/browscap/browscap/releases.atom
