### ISSUE TITLE
Silk does not detect version

### ISSUE THREAD

**Issue by hadoopbob** [browscap/browscap#1805]
given the user agent string
Mozilla/5.0 (Linux; Android 5.1.1; KFARWI Build/LVY48F) AppleWebKit/537.36 (KHTML, like Gecko) Silk/62.6.1 like Chrome/62.0.3202.84 Safari/537.36

get results of:
browser: Silk
browserMajorVersion: 0
deviceType: Ebook Reader
platform: Android

the version should be 62.6

**Comment by jaydiablo** [comment]
62.6 (and some other missing Silk versions) were added in this commit: https://github.com/browscap/browscap/commit/7d3bd6621e6ebbd722de1c236750e252098bf014#diff-bc91601d527e58cf98a9ad8450e19cde

They'll make their way into the next browscap release (6028).

Thanks!
