### ISSUE TITLE
remove versions from Vivaldi Browser

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1811]
Vivaldi 1.14 uses UA `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.170 Safari/537.36 Vivaldi/1.95.1077.50`.

The released version and the version in The UA do not match. For this reason the versions for Vivaldi shall be removed.

**Comment by jaydiablo** [comment]
Apparently the reason for this is because some systems were detecting Vivaldi "1.10" as "1.1":

![screen shot 2018-02-18 at 10 14 11 am](https://user-images.githubusercontent.com/136907/36354636-51c339fc-14cf-11e8-86a6-c4d00b68b413.png)

From: https://vivaldi.com/blog/minor-update-to-vivaldi-1-10/

**Comment by mimmi20** [comment]
I dont see a way to handle this in browscap.

**Comment by jaydiablo** [comment]
Could probably be done in a version-less file and define the UA version in the match directly, and the actual browser version in the properties:

```json
{
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Vivaldi/1.95.*Safari/*",
          "properties": {
              "MajorVer": "1",
              "MinorVer": "14"
          },
          "platforms": [
            "Win10_x64_B", "Win10_64_B", "Win10_32_B",
            "Win10_x64", "Win10_64", "Win10_32",
            "Win8_1_x64", "Win8_1_64", "Win8_1_32",
            "Win8_x64", "Win8_64", "Win8_32",
            "Win7_x64", "Win7_64", "Win7_32",
            "Vista_x64", "Vista_64", "Vista_32",
            "WinXPb_64", "WinXPb_32",
            "WinXPa_64", "WinXPa_32"
          ]
        },
```

Of course, would have to do this with every pattern, and every version since we can't make use of the version expansion past version 1.10 (or whenever they decided to start doing this convention).
