### ISSUE TITLE
Indent in json files

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1821]
In this project a lot of json files are used.

In the `user-agents` and the `core` directories these files have an indent of 2 spaces.
In the `browsers` and `devices` directories these files have an indent of 4 spaces.

The json files should use the same indent all over the project. Which one is prefered?

**Comment by jaydiablo** [comment]
I'm probably more used to 2 spaces in the user-agents resource files than the 4 spaces in devices/browsers files.

I think since the user-agents files can be nested a fair amount, 2 spaces may be better to minimize horizontal scrolling.

**Comment by mimmi20** [comment]
@jaydiablo I would like to convert the test cases (expect the two "invalid" files) into the json format too. Do you dislike this idea?

**Comment by mimmi20** [comment]
@jaydiablo @asgrim I would like to convert the test cases (expect the two "invalid" files) into the json format too. Do you dislike this idea?

**Comment by asgrim** [comment]
I don't care what indent is used as long as it's consistent. Can we use a tool to automate this or verify consistency in CI?

**Comment by mimmi20** [comment]
Yes. I added a command for this and put it into the build matrix for travis.
