### ISSUE TITLE
Possible ordering issue?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1836]
I saw this issue come up in Crossjoin:  https://github.com/crossjoin/Browscap/issues/38

And I can replicate with Crossjoin 2 &  3 (Crossjoin 1 seems to be unaffected).

## Crossjoin  2:
>Processing update...
>
>In Writer.php line 389:
>
>  Parent 'UC Browser 8.9 for WinPhone' not found.

## Crossjoin 3:
>Processing update...
>
>In Writer.php line 357:
>
>  Parent 'UC Browser 8.9 for WinPhone' not found.

I was curious if that parent exists in the Full file, and it seems to, but possibly out of order?

>ack -H  "UC Browser 8.9 for WinPhone" ./Full_PHP_BrowscapINI
>./Full_PHP_BrowscapINI
>251829:Parent="UC Browser 8.9 for WinPhone"
>251839:Parent="UC Browser 8.9 for WinPhone"
>252287:[UC Browser 8.9 for WinPhone]
>252289:Comment="UC Browser 8.9 for WinPhone"

**Comment by mimmi20** [comment]
The caching strategy from Crossjoin v1 is similar to the one browscap-php is using.
Crossjoin changed its caching in v2/3.

Aside from the caching the ordering in the generated files is a mess, because too much files have the same sortIndex.

**Comment by jaydiablo** [comment]
In this case, why does the parent line "[UC Browser 8.9 for WinPhone]" get inserted after lines that have that as the defined parent?

None of the JSON files use eachother as the parent (all define "default Properties" as the parent), so is this an issue with the file builder rather than the sort index of the JSON files?

**Comment by craftpip** [comment]
Can anyone please provide a hot fix for this for the time being, my development server is stuck,

**Comment by asgrim** [comment]
@craftpip what exactly are you stuck on? This isn't exactly a big issue from what I can tell...

**Comment by craftpip** [comment]
@asgrim 
I get the error
```
Parent 'UC Browser 8.9 for WinPhone' not found.
```
when i run
```php
$browser_detect = new \Crossjoin\Browscap\Browscap();
$browser = $browser_detect->getBrowser();
```
Which is the entry code on the website.

**Comment by asgrim** [comment]
I see. Well, pull requests welcome, remember we work on this in our free time, so if you need it fixed urgently feel free to submit a patch, thanks! :)

**Comment by beppejo** [comment]
If you want I have the correct file v6000028 for all the version "... for WinPhone" from 8.0 to 8.9 and idem for "Nokia ... for Symbian"" 8.0-8.9.
[full_php_browscap 6000028 (03 Mar 2018) corretto.zip](https://github.com/browscap/browscap/files/1823008/full_php_browscap.6000028.03.Mar.2018.corretto.zip)

**Comment by jaydiablo** [comment]
I built an INI file from #1839's changes, and ran the CrossJoin update process against it, and it worked fine, so seems those changes will fix this issue.

**Comment by mimmi20** [comment]
@jaydiablo Could you check, if the error is gone after the last release today?

**Comment by jaydiablo** [comment]
I was able to successfully update Crossjoin 1/2/3 against version 6.0.29 of the files, so I believe this is resolved.
