### ISSUE TITLE
The UA "MOBILE ANDROID 3.1.1" AND "LGE Nexus 5/6.0.0" cann't parse exactly

### ISSUE THREAD

**Issue by weiyongyuan** [browscap/browscap#1837]
Thanks to your reply.I‘m prepare use browscap to analyze uses's UA.So i test some UA with browscap."MOBILE ANDROID 3.1.1" AND "LGE Nexus 5/6.0.0" are  the ua of two app in my country ,china, http://browscap.org/ua-lookup also doesn't work correctly. Here is my test result,i just return the following BrowsCapField:
browser=Default Browser
browserType=Default Browser
browserMajorVersion=Unknown
deviceType=Unknown
platform=Unknown
platformVersion=Unknown
fake=Unknown
IS_CRAWLER=Unknown
In my thingking,deviceType shoud be mobile,platform shoud be android,and version is 3.1.1. I don't know if my thougnt is right.

**Comment by mimmi20** [comment]
@weiyongyuan Please add the useragents you tested.

**Comment by weiyongyuan** [comment]
"MOBILE ANDROID 3.1.1" AND "LGE Nexus 5/6.0.0" are the two useragents i tested.if you give me your email,i can send other useragents to you.It's too many.

**Comment by asgrim** [comment]
@weiyongyuan please put them in a gist or something.

Also, are they the full user agents? They don't look like real devices...?

**Comment by weiyongyuan** [comment]
yes,when i intercept the request with fiddler,the ua is just that.The next week I can list some of other ua in our database.

**Comment by mimmi20** [comment]
@weiyongyuan Any news?

**Comment by mimmi20** [comment]
@asgrim May we clode this issue?

**Comment by asgrim** [comment]
Yeah - if @weiyongyuan can come back with the UA list in a gist we can always re-open! :+1:
