### ISSUE TITLE
Xiaomi Redmi Note 4 default browser

### ISSUE THREAD

**Issue by dmytro-pe** [browscap/browscap#1838]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/53.0.2785.146 Safari/534.24 XiaoMi/MiuiBrowser/9.4.10

**Comment by mimmi20** [comment]
This UA has no device information.

Please check if you enabled the `Desktop mode`.

**Comment by dmytro-pe** [comment]
Looks like you right. Thank you.
