### ISSUE TITLE
syntax error on line 57

### ISSUE THREAD

**Issue by Dubz** [browscap/browscap#1842]
PHP:  syntax error, unexpected $end, expecting ']' in /etc/php.d/browscap.ini on line 57

Just pulled the latest version from the website and I'm getting this when running scripts from cli.

**Comment by mimmi20** [comment]
@Dubz Do you use the native `get_browser` function?

**Comment by Dubz** [comment]
I do for the main site I'm building, but the test script I run in CLI doesn't use it or anything else.

I made a new "Hello world" file, two lines. First is the opening tag, and the second is an echo command. Still shows this error on the CLI after I execute it.

**Comment by Dubz** [comment]
Added lite version for better performance, similar error:

PHP:  syntax error, unexpected $end, expecting ']' in /etc/php.d/lite_php_browscap.ini on line 38
PHP:  syntax error, unexpected $end, expecting ']' in /etc/php.d/php_browscap.ini on line 57

**Comment by jaydiablo** [comment]
@Dubz What version of PHP are you using?

And could you attach the `lite_php_browscap.ini` file that is causing the error?

I tried duplicating with a fresh build of the full file, but didn't run into the issue in my php version (7.2).

**Comment by Dubz** [comment]
The lines being mentioned are the following:

php_browscap.ini (38): `[Mozilla/4.0 (compatible; MSIE ?.0; *Windows NT 5.1*; StumbleUpon.com*]`
lite_php_browscap.ini (57): `[Mozilla/5.0 (SMART-TV; X11; Linux armv7l) applewebkit* (*khtml*like*gecko*) Chromium/65.*Chrome/*Safari/*]`

[php_browscap.zip](https://github.com/browscap/browscap/files/1868076/php_browscap.zip)

**Comment by mimmi20** [comment]
@Dubz To me it looks like you are using the browscap file via the native get_browser function and  the `browscap` property in the php.ini. Did you restart your server after updating the file?

**Comment by Dubz** [comment]
Yes, that is correct. I have tried reloading, restarting, and rebooting the server itself (for other reasons, but its been restarted since).

**Comment by Dubz** [comment]
For reference, I was using PHP v5.6 at the time and I am now using PHP v7.2.
Both are having this issue and I just updated the files (and PHP) today.

**Comment by mimmi20** [comment]
@Dubz A new browscap file was released today. Could you check if the error is gone?

**Comment by Dubz** [comment]
@mimmi20 I downloaded all three versions and the errors still show up. I believe the issue may pertain to them being installed in "/etc/php.d/" and trying to be loaded there. I'm not sure what the best place would be to put them, I just saw this location online for placing them and adding the line to php.ini

Is there an alternative place you'd recommend to put them? I'm not using composer to install it, as it is being installed on the server and not via a specific package.

**Comment by EvilKarter** [comment]
I have exactly the same problem. 
As suggested I moved my browsecap.ini to an other directory and updated my php.ini file but the error is the same.

My current test script to update the browsecap.ini looks like this: 
wget -O /etc/php.d/browscap.ini "https://browscap.org/stream?q=PHP_BrowsCapINI"

**Comment by Dubz** [comment]
@EvilKarter You can't put it in /etc/php.d/ you need to choose another location. Your update script is downloading it back to that folder. Change the command to save it elsewhere, delete the files out of /etc/php.d/ and edit your php.ini to point to where the files are saved.

Side note, PHP v7 seems to process get_browser a whole lot faster than v5. The full version file will run a lot quicker on 7 than the lite did on 5. Just something to keep in mind if your environment can handle upgrading to 7 (scripts compatible, etc).

**Comment by jaydiablo** [comment]
>Side note, PHP v7 seems to process get_browser a whole lot faster than v5. The full version file will run a lot quicker on 7 than the lite did on 5. Just something to keep in mind if your environment can handle upgrading to 7 (scripts compatible, etc).

Specifically the performance improvement is in PHP 7.0.15+ and 7.1.1+, anything earlier is really slow.

**Comment by mimmi20** [comment]
@Dubz Do you still have this issue?

**Comment by mimmi20** [comment]
@jaydiablo May we close this issue?

**Comment by Dubz** [comment]
@mimmi20 I'm sure it would be fine if I moved it, just never got around to picking a new path to install it to.

**Comment by jaydiablo** [comment]
I assume this has been resolved. Closing.

**Comment by sjcrookes** [comment]
I know this is a bit late, but this page comes up when searching for this error in Google, so hopefully it's still relevant for someone to find the right answer.

<b>/etc/php.d/</b> or <b>/etc/php*/conf.d/</b> is the location for loading php extensions. <b>NOT</b> for putting the browscap.ini database!

There is nothing wrong with the format of the browscap.ini database, you are putting it in the wrong place.

## The correct way to load browscap.ini is:

1. Download the browscap database into a common location EG:
```
wget -O /etc/browscap_php.ini https://browscap.org/stream?q=PHP_BrowsCapINI
```

2. Establish your browscap extension config file, EG:
```
cat <<EOT >/etc/php/8.4/mods-available/browscap.ini
[browscap]
; http://php.net/browscap
browscap = /etc/browscap_php.ini
EOT
```

3. Symlink the browscap extension config to your running config, EG:
```
ln -sn /etc/php/8.4/mods-available/browscap.ini /etc/php/8.4/fpm/conf.d/browscap.ini
```

4. Restart your PHP service if required
