### ISSUE TITLE
Chrome 66.0

### ISSUE THREAD

**Issue by ransom85** [browscap/browscap#1849]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.66 Safari/537.36

**Comment by jaydiablo** [comment]
This was just added yesterday: https://github.com/browscap/browscap/commit/c55b1426f8519bc308b6814908fda2856ca78fc3#diff-05c494b5188a12170327619fb9f47d8cR3 and will be in the next release of the browscap files (6.0.29).
