### ISSUE TITLE
Firefox 60.0

### ISSUE THREAD

**Issue by ransom85** [browscap/browscap#1850]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by jaydiablo** [comment]
This was just added yesterday: https://github.com/browscap/browscap/commit/c55b1426f8519bc308b6814908fda2856ca78fc3#diff-106a5587c93991de9fade2f14e69445aR3 and will be in the next release of the browscap files (6.0.29).

**Comment by asgrim** [comment]
This is working as of today - 6.0.29 is on the site, thanks for the patience in waiting for the update :+1:
