### ISSUE TITLE
Invalid version numbers for Firefox variation

### ISSUE THREAD

**Issue by quackdor** [browscap/browscap#1857]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:60.0) Gecko/20100101 Firefox/60.0
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1

Version numbers are all matched to "0"

**Comment by mimmi20** [comment]
Firefox did not release a version `40.1`.

**Comment by jaydiablo** [comment]
For the `60.0` version, that was just added recently (https://github.com/browscap/browscap/commit/2f9466bda2a84a5ca5ae330ba6df923041092b11#diff-106a5587c93991de9fade2f14e69445aR3) and will be in the next release of browscap.
