### ISSUE TITLE
UCBrowser and UCBrowser Mini

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1860]
I installed the UCBrowser and the UCBrowser Mini on my Nokia 6.

If I run the UCBrowser Mini in the Speed Mode I get the the useragent:
`UCWEB/2.0 (MIDP-2.0; U; Adr 7.1.1; en-US; TA-1021) U2/1.0.0 UCBrowser/11.1.2.1113 U2/1.0.0 Mobile`.

If I run the Browser not in Speed Mode I get the useragent:
`Mozilla/5.0 (Linux; U; Android 7.1.1; en-US; TA-1021 Build/NMF26F) AppleWebKit/528.5+ (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1 UCBrowser/11.1.2.1113 Mobile`.

Both useragents are detected as `UC Browser`.

When using the UCBrowser I get the useragent:
`Mozilla/5.0 (Linux; U; Android 7.1.1; en-US; TA-1021 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.0.0.1088 Mobile Safari/537.36`.

Should the `UCWEB/*` and the Safari like rules moved to the UCBrowser Mini?

**Comment by jaydiablo** [comment]
I think it would be nice if this was accurate, as long as it seems like it's easy enough to differentiate UC Browser from UC Browser Mini (and this is consistent).

FYI, there apparently is no "Mini" version of UC Browser on iOS.
