### ISSUE TITLE
Chrome 66

### ISSUE THREAD

**Issue by Crash58** [browscap/browscap#1861]
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

**Comment by dmarek** [comment]
BROWSER_MAJOR_VERSION is parsed incorectly as 0

CapabilitiesImpl [myValues={BROWSER=Chrome, BROWSER_TYPE=Browser, BROWSER_MAJOR_VERSION=0, PLATFORM=Win10, PLATFORM_VERSION=10.0, DEVICE_TYPE=Desktop}]]

```
<dependency>
	  <groupId>com.blueconic</groupId>
	  <artifactId>browscap-java</artifactId>
	  <version>1.2.2</version>
</dependency>
```

**Comment by mimmi20** [comment]
see issue #1849.

**Comment by asgrim** [comment]
This is working as of today - 6.0.29 is on the site, thanks for the patience in waiting for the update :+1:
