### ISSUE TITLE
Missing Chrome V66

### ISSUE THREAD

**Issue by Cnwangli** [browscap/browscap#1863]
eg:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Is there any ETA a new browscap with Chrome V66 will become availalbe?

Thank you so much!

**Comment by mimmi20** [comment]
see issue #1849.

**Comment by asgrim** [comment]
This is working as of today - 6.0.29 is on the site, thanks for the patience in waiting for the update :+1:
