### ISSUE TITLE
Chrome v66 - win10 - 64bits. Nor present in v6000028 (3rd may 2018)

### ISSUE THREAD

**Issue by roque-lpgc** [browscap/browscap#1864]
Hi,

With version 6000028 of browscap, the 3rd of May of 2018, Chrome 66 is not detected correctly.

I manually changed the INI file so it works correctly for my needs, but i wonder if theres a procedure to publicly add/suggest a new version of a browser when its been a while in the wild and hasent been added to browscap.

Thanks.

**Comment by mimmi20** [comment]
see issue #1849.

**Comment by asgrim** [comment]
This is working as of today - 6.0.29 is on the site, thanks for the patience in waiting for the update :+1:
