### ISSUE TITLE
No version information for Firefox 60.0

### ISSUE THREAD

**Issue by thornberger** [browscap/browscap#1877]
Firefox 60.0 doesn't create a version information:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0`

`
version | 0.0
majorver | 0
minorver | 0
`

Using browsecap 6000028 (latest)

**Comment by mimmi20** [comment]
see #1850.

**Comment by asgrim** [comment]
This is working as of today - 6.0.29 is on the site, thanks for the patience in waiting for the update :+1:
