### ISSUE TITLE
Some UAs marked as `crawler` that weren't before?

### ISSUE THREAD

**Issue by georgeholt** [browscap/browscap#1880]
We use Browscap to filter out robots from our analytics. A couple weeks ago when our Browscap DB updated we started noticing a sharp increase in the number of robots being recognised. I looked through our analytics data to find that a slew of user agents that were previously identified as not being a robot, now in fact were.

Here are a few examples of user agents that are now being filtered out that weren't before:

```
stagefright/1.2 (Linux;Android 4.1.2)
Stitcher/Android
stagefright/1.2 (Linux;Android NexPlayer LG-P71310c-ZAF-XX)
Pocket Casts
Samsung GT-N7100 stagefright/1.2 (Linux;Android 4.4.2)
PodcastAddict/v2 - Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-J105F Build/LMY47V)
```

Were these entries intentionally changed so that they identify as crawlers? The only way I've found to fix the issue ourselves is to also look at the `browser_type` field, but that fields doesn't exist on the standard version of the DB, which is the version we use.

**Comment by mimmi20** [comment]
Which version of browscap do you use now? Which version of browscap did you use before the update?

The `crawler` property is deprecated since at least a year now. We recommend to use the `browser_type` property instead.

**Comment by mimmi20** [comment]
@asgrim @jaydiablo Which browser types should be marked as `Bot`?

**Comment by georgeholt** [comment]
@mimmi20 Our DB updates every Sunday, and is currently running version 6000029 as of May 28. Unfortunately I'm not 100% sure what the previous version was, but we haven't seen anything to suggest the autoupdate failed at all.

As I mentioned in my OP, we use the standard DB, which doesn't include the `browser_type` field. Wasn't aware that the `crawler` field had been deprecated, good to know, but that kinda makes the lite and standard DBs useless for our needs :<

**Comment by mimmi20** [comment]
@georgeholt The property will not be removed so far.

**Comment by mimmi20** [comment]
@asgrim @jaydiablo Should we add `browser_type` to the standard mode?

**Comment by jaydiablo** [comment]
These all look like `Multimedia Player` which I don't think should be marked as a crawler.

As for `browser_type`, if we ever want to remove `iscrawler` from the Standard file, seems like we'd have to add `browser_type`.
