### ISSUE TITLE
Differentiate between "0" version and no version?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1888]
I was curious if something like this would be helpful.

In browscap, there are basically two types of "0" versions for browsers/apps.

When a version isn't defined for a browser that browscap does define versions for, the "generic" patterns typically pick these up, where the version is set to "0".  I think this is fine, and can be a good way to find useragents that are either using an invalid version, or help identify versions that need to be added to browscap.

There's also the browsers/apps that browscap doesn't define version information for, like Facebook app for example.  These will also be marked as a "0" version, but perhaps it's better if these get flagged in a different way, to make it easier to identify the browsers/apps that browscap doesn't (or can't) collect version information for.

This would certainly make it easier for me when I'm scanning for UAs to use to update browscap's version numbers.  Currently I have to maintain a list of browser names that browscap doesn't identify version information on.

I was thinking that `null` would be the most appropriate, but `n/a` could possibly work too.

There would be BC breaks to consider as well, as most clients are probably expecting a numeric value.

Thoughts?

**Comment by mimmi20** [comment]
For unknown platform or engine versions we use `unknown`.

**Comment by mimmi20** [comment]
The same issue exists with the properties `cssversion`, `aolversion`, `browser_bits` and `platform_bits`.

**Comment by mimmi20** [comment]
This may cause issues in browscap-php because there is a validation too.

**Comment by asgrim** [comment]
I guess this is really a question for consumers; do they care about the distinction?

Would indeed be quite a BC break I think too :/
