### ISSUE TITLE
Wiki / 

### ISSUE THREAD

**Issue by olivier-monaco** [browscap/browscap#1905]
Hi,

In the Wiki page [Resource: User Agents Database](https://github.com/browscap/browscap/wiki/Resource%3A-User-Agents-Database), section "Schema Reference", subsection "User Agent object reference", the "device" property is missing.

The same problem exists for the "#DEVICE#" tag in "Tags reference" and its linked property "devices" in "Children object reference".

Regards,

Olivier

**Comment by mimmi20** [comment]
@asgrim I added the Browser database in the Wiki and the missing information. Could you look about it?

**Comment by asgrim** [comment]
Nice, thanks @mimmi20 :+1:
