### ISSUE TITLE
K-Meleon Browser not detecting properly

### ISSUE THREAD

**Issue by siva-subramaniam-wdfc** [browscap/browscap#1910]
Hi Team,

First of all thanks a lot for this awesome plug-in. Appreciate your work.

Recently I came across a browser called K-Meleon which I want to detect. Browscap is reporting it incorrectly as Firefox. Following are the user agents that I came across with the K-Meleon browser.

**Mozilla/5.0 (Windows NT 6.2; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0 K-Meleon/75.1** - On a Windows 10 OS
**Mozilla/5.0 (Windows NT 6.2; WOW64; rv:31.0) Gecko/20100101 K-Meleon/75.1** - On a Windows 10 OS
**Mozilla/5.0 (Windows NT 5.2; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0 K-Meleon/75.1** - On a Windows XP OS

I quickly looked into the browscap source code and found the K-Meleon json file in the following [location](https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/k-meleon/k-meleon.json)

I think there is an issue with matching the platform in the file above. As you can see from the user-agent strings that I have provided, I have **platform** values that is not present in the json file in the repo.

Is there any work-around for this issue so that browscap correctly identifies K-Meleon as K-Meleon instead of reporting it as Firefox? Please help.

Thanks,
Siva

**Comment by siva-subramaniam-wdfc** [comment]
Hi @mimmi20 Thanks for the response. I am using Browscap as a Drupal plugin.
Drupal version: 6.38
Browscap version: 6.x
I understand your question regarding the windows system. But I used K-Meleon in a Windows 10 system.
Please let me know if you need more details.
Thanks,
Siva

**Comment by jaydiablo** [comment]
I just downloaded the latest test version of the browser, and here's the UA (on a Windows 10 system):

>Mozilla/5.0 (Windows NT 6.2; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0 K-Meleon/76.0

The lastest stable version also does the same thing (also on Windows 10):

>Mozilla/5.0 (Windows NT 6.2; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0 K-Meleon/75.1

Unfortunately there's not a way to differentiate the true windows version if the UA of the browser won't tell us what it actually is.

**Comment by siva-subramaniam-wdfc** [comment]
Hi @jaydiablo Thanks for the reply. Yeah I agree. But my issue is, browscap should identify the above UA string as K-Meleon browser. Instead it is reporting it as Firefox browser.

**Comment by jaydiablo** [comment]
@siva-subramaniam-wdfc I agree, I just don't think we'll be able to make it detect it as Windows 10 with that UA.
