### ISSUE TITLE
Add support for Whale browser

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1917]
see ua-parser/uap-core#334 for more details

**Comment by jaydiablo** [comment]
Whale (Desktop) was added here: https://github.com/browscap/browscap/commit/54aff504adf5fdce4f0533c0fd3ca882198fc898#diff-556d4cf2c8ee8280fcfbc434d28f3e57

Looks like there's a mobile version now though, this UA comes from UAP's tests (from the PR you linked to):

>Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Whale/0.9.1.679 Mobile/15D100 Safari/604.5.6

I'll dig a bit in our logs and see if I can find the Android UA (or see if I can install on my Android VM), I'll also download the browser (if possible) on my iOS device and confirm the UA.

**Comment by jaydiablo** [comment]
I've confirmed the iOS UA on my device:

>Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Whale/0.9.1.679 Mobile/15G77 Safari/605.1.15

I wasn't able to get the Android version to run on my VM and didn't see any hits from such a UA in our logs yet.

There's an OSX/macOS version of the browser as well, here's the UA for that one:

>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.220 Whale/1.3.50.3 Safari/537.36

OSX 10.10 or later.
