### ISSUE TITLE
Add Android 9 and iOS 12

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1919]
Android 9 was released in the last days, iOS has its 6. Beta now. We should add them.

**Comment by jaydiablo** [comment]
They've both been added already:

https://github.com/browscap/browscap/blob/master/resources/platforms.json#L3943
https://github.com/browscap/browscap/blob/master/resources/platforms.json#L1774

but not in a released file yet.

**Comment by mimmi20** [comment]
I did not see that.
