### ISSUE TITLE
top user agents from logs

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1953]
see matomo-org/device-detector#5803 for more information

**Comment by mimmi20** [comment]
[agents.txt](https://github.com/browscap/browscap/files/2369704/agents.txt)

List without count numbers.

**Comment by lord-alfred** [comment]
Maybe you will be interested ;-)
New portion of the past tense.

https://github.com/matomo-org/device-detector/issues/5803#issuecomment-427484551
