### ISSUE TITLE
Add Waterfox Android

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#1956]
Noticed this UA being detected as Firefox:

>Mozilla/5.0 (Android 7.0; Tablet; rv:55.0) Gecko/55.0 Firefox/55.2.0 Waterfox/55.2.0

Waterfox Project does have an Android version apparently:

https://www.waterfoxproject.org/en-US/waterfox/android/
https://play.google.com/store/apps/details?id=org.waterfoxproject.waterfox

Android 5+.  I'll try to confirm the UA on my Android VM.

**Comment by jaydiablo** [comment]
Unfortunately it crashes on my Android VM, so I can't verify the UA.

There's also an iOS version (https://itunes.apple.com/gb/app/waterfox-browser/id994141194?mt=8) but I confirmed that the UA for that one is just a generic Safari Webview UA.

**Comment by jaydiablo** [comment]
Also, as of Waterfox 56.2.3 (desktop) the UA format has changed, here's from my mac:

>Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0; Waterfox) Gecko/20100101 Firefox/56.2.3

I'll tackle that as well.

**Comment by mimmi20** [comment]
I have a Beta installed on my Phone. It is based on Firefox 50 and does not have the `Waterfox` token in the UA.

**Comment by jaydiablo** [comment]
I've tried several other emulators on my PC, but couldn't get them to install Waterfox (all say "Your device isn't compatible with this version" when I try to install from Google Play).

Should I still add the Android patterns even though we can't confirm the UA?

**Comment by mimmi20** [comment]
Yes.
