### ISSUE TITLE
List of useragents not recognized by BrowsCap

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#1957]
Hi, 

Our product BlueConic is using BrowsCap for some time now, and it's working great for us. 
Because we process a lot of requests every day. we are seeing clients which are not recognized by BrowsCap.
I could file a separate request for all of these, but that might not scale well.

I can deliver a CSV file with user agents not recognized, on a regular basis. Please let me know if that is helpful.

Example of such a CSV file is attached.
Thanks in advance and keep up the good work!

[Possible_bots_sept_17.csv.txt](https://github.com/browscap/browscap/files/2387711/Possible_bots_sept_17.csv.txt)

**Comment by mimmi20** [comment]
@paulrutter Please remove everything expect the useragents from the file. Please do not quote them.

**Comment by paulrutter** [comment]
Hi @mimmi20,

Fixed, although the quotes in this case are part of the useragent string (not added by ourselves).
[Possible_bots_sept_17_edit.csv.txt](https://github.com/browscap/browscap/files/2387751/Possible_bots_sept_17_edit.csv.txt)

**Comment by mimmi20** [comment]
@paulrutter If you have more undetected useragents, please open a new Issue.
