### ISSUE TITLE
Detecting Opera54

### ISSUE THREAD

**Issue by SpenserJulia** [browscap/browscap#1970]
i found that Opera detected as Chrome

` UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.60`

**Comment by mimmi20** [comment]
@SpenserJulia Which version of Browscap are you using?

**Comment by SpenserJulia** [comment]
[GJK_Browscap_Version]
Version=6000030
Released=Tue, 14 Aug 2018 09:20:40 +0000
Format=php
Type=FULL

**Comment by mimmi20** [comment]
Opera 54 is defined in that file. Could you add a code sample for your implementation?

**Comment by mimmi20** [comment]
>UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.60

Is the token `UA: ` part of the useragent?
