### ISSUE TITLE
Use git tag date for `GJK_Browscap_Version`.`Released` date

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#2000]
Currently we just use the current date/time for making the `Released` date:

```ini
[GJK_Browscap_Version]
Version=6000030
Released=Fri, 26 Oct 2018 12:54:15 +0100
```

Ideally we should use the date of the git tag for `6.0.30` so the date is always consistent, e.g.:

```ini
[GJK_Browscap_Version]
Version=6000030
Released=Tue Aug 14 09:03:56 2018 +0000
```

Also the date should be adjusted for UTC.

**Comment by mimmi20** [comment]
How does this library know when it was released?

**Comment by asgrim** [comment]
The git tag ;)

**Comment by mimmi20** [comment]
For the Build the version is set from outsite. Should the date also set from outside?

**Comment by asgrim** [comment]
Ideally we should do away with any manual build labelling and switch to using git tags now. I'll have a dig around some other projects I have as I've got some code lying around that'll detect the last git tag etc and we can derive the date from that :)

**Comment by mimmi20** [comment]
In my opinion the version and the date should set from outside (from the project which triggers the build). e.g the `browscap-file` project should easily know which tag of browscap it is using and should be able to find out the date of that tag.

In my opinion browscap itself does not need to know this, it should build the current set of data to ini files.

**Comment by asgrim** [comment]
Did you mean "browscap-site"? :)

I do like the idea of the library being able to determine itself what build number/date we should be building. It's a property/attribute of THIS rather than something outside.

Otherwise you could checkout tag 6.0.30, but call it "6000031" by accident (or on purpose even) even though `6.0.31` doesn't exist as a tag, and the date would always be the "current" date...

**Comment by asgrim** [comment]
This issue is going to crop up if we merge browscap/browscap-site#49 interestingly. It will still be the same version `6000034` served up, but the date will be updated to today's date.

**Comment by asgrim** [comment]
Currently:

> The latest version is 6000034 (1st Jul 2019)

 (which reminds me, I should probably do another release! :grin: )

**Comment by asgrim** [comment]
@mimmi20 used your suggestion of providing the generation date externally, and I'll determine the release date from `composer.lock` (PR #2164 created)
