### ISSUE TITLE
Missing PingdomPageSpeed user agent

### ISSUE THREAD

**Issue by allie** [browscap/browscap#2031]
**Version**: 6000031, PHP full
**Method**: browscap/browscap-php
**Missing user agent**: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/61.0.3163.100 Chrome/61.0.3163.100 Safari/537.36 PingdomPageSpeed/1.0 (pingbot/2.0; +http://www.pingdom.com/)`

The user agent comes from page speed tests originating from [tools.pingdom.com](https://tools.pingdom.com).

**Comment by allie** [comment]
I don't mind adding this one myself, but I need some quick clarification—would `browscap/resources/user-agents/crawlers/site-monitors/pingdom.json` be the correct place to add it? Thanks!

**Comment by mimmi20** [comment]
@allie I dont think that file is right place. Please add the new bot inside the `seo-analytics` directory. If you dont want to add a new file there, add the bot to the generic `seo-analytics.json` file.
