### ISSUE TITLE
Looking for database for useragents of media players

### ISSUE THREAD

**Issue by kleinadam** [browscap/browscap#2039]
Hi all,

maybe someone can help me with some links. 

I am looking for databases/services similar as WURLF/browscap/etc. but not for browser user agent strings but for media players. 

What I mean with media player useragents, e.g.
iTunes/12.3.1 (Windows; Microsoft Windows 7 x64 Business Edition Service Pack 1 (Build 7601); x64) AppleWebKit/7603.3008.0.3  --> iTunes 

NSPlayer/12.0.7601.17514 -> Microsoft Media Player

Nullsoft Winamp3 version 3.0 (compatible) --> Winamp

Since years we do our own media player user agent interpretations (for player statistics) but maybe there are some services on the web? Any recommendations?  

Thanks a lot in advance. 

Regards,
Adam

**Comment by asgrim** [comment]
Browscap has the iTunes and Microsoft Media Player UA strings you have, we're missing the Winamp one though. You'd do a lookup using the library (php or other language - see the wiki for language libaries), and it looks like you want the `browser` key

**Comment by kleinadam** [comment]
Thanks a lot asgrim, I will do some tests. 

Any idea why "Alexa" is defined as Mobile Phone [device_type]? Maybe "Smart Home" device would be the better type. 

Which devices-types are output by browscap? Mobile Phone, Desktop, Tablet, unknown? Any more? 

Regards, Adam

**Comment by kleinadam** [comment]
I would as well recommend device_types like "home entertainment" (Bose, Yamaha) - these are so called network (radio) receiver (user agents).

**Comment by mimmi20** [comment]
@kleinadam If you have useragents for Alexa and the home entertainment systems, please provide them.

**Comment by mimmi20** [comment]
> Which devices-types are output by browscap? Mobile Phone, Desktop, Tablet, unknown? Any more?

- Car Entertainment System
- Console
- Digital Camera
- Ebook Reader
- Mobile Device (e.g. iPod)
- TV Device

**Comment by kleinadam** [comment]
Here some UA from a typical Icecast Server media server log. 

The second column is what we are reading out of it (Just "player name") Third and fourth column is what browscap is putting out. 

You will find "Bose" (Sound system) as UA for home entertainment. 
[mediapplayer-useragents.zip](https://github.com/browscap/browscap/files/2775923/mediapplayer-useragents.zip)


Let me know, if you need more or other infos.

**Comment by mimmi20** [comment]
@kleinadam Did you limit the length of the Uas in your list? Could you create a Ua list like this (`zcat ~/path/to/access/logs* | awk -F'"' '{print $6}' | sort | uniq -c | sort -rn | head -n20000 > /home/matomo/top-user-agents.txt`)?

**Comment by kleinadam** [comment]
Hi Thomas, your provided regex does not fit my logs, I just get a number as result in the output file. Here a raw logfile with 2 lines, the values are separated by blank, due I use urlencoded strings inside. Hope that helps. 
[2019-01-22_XXXXX-X_stream.log](https://github.com/browscap/browscap/files/2788221/2019-01-22_XXXXX-X_stream.log)

**Comment by kleinadam** [comment]
Can someone explain how I can change global output (for all users) or let say only for my local cache the results browscap is putting out for certain UAs? Example: I am not happy to get "Amazon / Alexa / Echo" as a Mobile Phone. A mobile phone is for media people a smartphone. Each UA containing Alexa/Amazon should belong let say to "Smart Home" or "Home Entertainment" but not be defined as mobile phone. 

As I can see, browscap is a text-file, same informations are repeating 1000-times. I there a way to go for a database structure?
