### ISSUE TITLE
Recommended corrections

### ISSUE THREAD

**Issue by kleinadam** [browscap/browscap#2041]
I have started to use browscap on our Media Player UA (from webradio hosting customers), here some correction issues: 
"Lavf/" standalone (e.g. Lavf/57.25.100 ) is not "Windows Media Player". 
Lavf is only in combination with NSPlayer/ really Windows Media Player. 

Lavf standalone should be "unknown" as ->browser, it is used in several application, like FFMEG and it is used often in older Android Apps.  As browser_type it is LIB/SDK, a part of an application. 

Nullsoft Winamp3 version 3.0 (compatible) is missing --> WinAmp
Note hat Winamp3 as well as WinAmp/2.x are often fakes, StreamRippers, etc.. 

Alexa is defined as Mobile Phone. Alexa is let say "Smart Home / Virtual Assistant". UAs with "Echo" are as well Alexa. (Echo /Echo Dot ist the so-called "Smart Speaker" Hardware.

Regards, Adam

**Comment by mimmi20** [comment]
@kleinadam Could you add some useragents for Winamp, alexa and Echo?

**Comment by kleinadam** [comment]
Here we go:

WinampMPEG/2.8
WinampMPEG/2.7
WinampMPEG/x.y
Nullsoft Winamp3
AlexaMediaPlayer/2.0.204008.0 (Linux;Android 7.1.2) ExoPlayerLib/1.5.9
Echo/1.0(APNG)
Alexa\/
Echo\/

Is there somewhere written what are the differences in FULL and Default INI-File? Ist Default limit to a special date, let say not before IE6 or what is advantage of FULL list?

**Comment by mimmi20** [comment]
> Is there somewhere written what are the differences in FULL and Default INI-File? Ist Default limit to a special date, let say not before IE6 or what is advantage of FULL list?

There is nothing written about this. The standard version has no device properties, and some browser versions are removed.

**Comment by kleinadam** [comment]
What are device properties? Does Default INI contain and output devices types (desktop, tablet, smpartphone) or not, means all unknown?

**Comment by kleinadam** [comment]
--> "AvsDeviceSdk/" is Alexa as well (Alexa Voice Service Device SDK)

**Comment by mimmi20** [comment]
@kleinadam 
> "AvsDeviceSdk/"

Is this the complete useragent? If not, please add the the complete useragents. This is required for testing.

**Comment by mimmi20** [comment]
@kleinadam 
> What are device properties?

Please look into [this](https://github.com/browscap/browscap/blob/b478c04c88564621ec47942e29caa70e666648f0/src/Browscap/Data/PropertyHolder.php#L126)
and 
[this](https://github.com/browscap/browscap/blob/b478c04c88564621ec47942e29caa70e666648f0/src/Browscap/Data/PropertyHolder.php#L163) function. These properties are available in the standard mode.

**Comment by kleinadam** [comment]
The UA on media players / webradio apps are not so in detail as you know it from browsers. 

Here the full UA from raw log: 
AvsDeviceSdk/1.10.0

**Comment by kleinadam** [comment]
here some more examples of typical Media player UAs:

Karadio/1.5
SA-MP/0.3

So I just google for it, to get full name and then I try to define device type, desktop, general mobile or something else. In the last years a lot of so-called network receivers has been established, they have strange UA, they us the device model label as UA: 

if (preg_match("/^TX-NR|^CR-N|^HT-R/i", $player)) 
return $output = array("Onkyo Receiver", 7);

**Comment by mimmi20** [comment]
> Alexa/

@kleinadam Please add the complete useragent

**Comment by mimmi20** [comment]
> SA-MP/0.3

@kleinadam Is `Grand Theft Auto: San Andreas` using your media server? Or belongs the UA to a dirrent App?

**Comment by mimmi20** [comment]
> if (preg_match("/^TX-NR|^CR-N|^HT-R/i", $player))

@kleinadam Please add useragnets for this regex.
