### ISSUE TITLE
Firefox version 65 returns version 0.0

### ISSUE THREAD

**Issue by macady** [browscap/browscap#2042]
Just upgraded to latest Firefox on Windows 10, and lite_asp_browscap.ini file doesn't correctly recognize Firefox version 65.0 as being > version 47.  The User Agent Lookup page reports the 
<img width="851" alt="screen shot 2019-01-29 at 6 34 56 pm" src="https://user-images.githubusercontent.com/23364864/51947943-a17fa400-23f4-11e9-90d7-995e2f2bff65.png">
version as 0.0.

**Comment by mimmi20** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
