### ISSUE TITLE
Difference between Device_Type=Mobile Device and Device_Type=Mobile Phone

### ISSUE THREAD

**Issue by pcomans** [browscap/browscap#2063]
Hi, I'm trying to figure out what the difference is between the `Mobile Device` and `Mobile Phone` `Device_Type`. To me it looks like they are used interchangeably for phone browsers. In testing it seems like Android devices get categorized as `Mobile Device` and iOS devices as `Mobile Phone`.

What's the distinction between these device types?

**Comment by mimmi20** [comment]
A `Mobile Phone` is a device which can do phone calls, A `Mobile Device` can't do this.
Do you have any samples/useragents?

**Comment by pcomans** [comment]
Thank you for clarifying @mimmi20. The UA in question is `Mozilla/5.0 (Linux; Android 8.0; Pixel 2 Build/OPD3.170816.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Mobile Safari/537.36`.

I am using a pretty old version of browscap lite (6012) so that's probably the reason for the miscategorization. It looks like the latest version of browscap categorizes this device correctly as `Mobile Phone` per https://browscap.org/ua-lookup.

Feel free to close this issue.
