### ISSUE TITLE
Mistaken classification in issues #1828 and #1846

### ISSUE THREAD

**Issue by yoniiny** [browscap/browscap#2075]
I've recently written an implementation of the browscap library, and I'm getting two spec failures:

issue-1828-00058:
`Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; ###842854534364284829315431###; Browsezilla; .NET CLR 1.1.4322)`
Should be parsed as `Mozilla/4.0 (compatible; MSIE 6.0*; *Windows*`
Actually parsed as `Mozilla/4.0 (compatible; MSIE 6.0*; *Windows*98*`

issue-1846-EH:
`Mozilla/5.0 (compatible; MSIE 8.0; compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; .NET4.0E; .NET4.0C; InfoPath.3; Trident/6.0)`
Should be parsed as `Mozilla/5.0 (compatible; MSIE 8.*Windows NT 6.1*Trident/6.0*)*`
Actually parsed as `Mozilla/5.0 (compatible; MSIE 8.0; *Windows NT 6.1*Trident/5.0*)*`

In both cases, the actual pattern is longer than the expected one. In the first case, it seems like a better fit, and I would say is probably a bug in the spec?
In the second case, what makes the parser decide to use the expected pattern? It looks like the second one is a better fit, since it's more specific. Maybe this is a bug in the patterns themselves?

**Comment by mimmi20** [comment]
First, if you dont use a native implementation for reading the browscap.ini files which exists for PHP and ASP, you have to convert the rules from the ini files to regexes. These regexes need to be sorted to work better.

There are two major sorting rules for the regexes.
* 1. The length from the start to the first wildcard (`*` or `?` converting to the regex). Longer is better.
* 2. The length of the rule without wirdcards. Longer is better.

Where did you find these sample useragents? Why do you thinks, the detection is wrong?

**Comment by yoniiny** [comment]
These sample user agents are from the specs in this project:
https://github.com/browscap/browscap/blob/master/tests/issues/issue-1828.php line 529
https://github.com/browscap/browscap/blob/master/tests/issues/issue-1846.php line 6327

The first spec expects the result to be `Mozilla/4.0 (compatible; MSIE 6.0*; *Windows*`, but the pattern `Mozilla/4.0 (compatible; MSIE 6.0*; *Windows*98*` also matches, and is longer.
The second spec expects the result to be `Mozilla/5.0 (compatible; MSIE 8.*Windows NT 6.1*Trident/6.0*)*`, but the pattern `Mozilla/5.0 (compatible; MSIE 8.0; *Windows NT 6.1*Trident/5.0*)*` also exists and is also longer, and length from the start to the first wildcard is longer.

So in both cases according to the match order, the other pattern (not the one expected in the specs) should match. Am I missing something?

**Comment by mimmi20** [comment]
No, you are right.

Could you tell us, why do you expect the other pattern to match?

**Comment by yoniiny** [comment]
In the first case, the user agent is
`Mozilla/4.0 (compatible; MSIE 6.0; Windows 98; ###842854534364284829315431###; Browsezilla; .NET CLR 1.1.4322)`
The pattern I expect to match is 
`Mozilla/4.0 (compatible; MSIE 6.0*; *Windows*98*`
and not
`Mozilla/4.0 (compatible; MSIE 6.0*; *Windows*`
Because it's longer.

In the second case, the user agent is
`Mozilla/5.0 (compatible; MSIE 8.0; compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; .NET4.0E; .NET4.0C; InfoPath.3; Trident/6.0)`
The pattern I expect to match is
`Mozilla/5.0 (compatible; MSIE 8.0; *Windows NT 6.1*Trident/5.0*)*`
And not
`Mozilla/5.0 (compatible; MSIE 8.*Windows NT 6.1*Trident/6.0*)*`
Again, because it's longer. In this case, the user agent has both Trident/5.0 and Trident/6.0 in it, so it hits both patterns.

**Comment by mimmi20** [comment]
@yoniiny You found errors in our lib. We have to fix both patterns.

**Comment by mimmi20** [comment]
> I've recently written an implementation of the browscap library

Could you add your implementation [here](https://github.com/browscap/browscap/wiki/Using-Browscap)?

**Comment by yoniiny** [comment]
Sure, I just need to finish wrapping it up and I'll add a link. It's a high performance implementation for Scala.
