### ISSUE TITLE
Samsung Tab A 8.0 incorrectly shows as a smartphone

### ISSUE THREAD

**Issue by lloydmurray** [browscap/browscap#2093]
similiar to #2033 , but for android 8.1.x

Mozilla/5.0 (Linux; Android 8.1.0; SM-T380) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36

detects as

device_name | general Mobile Phone
device_maker | unknown
device_type | Mobile Phone
device_pointing_method | touchscreen
device_code_name | general Mobile Phone
in 6000032

Can we make the fix for #2033 generic to the android version?

**Comment by mimmi20** [comment]
> Can we make the fix for #2033 generic to the android version?

No. If you do that, you won't detect the android version.
