### ISSUE TITLE
Chrome 74 not recognized

### ISSUE THREAD

**Issue by mtarajosarc** [browscap/browscap#2095]

**Comment by mtarajosarc** [comment]
Chrome 74 is out and is not being recognized. Tried browscap.org site and the following user agent string is not decoded 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

**Comment by natesreich** [comment]
Would it be possible to future-proof Chrome for upcoming versions?

**Comment by jaydiablo** [comment]
@natesreich the way that browscap works, it's not really possible to have it detect all possible future versions of a browser (the versions have to be defined in the files that are used to build the INI file).

Usually there are a couple of "future" chrome versions added to the files to deal with this, but I think everybody just got busy between the last update, so those versions haven't been updated as frequently as they usually are.
