### ISSUE TITLE
Platform Version iOS 12.2 and 12.3 is not detected

### ISSUE THREAD

**Issue by rubincroy** [browscap/browscap#2097]
Platform Version iOS 12.2 and 12.3 is not getting detected

**Comment by mimmi20** [comment]
@rubincroy Please add a useragent for each version.

**Comment by jaydiablo** [comment]
In #2100 I've added iOS 12.2 and 12.3 to a lot of different useragents, but yes, would be nice to know exactly which UAs you're seeing so we can be sure to update those browsers/apps as well.

**Comment by rubincroy** [comment]
Chrome mobile IOS: 
Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/71.0.3578.89 Mobile/15E148 Safari/605.1

Safari:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

Firefox:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/14.0b12646 Mobile/16D39 Safari/605.1.15
