### ISSUE TITLE
Missing Google Chrome V74 and V75

### ISSUE THREAD

**Issue by detay** [browscap/browscap#2103]
Hi, 
looks like the latest release 6000033 (15th May 2019) still missing Chrome V74 and V75.

Google Chrome New Version 75.0.3770.80

Looking forward to your new version...

Thanks.

**Comment by mimmi20** [comment]
@detay Please add a useragent

**Comment by detay** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
