### ISSUE TITLE
New bots

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#2126]
see matomo-org/device-detector#5953 for more details

**Comment by qqqaq** [comment]
Hello, missing this user agent from google bot 

Mozilla/5.0 (Linux; Android 5.0; SM-G920A) AppleWebKit (KHTML, like Gecko) Chrome Mobile Safari (compatible; AdsBot-Google-Mobile; +http://www.google.com/mobile/adsbot.html)

https://support.google.com/webmasters/answer/1061943?hl=es
