### ISSUE TITLE
iOS bits

### ISSUE THREAD

**Issue by ibmua** [browscap/browscap#2128]
Generally speaking,
`browser_bits`
and
`platform_bits`
for iOS devices should now be 64.

Thanks for your work, btw!

**Comment by jaydiablo** [comment]
I think as of iOS 11.0 32-bit apps aren't supported any longer and have to be upgraded to support 64 bit OS.

https://developer.apple.com/documentation/uikit/app_and_environment/updating_your_app_from_32-bit_to_64-bit_architecture
https://www.macworld.com/article/3163248/the-future-of-ios-is-64-bit-only-apple-to-stop-support-of-32-bit-apps.html

So probably safe to bump anything iOS 11.0+ to 64 bit for the platform bits...  browser_bits is probably trickier, I forget if the platform can override the browser in the data files or not.
