### ISSUE TITLE
remove versions from Instagram App, Pinterest App and Snapchat App

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#2144]
Like the Facebook App, I want to remove the versions from Instagram App, because I see no benefit for this version at the moment.

Because the Pinterest App on iOS shows no version, I want to remove the versions from the Android App too.

**Comment by mimmi20** [comment]
@jaydiablo @asgrim Please comment.

**Comment by jaydiablo** [comment]
+1 from me, Instagram releases a lot of new versions, and yes, there's no real benefit to keep up on that.

**Comment by jaydiablo** [comment]
I think Snapchat could probably be added to this list as well.
