### ISSUE TITLE
browscap not able to pick up platform version for iOS 12.4 device

### ISSUE THREAD

**Issue by benmak11** [browscap/browscap#2156]
Hi,

For this userAgent String:
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

I am unable to get the platform version of my iOS device from the Capabilities object that is returned after parsing... The platformVersion that is set is "Unknown". Seems to only affect iOS 12.4 but any release prior seems to work just fine.

Could we get more information about when this will be addressed?

**Comment by jmeattle** [comment]
Relates to https://github.com/browscap/browscap/issues/2129
