### ISSUE TITLE
Add Samsung phone SMS link preview

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#2157]
We get a lot of this UA from people on mobile networks:

>Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0

It's clearly too much volume to really be Firefox 24 on Ubuntu (and from users being on mobile networks, it doesn't make a lot of sense that it would be a desktop linux browser).

Did some googling, and found other people on StackOverFlow discussing the exact same UA (originally posted more than a year ago): https://stackoverflow.com/questions/48068227/details-on-user-agent-mozilla-5-0-x11-ubuntu-linux-i686-rv24-0-gecko-2010

It seems the UA is used by Samsung phones when fetching a preview for links that are sent in SMS messages. It would be nice if browscap identified this UA properly, instead of Firefox on Ubuntu.

The users' devices are making the requests, but the users themselves aren't actually triggering the request (this is done automatically when the message is viewed in the SMS app). I believe there are other UAs in browscap like this, I just don't recall if they end up getting marked as a bot/crawler or not.

**Comment by npscode** [comment]
Yes, i am also getting same UA in my server access logs as well. Not sure if i can block these UA at firewall / ACL layer. What i found is these hits are coming from messenger Apps while showing preview to user.

I hope these are not genuine user clicks.
