### ISSUE TITLE
permanent unban 

### ISSUE THREAD

**Issue by vchebotarev** [browscap/browscap#2159]
Hello. 
We suppose our server 92.53.82.182 was permanently banned
How is it possible to unban us ?

**Comment by asgrim** [comment]
Hi Vladimir,

I have checked both our website ban logs, and any blocks on CloudFlare, but
I couldn't find that IP address.

What response do you received? I suspect you are getting intercepted by
CloudFlare's verification page.

Thanks
James

**Comment by vchebotarev** [comment]
@asgrim 
And what about these `95.213.201.142` `95.213.220.93`  ?

**Comment by asgrim** [comment]
Hi Vladimir,

Yes, surprisingly I found both those IP addresses in our ban log. It's not
often IPs make it in there any more as Cloudflare tends to block most
malicious traffic. Please make sure you're not trying to download too
often; it's really not necessary to check multiple times per day - even
just once a day is fine.

Thanks
James
