### ISSUE TITLE
UserAgent: Safari 13 is missing 

### ISSUE THREAD

**Issue by psathishcs** [browscap/browscap#2163]
Safari 13 is missing  in the latest version rowscap-java.  version 1.2.11

 Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/13.0 Mobile/14D27 Safari/602.1

**Comment by jaydiablo** [comment]
Safari on iOS is only available on iOS 13: https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes

>Safari 13 ships with iOS 13 and macOS 10.15. It’s also available for macOS 10.14.5 and 10.13.6.

It's not possible to update the Safari version independently of the iOS version.  The UA you provided is most likely spoofed.
