### ISSUE TITLE
Firefox 69 returning version 0.0

### ISSUE THREAD

**Issue by fabiomtl** [browscap/browscap#2171]
browscap.ini (6000035) using Classic ASP
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

![Browser Capabilities Project](https://user-images.githubusercontent.com/11317969/67044879-934cf180-f103-11e9-9a63-0649c015c952.png)

**Comment by jaydiablo** [comment]
This version was added in #2167 and will be available in the next release of browscap.

**Comment by asgrim** [comment]
Suppose I'd better do a release, thanks for the ping! :)
