### ISSUE TITLE
Suggestion: Correcting Samsung browser's name

### ISSUE THREAD

**Issue by ianthedev** [browscap/browscap#2173]
Instead of using an informal name "Samsung Browser", I suggest using the browser's official name "Samsung Internet".

**Comment by mimmi20** [comment]
@ianthedev Could you open a PR?

**Comment by ianthedev** [comment]
> @ianthedev Could you open a PR?

Do you mean fork, modify, and open a pull request? I'm not sure if the modification would be just a simple "find and replace" or involve other things. Please let me know.
