### ISSUE TITLE
Google Lighthouse mobile version

### ISSUE THREAD

**Issue by p4trizio** [browscap/browscap#2174]
While testing my website on https://developers.google.com/speed/pagespeed/insights/ I noticed that useragent 

Mozilla/5.0 (Linux; Android % Build/%) applewebkit%(%khtml%like%gecko%) Chrome/% Mobile Safari/% Chrome-Lighthouse

has ismobiledevice set to false

I think it should be set to true

**Comment by mimmi20** [comment]
@p4trizio Are there really these `%` in the useragent? If not, please add the real useragent.

**Comment by p4trizio** [comment]
Hi @mimmi20 the useragent is

Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse

**Comment by joeyhub** [comment]
There's another issue of this at top about both agents going to desktop. It looks like the mobile pattern is there already but just missing the device type property override.
