### ISSUE TITLE
Missing UA: Binance App

### ISSUE THREAD

**Issue by drexlma** [browscap/browscap#2176]
Binance/X.X.X (com.binance.mac-client; build:XX; OS X XX.XX.XX) Alamofire/X.X.X
https://www.binance.com/en/support/articles/115003777132

**Comment by mimmi20** [comment]
@drexlma Is this the real useragent?

**Comment by drexlma** [comment]
yes

**Comment by asgrim** [comment]
The user agent is literally: `Binance/X.X.X (com.binance.mac-client; build:XX; OS X XX.XX.XX) Alamofire/X.X.X` ?? I think @mimmi20 was asking for a real user agent example....
