### ISSUE TITLE
Google PageSpeed Insights User Agent missing device_type

### ISSUE THREAD

**Issue by mikeytag** [browscap/browscap#2191]
There's a popular web page speed tool put out by Google called PageSpeed Insights. The tool hits pages with 2 different user agents:

Mobile Phone
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Mobile Safari/537.36 Chrome-Lighthouse

Desktop
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3694.0 Safari/537.36 Chrome-Lighthouse

Browscap libraries currently return unknown values for pretty much everything in the device_ prefix, but I think that it should be detected as device_type Mobile Phone and Desktop. We use browscap to figure out what experience to show to any individual browser, and our Mobile scores look terrible in PageSpeed Insights because it's scoring the heavier Desktop experience.

I'm not sure if this is the right place to talk about enriching user agent detection in the library, but if not, feel free to point me in the right direction.

**Comment by joeyhub** [comment]
This might be fixed with this (plus the incoming commits): https://github.com/browscap/browscap/issues/2174

Otherwise currently there appear to be two patterns that look like they match those user agents but both just point to the same parent without one overriding the device type.

**Comment by mikeytag** [comment]
Thanks @joeyhub I think it will be fixed by that issue. Thanks for following up.
