### ISSUE TITLE
Optimised JSON data file...

### ISSUE THREAD

**Issue by joeyhub** [browscap/browscap#2196]
The current JSON file double encodes properties and escapes slashes.

For example:

> `"gooblog\/*": "{\"Parent\":\"gooblog\"}",`

Could be:

> `"gooblog/*": "{"Parent":"gooblog"}",`

The escaping is a PHP default because it assumes the JSON might go into script and it prevents this from breaking:

> `<script>var json = "</script>";</script>`

The JSON data file however isn't something that would normally go into a script tag but if so it would be on the user, particular if for example they load the JSON with node then emit a part of it back out to script with `JSON.stringify` the slashes would be removed.

I usually use this for relatively clean and unassuming JSON: `JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES`. The escape slashes is not intended for backend JSON.

The double encoding is a bit more tricky. It's a side effect of keeping properties on one line.

```php
<?php

$flags = JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES;
$data = [
  'comments' => ['line 1', 'line 2'],
  'GJK_Browscap_Version' => ['Version' => '0', 'Released' => 'Never'],
  'pattern/test1' => ['key' => 'value'],
  'pattern/test2' => ['key' => 'value']
];

if(isset($argv[1])) {
  $data = json_decode(file_get_contents($argv[1]), true);

  foreach($data as &$value)
    if(is_string($value))
      $value = json_decode($value, true);

  unset($value);
}

$json = "{\n";
$last = array_key_last($data);

foreach($data as $key => $value) {
  if($key === 'comments')
    $json .= '  "comments": ' . str_replace("\n]", "\n  ]", json_encode($value, JSON_PRETTY_PRINT | $flags));
  elseif($key === 'GJK_Browscap_Version')
    $json .= '  "GJK_Browscap_Version": ' . str_replace("\n}", "\n  }", json_encode($value, JSON_PRETTY_PRINT | $flags));
  else
    $json .= '  ' . json_encode($key, $flags) . ': ' . json_encode($value, $flags);

  if($key !== $last)
    $json .= ',';

  $json .= "\n";
}


$json .= "}";

echo $json;
```

The benefits of this are:

* Smaller, albeit is only slightly, data file.
* More human readable data file.
* Simpler and faster to parse.

I've considered that might be some other purpose to the double encoding as as deferred deserialize for entries but it seems unlikely.

This wouldn't be something advisable to do too quickly as it would break compatibility for people downloading the data automatically.

**Comment by asgrim** [comment]
@joeyhub I'm not sure what you're asking here, all you've done is made a statement. There is no bug here, you are not asking for a new feature.

> For example:
> 
> > `"gooblog\/*": "{\"Parent\":\"gooblog\"}",`
> 
> Could be:
> 
> > `"gooblog/*": "{"Parent":"gooblog"}",`

Unfortunately, this is not valid JSON.

**Comment by joeyhub** [comment]
> "gooblog/*": {"Parent":"gooblog"}

Should be that.

> The current JSON file double encodes properties and escapes slashes.

This causes the file to be larger, less easy on the eye and more complicated to parse than necessary.

The feature is a format change that would improve the file.

The script is an example that converts to that format.

**Comment by mimmi20** [comment]
The properties are not double quoted, they are converted to strings. This was made to reduce memory consumption during processing. Only properties for enties which are matched for the current useragent are de-stringified and merged.

**Comment by joeyhub** [comment]
I suspected that could be the case though thought just legacy was more likely. I'd describe that as implementation specific.

The actually implementation agnostic data files are in this repository which I didn't expect to be so different from the combined files.

I probably should have used those from the start as I take the JSON and turn it into something completely different with a similar toolset to what the set of scripts here appear to be doing.
