### ISSUE TITLE
Missing HUAWEI Webview

### ISSUE THREAD

**Issue by wordlesswind** [browscap/browscap#2198]
```
Mozilla/5.0 (Linux; Android 10; MRX-AL09 Build/HUAWEIMRX-AL09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.64 Safari/537.36
```
I don't know if this UA without its own identity can be recorded, but I decided to report it.
It is reported that Huawei devices that are still being updated will transition from Google Android System Webview to HUAWEI Webview.

**Comment by mimmi20** [comment]
Do you have any information about the affected Android versions or devices?

**Comment by wordlesswind** [comment]
Many people claim that HUAWEI Webview has been built into the device since Huawei Honor 9X, so I have listed this device and the devices since then.

### HUAWEI
- SPN-AL00, SPN-TL00 (HUAWEI nova 5i Pro)
- STK-AL00, STK-TL00 (HUAWEI Enjoy 10 Plus)
- VRD-W09 (HUAWEI MediaPad M6 8.4 Wi-Fi)
- VRD-W10 (HUAWEI MediaPad M6 8.4 Turbo Wi-Fi)
- VRD-AL09 (HUAWEI MediaPad M6 8.4 LTE)
- VRD-AL10 (HUAWEI MediaPad M6 8.4 Turbo LTE)
- SCM-W09 (HUAWEI MediaPad M6 10.8 Wi-Fi)
- SCM-AL09 (HUAWEI MediaPad M6 10.8 LTE)
- YAL-L21, YAL-L61, YAL-L71, YAL-L61D (HUAWEI nova 5T)
- TAS-L09, TAS-L29, TAS-AL00, TAS-TL00 (HUAWEI Mate 30)
- TAS-AN00, TAS-TN00 (HUAWEI Mate 30 5G)
- LIO-L09, LIO-L29, LIO-AL00, LIO-TL00 (HUAWEI Mate 30 Pro)
- LIO-N29, LIO-AL10, LIO-TL10 (HUAWEI Mate 30 Pro 5G)
- LIO-N29, LIO-AN00P (HUAWEI Mate 30 RS Porsche Design)
- ART-TL00, ART-AL00 (HUAWEI Enjoy 10)
- AQM-AL00, AQM-TL00 (HUAWEI Enjoy 10S)
- SPN-AL00, SPN-TL00 (HUAWEI nova 5z)
- MRX-W09, MRX-W19 (HUAWEI MatePad Pro Wi-Fi)
- MRX-AL09, MRX-AL19 (HUAWEI MatePad Pro LTE)
- WLZ-AL10, WLZ-TL10 (HUAWEI nova 6)
- JNY-AL10, JNY-TL10 (HUAWEI nova 6 SE)
- WLZ-AN00 (HUAWEI nova 6 5G)

### Honor
- HLK-AL00,STK-LX1 (Honor 9X)
- HLK-AL10,HLK-TL10 (Honor 9X PRO)
- ASK-AL00x, ASK-TL00x (Honor Play 3)
- KSA-AL10 (Honor Play 3e)
- YAL-AL50 (Honor 20S)
- LRA-AL00 (Honor 20 Lite)
- OXF-AN00 (Honor V30)
- OXF-AN10 (Honor V30 PRO)
