### ISSUE TITLE
Firefox 72.0 is detected as version 0.0

### ISSUE THREAD

**Issue by gregnolle** [browscap/browscap#2213]
As the subject says, Browscap is detecting the version of Firefox 72 as 0.0.

**Comment by mimmi20** [comment]
@gregnolle Please add a useragent.

**Comment by nbraun** [comment]
UA according to https://browscap.org/ua-lookup is:

`Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0`
