### ISSUE TITLE
Detect just Major version of Silk and Opera

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#2220]
Amazon's Silk browser is a modified Chrome browser, they stay in-sync with Chrome for the major version, but add minor versions with each release.

It's sort of a pain to keep up with the minor version releases, and if browscap misses a minor version, it's detected as version `0.0` instead of at least the major version.

I'd like to propose that the minor version is dropped from silk, and just the major version is defined and detected. The minor version doesn't provide much information.

**Comment by jaydiablo** [comment]
Opera Mobile is another one of these browsers that release a lot of minor versions...

**Comment by jaydiablo** [comment]
@mimmi20 any thoughts on this? I can roll the change into a version update I’m working on.

**Comment by mimmi20** [comment]
We can do this, I think.
