### ISSUE TITLE
Class 'JsonClass\Json' not found  

### ISSUE THREAD

**Issue by sciprok** [browscap/browscap#2221]
Trying to run the standard build with the latest pull, but running into this error. I last did a build in September last year... did something change that I missed or did I break something on my machine? Any suggestions welcome!

```
[2020-02-01 19:25:51] browscap.ERROR: Uncaught Exception Error: "Class 'JsonClass\Json' not found" at /Users/***/browscap/src/Browscap/Data/Factory/DataCollectionFactory.php line 331 {"exception":"[object] (Error(code: 0): Class 'JsonClass\\Json' not found at /Users/***/browscap/src/Browscap/Data/Factory/DataCollectionFactory.php:331)"} []
[error] Uncaught Exception Error: "Class 'JsonClass\Json' not found" at /Users/***/browscap/src/Browscap/Data/Factory/DataCollectionFactory.php line 331

In DataCollectionFactory.php line 331:
                                    
  Class 'JsonClass\Json' not found  
```
                        
I'm running:
PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

**Comment by asgrim** [comment]
Did you run `composer install`?

**Comment by sciprok** [comment]
Thank you! That did it, there were tons of updates and new installs. I've added to my build script to always check. Will close this out.

**Comment by asgrim** [comment]
Thanks!
