### ISSUE TITLE
Chrome 80 not properly identified

### ISSUE THREAD

**Issue by quackdor** [browscap/browscap#2224]
Example UAs: 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36

**Comment by Freeshnik** [comment]
One more example of Chrome 80:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36

**Comment by paulrutter** [comment]
Can't these predictable major browsers be added for several versions in advance?
I have checked a few Chrome agents for example, and the only thing changing usually is

Chrome/80.0

I would really help to have a few of these regular expressions in place for future versions to come.
