### ISSUE TITLE
Solved: Wrong device_type and device_pointing_method

### ISSUE THREAD

**Issue by tachtler** [browscap/browscap#2232]
Hi,

user-agent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15`

`device_type` is desktop should be `tablet`
and 
` device_pointing_method ` is mouse should be `touch`

Thank you!
Klaus.

**Comment by mimmi20** [comment]
@tachtler This is an Desktop Useragent. Did you use an iPad? This sends the Desktop Useragent by default. If you want to change this, you may read [this page](https://forums.developer.apple.com/thread/119186).

**Comment by tachtler** [comment]
Hi mimmi20,

yes you're right, it's an iPad. I will check that tomorrow and report here.

Thank you for the link!

Klaus.

**Comment by tachtler** [comment]
Hi mimmi20,

thank you again, the settings on the iPad Settings -> Safari -> Request Desktop Website -> All websites solved my problem.

Now the user agent was:
`Mozilla/5.0 (iPad; CPU OS 13_2_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1 `

Greetings
Klaus.
