### ISSUE TITLE
Smudge Error

### ISSUE THREAD

**Issue by GouravIN** [browscap/browscap#2233]
Getting the following error: 

git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)
git version 2.1.4

$ git-lfs smudge -- app-new/config/browscap.ini
Error downloading object: app-new/config/browscap.ini (ba81f69): Smudge error: Error downloading app-new/config/browscap.ini (ba81f6956fa350f2837ec9d3b61842719e8b984dbec3fd54140b66df0cf7e13d): batch request: Repository not found.: exit status 1

Please let me know the possible solution.

**Comment by mimmi20** [comment]
I dont know what you are trying to do. Could you explain a bit more?
