### ISSUE TITLE
Chrome Version Recognized as 0.0

### ISSUE THREAD

**Issue by 9ae8sdf76** [browscap/browscap#2235]
There seems to have been a regression from https://github.com/browscap/browscap/issues/1389, as at the time of this writing the latest version of Chrome is recognized as 0.0 again. 

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36`

Using browscap `6000037`.

Thank you!

**Comment by mimmi20** [comment]
same as #2224.
