### ISSUE TITLE
Release zip 6.0.38 is not updated

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#2252]
The [zipfile](http://browscap.org/stream?q=BrowsCapZIP) doesn't contain the latest updates.
The [CSV](http://browscap.org/stream?q=BrowsCapCSV) does contain the latest updates.

Please update all artifacts to avoid confusion.
I verified it by looking at the CSV file in the zip version, and searched for "Chrome 80.0", which is present (but should be).

**Comment by asgrim** [comment]
Hi Paul, I can confirm all artifacts for 6.0.38 were updated correctly. The "acid" test is to check a UA on the http://browscap.org/ua-lookup tool, for example `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36` correctly resolves to `Chrome 80.0`.

I've just downloaded the CSV for example, and it does contain `Chrome 80` (using `grep -i "Chrome 80" browscap.csv`).

My only thought is that you maybe got a cached copy. To ensure the problem isn't our end, I've gone ahead and purged our Cloudflare cache to eliminate that issue.

If you still think you're getting an older version please check any local caches aren't causing the issue. Please then, if you're using the CSV version, let us know whether the first two "version" lines in the CSV match properly:

```
"GJK_Browscap_Version","GJK_Browscap_Version"
"6000038","Tue, 17 Mar 2020 13:57:16 +0000"
```

If they match, please could you verify the `md5sum` of your CSV matches:

```
a8a0c949a2c978b59465d95c81c7a47b  browscap.csv
```

Perhaps you're getting an incomplete download or something?

Hope something helps, it looks like everything is working our end so hopefully you can get up and running quickly @paulrutter !

**Comment by paulrutter** [comment]
Hi @asgrim,

Thanks for checking.
Yes, when i download the zip again now, all is well.
The previous version i downloaded indeed stated 600037, so your thought about a cached copy might be right.

Let's close the issue, as it's resolved now.
Thanks for the help. The latest version of the java library has been updated :)

https://github.com/blueconic/browscap-java/releases

**Comment by asgrim** [comment]
Thanks for confirming @paulrutter ! I'll make sure the CF cache is cleared when we do a release in future - I always used to do it, but I got out of the habit as I wasn't sure if it made any difference anyway - anecdotally, it does :grin:

**Comment by paulrutter** [comment]
Thanks for your work on this awesome project, we (and quite some others) depend on it being updated regularly!

**Comment by asgrim** [comment]
> we (and quite some others) depend on it being updated regularly!

Thank you :) One day, when I find this mythical "time" thing, I'll automate the releases :sweat_smile:
