### ISSUE TITLE
"php composer.phar install" fails

### ISSUE THREAD

**Issue by riskop** [browscap/browscap#2259]
I'd like to compile the csv files from source.

When I run "php composer.phar install" it fails:

~/git/browscap$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 82 installs, 0 updates, 0 removals
  - Installing justinrainbow/json-schema (5.2.9): Loading from cache
  - Installing localheinz/diff (1.0.1): Loading from cache
  - Installing ergebnis/json-printer (3.0.2): Loading from cache
  - Installing ergebnis/json-normalizer (0.11.0): Loading from cache
  - Installing ergebnis/composer-normalize (2.2.2): Loading from cache
PHP Fatal error:  Uncaught TypeError: Return value of Ergebnis\Composer\Normalize\NormalizePlugin::activate() must be an instance of Ergebnis\Composer\Normalize\void, none returned in /home/riskop/git/browscap/vendor/ergebnis/composer-normalize/src/NormalizePlugin.php:28
Stack trace:
#0 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Plugin/PluginManager.php(237): Ergebnis\Composer\Normalize\NormalizePlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(Ergebnis\Composer\Normalize\NormalizePlugin))
#2 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Reposit in /home/riskop/git/browscap/vendor/ergebnis/composer-normalize/src/NormalizePlugin.php on line 28

Fatal error: Uncaught TypeError: Return value of Ergebnis\Composer\Normalize\NormalizePlugin::activate() must be an instance of Ergebnis\Composer\Normalize\void, none returned in /home/riskop/git/browscap/vendor/ergebnis/composer-normalize/src/NormalizePlugin.php:28
Stack trace:
#0 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Plugin/PluginManager.php(237): Ergebnis\Composer\Normalize\NormalizePlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Plugin/PluginManager.php(206): Composer\Plugin\PluginManager->addPlugin(Object(Ergebnis\Composer\Normalize\NormalizePlugin))
#2 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Installer/PluginInstaller.php(62): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#3 phar:///home/riskop/git/browscap/composer.phar/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Reposit in /home/riskop/git/browscap/vendor/ergebnis/composer-normalize/src/NormalizePlugin.php on line 28

  Maybe it's some obvious problem, but I am a beginner in php...

**Comment by asgrim** [comment]
What version of PHP are you running please? You need at least PHP 7.1.
