### ISSUE TITLE
iPad Safari UA being detected as Mobile Device instead of Tablet - chrome dev tools

### ISSUE THREAD

**Issue by billyholbrook** [browscap/browscap#2262]
When running the UA lookup tool against the iPad Safari iOS 13.2 UA (the one that my version of chrome developer tools uses), it is detecting it as a device type of "Mobile Device", rather than "Tablet". This is the UA that chrome developer tools is using:

Mozilla/5.0 (iPad; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1

![Screen Shot 2020-04-13 at 1 10 35 PM](https://user-images.githubusercontent.com/18044547/79162164-04f7b680-7d9a-11ea-9f68-5c339ecdcbb1.png)

**Comment by sciprok** [comment]
This  seems  to map as device_type = Desktop in browscap, which is  also not Tablet. Would be interested in  this one updated to be reflected as Tablet.
