### ISSUE TITLE
iPad Safari detected as Desktop device

### ISSUE THREAD

**Issue by Froxz** [browscap/browscap#2263]
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15

Browser: Safari

**Comment by mimmi20** [comment]
see here: #2232

**Comment by Froxz** [comment]
Hi @mimmi20 thank you.

**Comment by Froxz** [comment]
@mimmi20 question, there is no way to detect device_pointing_method as touch, based on this user agent?

because currently is says:  device_pointing_method | mouse

**Comment by mimmi20** [comment]
No. This is the dekstop useragent, the same used with macOS. Based on the useragent is no way to detect that.
