### ISSUE TITLE
iPad detected as "Desktop" instead Tablet

### ISSUE THREAD

**Issue by BurninLeo** [browscap/browscap#2266]
It seems that various iPads are detected as `device_type=Desktop`.

I could confirm that on https://browscap.org/ua-lookup with the following browser string:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

(Actually, the browser string seems not to give any clue that it is no MacBook)

I have also reports for the same issue with iPad Pro 3rd and 6th generation.

**Comment by mimmi20** [comment]
see here: #2232
