### ISSUE TITLE
Safari Version Issue

### ISSUE THREAD

**Issue by stermenis** [browscap/browscap#2284]
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`

Returns a version 0.0

**Comment by 1xtr** [comment]
From macbook or ipad pro too

**Comment by eesquibel** [comment]
Also have this user agent hitting our sites and not being detected properly.

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15`
