### ISSUE TITLE
applbot not in browscap file

### ISSUE THREAD

**Issue by sklewis13** [browscap/browscap#2300]
Following applebot I can't find in the browscap.xml file.  It's creating about 150,000 blank customer records a day in my nopcommerce site.

----------
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1)
-----------
Comes from ip address range  17.58.97.*

According the the response I got from apple:
----
Our user agent is documented here: https://support.apple.com/en-us/HT204683. If do see generally a listing for Applebot. 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1)

Is this the user agent that’s not correctly identified?
-----

**Comment by asgrim** [comment]
That user agent is recognised correctly by the files; you can verify on http://browscap.org/ua-lookup and enter UA string to check.
