### ISSUE TITLE
Has browscap c++ client library?

### ISSUE THREAD

**Issue by VictorRomanov2** [browscap/browscap#2312]
Hi browscap
Subj, if not then may be some gold data to test from php client. I am not PHP developer, but will try to translate to c++
Best regards. Victor

**Comment by asgrim** [comment]
@VictorRomanov2 I haven't heard about a C++ implementation, however PHP's own internal implementation is written in C, you can check that out here: https://github.com/php/php-src/blob/master/ext/standard/browscap.c - may be of some help! Thanks.

**Comment by asgrim** [comment]
If you do make a C++ implementation, please feel free to add it to https://github.com/browscap/browscap/wiki/Using-Browscap

**Comment by VictorRomanov2** [comment]
Thank you, php has some implementation, but how to check it. Have you some data for test cases? Probably it is user agent string and gold answer from client. I didn't find in repositories something.

**Comment by asgrim** [comment]
Both the C implementation in `php-src` and the `browscap/browscap` PHP implementation have test suites to verify functionality.
