### ISSUE TITLE
Introduce automatic releases

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#2316]
https://github.com/Roave/automatic-releases is a tool @ocramius is working on;

The process on this repo should be something like (depends on setting up `roave/automatic-releases`):

 - Create next milestone (if not already), e.g. `6.0.40`
 - PRs get assigned to the Milestone and merged (already happens)
 - Milestone `6.0.40` is closed
 - Release is automatically tagged as `6.0.40` & pushed to GH releases
 - Hooks already update packagist with newest version

Then on the website side of things (depends on browscap/browscap-site#63)
 - `browscap/browscap-site` will be scanned daily for dependency updates, so Dependabot will make a PR to update deps there
 - If build passes on Dependabot's PR, we merge, it gets auto deployed

Once this process is working, update the wiki: https://github.com/browscap/browscap/wiki/Public-release-procedure

**Comment by Ocramius** [comment]
Discussed this in chat with @asgrim: `roave/automatic-releases` is being converted to a github action, so we can get rid of any complexity in setup, and document all the required environment variables there.

**Comment by asgrim** [comment]
Fixed by #2336 - closing.
