### ISSUE TITLE
Missing browser version for UA: Firefox 78.0.2

### ISSUE THREAD

**Issue by RaySolomon** [browscap/browscap#2325]
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

verified by UA Lookup
https://browscap.org/ua-lookup

**Comment by mimmi20** [comment]
Fixed with PR #2323

**Comment by asgrim** [comment]
I'll look at getting a release done tomorrow 😅
