### ISSUE TITLE
Older iPad not detected as tablet

### ISSUE THREAD

**Issue by Lonzak** [browscap/browscap#2355]
I migrated our user agent functionality to your library. Nearly all unit tests worked except for this UA:

Mozilla/5.0 (iPad; U; CPU OS 4_3_5 like Mac OS X; de-de) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8L1 Safari/6533.18.5";

The user agent is not detected as a tablet but iPad qualifies as one...

This user agent or similar are listed here:
https://developers.whatismybrowser.com/useragents/explore/operating_platform/ipad/9

**Comment by Lonzak** [comment]
Activity!

**Comment by jaydiablo** [comment]
I don't think anything has changed recently in browscap that would have changed the detection of this UA, but I just ran this through browscap.org/ua-lookup and it outputs that it's a tablet:

```
browser_name_regex | /^mozilla\/5\.0.*\(ipad.*cpu os 4_3.* like mac os x.*\).*applewebkit.*\(.*khtml.*like.*gecko.*\).*version\/5\.0.*safari\/.*$/
browser_name_pattern | mozilla/5.0*(ipad*cpu os 4_3* like mac os x*)*applewebkit*(*khtml*like*gecko*)*version/5.0*safari/*
parent | Mobile Safari 5.0
comment | Mobile Safari 5.0
browser | Safari
browser_type | Browser
browser_bits | 32
browser_maker | Apple Inc
browser_modus | unknown
version | 5.0
majorver | 5
minorver | 0
platform | iOS
platform_version | 4.3
platform_description | iPod, iPhone & iPad
platform_bits | 32
platform_maker | Apple Inc
alpha | false
beta | false
win16 | false
win32 | false
win64 | false
frames | true
iframes | true
tables | true
cookies | true
backgroundsounds | false
javascript | true
vbscript | false
javaapplets | true
activexcontrols | false
ismobiledevice | true
istablet | true
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 3
aolversion | 0
device_name | iPad
device_maker | Apple Inc
device_type | Tablet
device_pointing_method | touchscreen
device_code_name | iPad
device_brand_name | Apple
renderingengine_name | WebKit
renderingengine_version | unknown
renderingengine_description | For Google Chrome, iOS (including both mobile Safari, WebViews  within third-party apps, and web clips), Safari, Arora, Midori, OmniWeb,  Shiira, iCab since version 4, Web, SRWare Iron, Rekonq, and in Maxthon  3.
renderingengine_maker | Apple Inc
```

Are you using the Full version of browscap or Lite/Standard (these results are from the Full version)?

**Comment by Lonzak** [comment]
Yes you are right! I am using the java version of browscap and mistakenly thought it was not detected by browscap. So  we can close this here since it is a java issue then...
