### ISSUE TITLE
Firefox UA Version Strings

### ISSUE THREAD

**Issue by Stexxen** [browscap/browscap#2356]
Following on from PR https://github.com/browscap/browscap/pull/2323

I've started seeing 
`
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:81.0) Gecko/20100101 Firefox/81.0
`

From https://wiki.mozilla.org/Release_Management/Calendar
![image](https://user-images.githubusercontent.com/4494301/93079020-5c6cbc00-f683-11ea-814e-36983152a20f.png)

Can the above versions be added please.

**Comment by Stexxen** [comment]
Also Nightlys show versions up to 86
![image](https://user-images.githubusercontent.com/4494301/93079556-38f64100-f684-11ea-891a-07def649ef6c.png)

**Comment by mimmi20** [comment]
You are free to open a PR for this

**Comment by paulrutter** [comment]
@asgrim This issue can be resolved with the latest release 👍

**Comment by asgrim** [comment]
Fixed in #2374

**Comment by asgrim** [comment]
Thanks @paulrutter :)
