### ISSUE TITLE
Chrome 86

### ISSUE THREAD

**Issue by em9999** [browscap/browscap#2370]
Hello,

Chrome 86 isn't being recognized and showing 0 as version:

"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"

**Comment by paulrutter** [comment]
@asgrim This issue can be resolved with the latest release 👍

**Comment by asgrim** [comment]
Fixed in #2374

**Comment by asgrim** [comment]
Thanks @paulrutter :)
