### ISSUE TITLE
Future of user agent string parsing

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#2378]
When researching Safari ITP, i came across this proposal from Chrome.
https://groups.google.com/a/chromium.org/forum/m/#!msg/blink-dev/-2JIRNMWJ7s/yHe4tQNLCgAJ

It looks like they're suggesting to drop useragent strings altogether, and instead move to less fine grained means of recognizing a client. 

It might change how this library would work so i thought it was interesting to share. Note that it's only a proposal, so it might not be implemented at all.

**Comment by asgrim** [comment]
I think if the day comes where user agents are not a "thing", I would happily deprecate and retire this library. Even when I took it over UA sniffing was "a bad thing™", and I'd be very happy for it to go away tbh 😁

**Comment by paulrutter** [comment]
Agreed, although the question is if the alternative is sufficient. We'll see what happens :)

**Comment by paulrutter** [comment]
Let's close for now.
