### ISSUE TITLE
Add "PetalBot" to the list of crawlers

### ISSUE THREAD

**Issue by AndreiMaz** [browscap/browscap#2415]
We get a lot of "search crawler" requests with the following header - 

Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://aspiegel.com/petalbot)

Please add it to the list

I presume it should be something like: Mozilla/5.0 (compatible;PetalBot;+https://aspiegel.com/petalbot)

**Comment by mimmi20** [comment]
@AndreiMaz Please add a pull request

**Comment by AndreiMaz** [comment]
@mimmi20 Unfortunately, I don't have an opportunity to do a PR. Please do it yourself. I've just shared information about a new crawler so you can make the database better
