### ISSUE TITLE
macOS, Edge get error.

### ISSUE THREAD

**Issue by juvenrui** [browscap/browscap#2446]
Hi:

My current HTTP_USER_AGENT is: 
`Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.53`

get_browser() show:
```
array (size=10)
  'browser_name_regex' => string '~^mozilla/5\.0 \(.*mac os x.*\) applewebkit.* \(.*khtml.*like.*gecko.*\) chrome/88\.0.*safari/.*$~' (length=98)
  'browser_name_pattern' => string 'Mozilla/5.0 (*Mac OS X*) applewebkit* (*khtml*like*gecko*) Chrome/88.0*Safari/*' (length=79)
  'parent' => string 'Chrome 88.0' (length=11)
  'platform' => string 'MacOSX' (length=6)
  'comment' => string 'Chrome 88.0' (length=11)
  'browser' => string 'Chrome' (length=6)
  'version' => string '88.0' (length=4)
  'device_type' => string 'Desktop' (length=7)
  'ismobiledevice' => string '' (length=0)
  'istablet' => string '' (length=0)
```
I think browser is 'Edge 88.0'.

**Comment by juvenrui** [comment]
I use this segment:
```
[Mozilla/5.0 (Macintosh; *Mac OS X*) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/* Edg/88.*]
Parent="Edge 88.0"
Platform="MacOSX"
```

**Comment by smazurov** [comment]
this shouldn't be marked as stale as its still a problem.

**Comment by mimmi20** [comment]
you are free to create a Pullrequest for this issue.

**Comment by smazurov** [comment]
Still a problem

**Comment by asgrim** [comment]
> Still a problem

If you are still having this issue, a PR is welcome.

**Comment by nileshpawa** [comment]
This is still a problem on Big Sur Mac OS,  To fix this, I have updated the phpbrowscap.ini as below.

From Edge version 80 to 85 user agent is like: 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like*gecko*) Chrome/* Safari/* Edg/85.*
```

From Edge version 86 to 89 user agent is like:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like*gecko*) Chrome/* Safari/* Edg/85.*
```
So for Edge version 80 to 85 add below:   (change version number accordingly)
```
[Mozilla/5.0 (*Mac OS X 10?16*) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/* Edg/84.*]
Parent="Edge 84.0"
Platform="macOS"
```

For Edge versions 86 to 89 add:  (change version number accordingly)
```
[Mozilla/5.0 (*Mac OS X 11?*) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/* Edg/86.*]
Parent="Edge 86.0"
Platform="macOS"
```

**Comment by smazurov** [comment]
Still an issue

**Comment by asgrim** [comment]
> Still an issue

You keep saying that, but it's clearly not important enough for you to bother making a PR as has already been suggested. Repeatedly commenting to stop the issue being closed is not helpful. So sorry, but I am closing this issue.
