### ISSUE TITLE
Long user agent not usable by mysql

### ISSUE THREAD

**Issue by james-funk-fen** [browscap/browscap#2474]
The main lookup query 

"SELECT * FROM {browscap} WHERE :useragent LIKE useragent ORDER BY LENGTH(useragent) DESC"

only functions when useragent is 30 or fewer characters on mysql Ver 8.0.21 and probably others. This prevents system from recognizing chrome browsers and many others

**Comment by asgrim** [comment]
Not sure what this has to do with us - the database is provided as an INI file, not SQL file. Perhaps report an issue to whatever library/application you are using...?
