### ISSUE TITLE
New UA for Xiaomi Redmi Note 10 Pro Chrome

### ISSUE THREAD

**Issue by damdab** [browscap/browscap#2476]
This it user agent for new Xiaomi Redmi Note 10 Pro on it's chrome. FF does not provide more, than generic device information.
Info is missing in current browscap version 6000043. I am usually using browscap/browscap-php,

`Mozilla/5.0 (Linux; Android 11; M2101K6G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.82 Mobile Safari/537.36`

Firefox prints only

`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0`

Opera provides:

`Mozilla/5.0 (Linux; Android 11; M2101K6G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36 OPR/63.3.3216.58675`

Opera Touch:

`Mozilla/5.0 (Linux; Android 11; M2101K6G Build/RKQ1.200826.002) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.82 Mobile Safari/537.36 OPT/2.9`

MiUiBrowser:

`Mozilla/5.0 (Linux; U; Android 11; pl-pl; Redmi Note 10 Pro Build/RKQ1.200826.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.147 Mobile Safari/537.36 XiaoMi/MiuiBrowser/12.10.3-gn`

Finally Edge:

`Mozilla/5.0 (Linux; Android 11; M2101K6G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/46.03.4.5155`

Let me know, if I might check anything additionally

**Comment by sanchezzzhak** [comment]
Xiaomi Redmi Note 10 Pro
* [ ] Mozilla/5.0 (Linux; Android 11; M2101K6I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36
