### ISSUE TITLE
BrowsCap 6000045 CSV not correct

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#2481]
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4240.183 Safari/537.36' is recognized via lookup http://browscap.org/ua-lookup, but not when using the CSV file that i've downloaded.

Is the CSV properly updated on http://browscap.org/?

**Comment by asgrim** [comment]
Sometimes Cloudflare caches a little aggressively; I've purged the cache, please do check again in a few moments :+1:

**Comment by paulrutter** [comment]
Thanks, it's fine now.

**Comment by asgrim** [comment]
Thanks for following up, will close this :)
