### ISSUE TITLE
 metasploitلا يقدر علئ فتح  التحكم فيالاوامر في اداه

### ISSUE THREAD

**Issue by Hakemohamed** [browscap/browscap#2490]
[*] Auxiliary module running as background job 3.

[*] Using URL: http://0.0.0.0:8080/siS20xIA
[*] Local IP: http://10.90.90.1:8080/siS20xIA
[*] Server started.
msf6 auxiliary(gather/android_htmlfileprovider) > [*] Request 'GET /siS20xIA'
[*] User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0
[*] Sending initial HTML ...
[*] Request 'GET /siS20xIA'
[*] User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0
[*] Sending initial HTML ...
[*] Request 'GET /siS20xIA'
[*] User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0
[*] Sending initial HTML ...
[*] Request 'GET /siS20xIA'
[*] User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0
[*] Sending initial HTML ...

**Comment by asgrim** [comment]
Sorry, I don't understand what the issue is here? Also please update the title to English so everyone can understand.
