### ISSUE TITLE
Close the wiki page from editing for third-party contributors

### ISSUE THREAD

**Issue by sanchezzzhak** [browscap/browscap#2497]

**Comment by asgrim** [comment]
Why? 🤔

**Comment by sanchezzzhak** [comment]
![image](https://user-images.githubusercontent.com/1337066/121227533-57e0d700-c894-11eb-8c62-a7f2139bc2a5.png)

1 so that there are no garbage pages
2 also, any participant can delete the page

**Comment by asgrim** [comment]
Hrmm that's a shame. Left it open so folks could contribute. I'll take a look. Thanks!

**Comment by asgrim** [comment]
Thanks @sanchezzzhak - I have now restricted the wiki :disappointed:
