### ISSUE TITLE
Support Latest SamsungBrowser(>=14.2)

### ISSUE THREAD

**Issue by iwasa-kosui** [browscap/browscap#2516]
1. Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/12.1 Chrome/79.0.3945.136 Safari/537.36
2. Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Safari/537.36

Both of the above is Samsung Browser's User-Agent string. However, with http://browscap.org/ua-lookup, Browscap says the first one is Samsung Browser's one but the second one is Chrome's one.

It is because that `samsung-android-browser-6-2-on.json` only supports the specific version of SamsungBrowser and `samsung-android-browser-generic.json` only supports old  SamsungBrowser's UA string format.

**Comment by willyaranda** [comment]
This should be fixed by #2537
