### ISSUE TITLE
Opera 77 is missing

### ISSUE THREAD

**Issue by paulrutter** [browscap/browscap#2522]
See https://github.com/blueconic/browscap-java/issues/39.

Opera 77 is not recognized. UA:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 OPR/77.0.4054.277

**Comment by asgrim** [comment]
Closed in 82b80174251d9d8819d8366de3431dd6610899bf
