### ISSUE TITLE
Edge on Linux missing on 6000050 

### ISSUE THREAD

**Issue by aCid62** [browscap/browscap#2540]
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.26

**Comment by willyaranda** [comment]
Fixed on #2542 by checking https://browscap.org/ua-lookup

**Comment by asgrim** [comment]
Thanks!
