### ISSUE TITLE
Ablaze Floorp UA

### ISSUE THREAD

**Issue by Kori-Syusetu** [browscap/browscap#2587]
English
===
I'm writing this because I'm using version 6000051 of full_php_browscap.ini and I can't determine Ablaze Floorp's UserAgent correctly.
The UserAgent in question is: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0 Floorp/8.3.6".
This is just Firefox's UserAgent with the Floorp version attached.
Floorp has been a Firefox-based browser since Version 8.
The 7.x version was based on Kinza, and the 1.x version was based on Chromium, both with the same UserAgent.
The latest version at the moment (2022/02/23) is 8.4.8, but Google is temporarily fixing the UserAgent to 8.3.6 because it is not working properly.

Translated with www.DeepL.com/Translator (free version)

Floorp 8.3.x -> Firefox 96.x Base
Floorp 8.4.x -> Firefox 97.x Base

- Browser: Floorp
- Browser Maker: Ablaze
- Browser Maker(Alt): Floorp Project
- Browser Type: Browser

日本語
===
バージョン6000051の full_php_browscap.ini を使用していて，Ablaze Floorpの UserAgent が正常に判別できないためこうして書いています．
対象の UserAgent は次の通りです： "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0 Floorp/8.3.6"
これは，Firefoxの UserAgent に，Floorpのバージョンを付けただけのものです．
FloorpはVersion 8以降，Firefoxベースのブラウザとなりました．
UserAgentに変更の無い，7.xはKinzaを,1.xはChromiumをベースとしていました．
また，現時点(2022/02/23)での最新版は 8.4.8 ですが，Googleの動作に異常をきたすため，UserAgentを8.3.6のもので一時的に固定しているそうです．

**Comment by mimmi20** [comment]
@Kori-Syusetu Do you have more useragents from this browser (also for older versions)? Does this browser also exist on other platforms (like Linux, macOS or Android) like Firefox?

**Comment by Ryosuke-Asano** [comment]
### Japanese

 突然失礼します。このブラウザーの開発者です。

Firefox のユーザーエージェントに追従することにしたのでこのissue は close してもらって構いません。


### English 

I'm sorry to bother you. I'm the developer of this browser.

I've decided to follow Firefox's user agent, so you can close this issue.

**Comment by asgrim** [comment]
> 突然失礼します。このブラウザーの開発者です。
> 
> Firefox のユーザーエージェントに追従することにしたのでこのissue は close してもらって構いません。

Please reply in English. Translation using automated tools is not always accurate. Thank you.

**Comment by Ryosuke-Asano** [comment]
> @ Kori-Syusetu このブラウザのユーザーエージェントは他にもありますか（古いバージョンの場合も同様）？ このブラウザは、Firefoxなどの他のプラットフォーム（Linux、macOS、Androidなど）にも存在しますか？

### Japanese
Linux と Windows に対応しています。Windows で劣化は確認できませんでしたが、Linux でば Google が劣化しました。私の環境が原因かもしれない ＆ UA が純粋であれば発生しなかったので、上記の通り、この独自のUAを使用を中止します。

### English 

It is available for Linux & Windows. I could not see any degradation on Windows, but Google degraded on Linux. It may be due to my environment & it would not have occurred if the UA was pure, so I will stop using this proprietary UA as described above.
