### ISSUE TITLE
Issues due to unescaped semicolons

### ISSUE THREAD

**Issue by b-t-927** [browscap/browscap#2636]
Hey all, I've had to download browscap a few times now, and every time it's basically impossible to use it without a load of manual intervention around escaping out the semicolons in UA strings.

A bit of googling will show various posts on places such as stackoverflow and these issues regarding this issue, so it's clearly not an isolated incident.

I'm just wondering if there's any reason for this at all or if I and the other people with these issues are just missing something blindingly obvious?

**Comment by asgrim** [comment]
@bruce2409 which format are you using, what programming language are you using, and what are you using to parse it please? The official PHP implementation, for example, already handles the files. There are also several other libraries that can be used in other languages, listed here: https://github.com/browscap/browscap/wiki/Using-Browscap - most common languages already covered by these libraries, so it shouldn't be necessary to manually change anything :/

**Comment by b-t-927** [comment]
Hi Asgrim, sorry should've clarified!

This is the lite browscap file for PHP, both 8.0 and 8.1. I'm loading it via php.ini's browscap parameter, which seems to be the common issue there.

I appreciate there's a library available for this and support for other methods would be best described as best effort, but I'd ideally like to keep my project dependencies to a minimum, especially when the get_browser function works well enough.

**Comment by asgrim** [comment]
@bruce2409 OK - could you clarify exactly the manual interventions/escaping you have to do please? My suspicion is that this should be handled in upstream PHP's implementation, as all other current implementations don't appear to have any issues.

**Comment by b-t-927** [comment]
@asgrim Sure, it's basically just doing find and replaces for the errors that stop it working, so for example I'll get:

```
 ~> php
PHP:  syntax error, unexpected end of file, expecting ']' in /opt/homebrew/etc/php/8.1/conf.d/browscap.ini on line 19562
```
Which in this case has:
`[Mozilla/5.0 (Windows 95; Anonymisiert*\; Trident/7.0*]`

So I then do a string replacement to change `95;` to `95\;` (As you can see already with the `*\;` on that line). Rinse and repeat until it finally works.

I did run into some sed commands that would supposedly do it all in one hit, since it seems just a blanked replacement of ; with \; just causes bigger errors due to the comment, but without any joy, hence the manual process here. That's also why once it works I just leave the file untouched which probably isn't ideal long term!

**Comment by asgrim** [comment]
@mimmi20 Hmm, do we think anything can be done here? Are these missed escaping? If we fix them, will it break things?

**Comment by b-t-927** [comment]
@asgrim So I've done some more digging and it seems like it was a bit of a red herring (see back to the missing something blindingly obvious part!).

It seems like the issue only crops up if you put the browscap.ini file in any of the locations where php looks for and parses ini files from it causes the errors without the escaping, but if it's somewhere else then it seems to work fine without the escaping. The errors were basically php trying to parse it like a normal config ini rather than something else entirely.

So does seem like a layer 8 issue on my part, sorry about that! But would it be possible to add a note to the wiki about this? Just to avoid people getting confused in future?

**Comment by asgrim** [comment]
Great idea - thank you @bruce2409 - hope this helps: https://github.com/browscap/browscap/wiki/Using-Browscap/_compare/949817243d697c83b052b92ae439d642c77dd300...9191030c9c634086310e563948ebd20ffa0183af
