### ISSUE TITLE
Brave Browser is detecting as Chrome

### ISSUE THREAD

**Issue by cjsio** [browscap/browscap#2676]
Hi, I'm using Brave Browser Version 1.40.109 w/ Chromium Version 103.0.5060.66 (Official Build) (64-bit) on Windows 11, but after updating to the latest [php_browscap.ini](http://browscap.org/stream?q=PHP_BrowsCapINI), Brave Browser is being detected as:

>Chrome version 103 on Windows 10

According to [developers.whatismybrowser.com](https://developers.whatismybrowser.com/useragents/explore/software_name/brave/), most Brave user agents contains the keyword "Brave" in them, but my current user agent in a standard Brave installation on Win11 is:

>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36

Thanks

**Comment by cjsio** [comment]
Is there a way that we can help with this? I don't see any identifiable portion in the user agent string that would distinguish Brave from Chrome. Is this something that would need to be updated in Brave's codebase to always include an identifiable portion?

**Comment by asgrim** [comment]
> Is there a way that we can help with this? I don't see any identifiable portion in the user agent string that would distinguish Brave from Chrome. Is this something that would need to be updated in Brave's codebase to always include an identifiable portion?

Yeah unless there's something distinguishable, it's not going to work :/

**Comment by cjsio** [comment]
I have opened [issue #24478](https://github.com/brave/brave-browser/issues/24478) in the Brave Browser issue tracker to make progress on this useragent discrepancy.

**Comment by asgrim** [comment]
As the upstream issue #24478 has been closed without any change, unfortunately, there's nothing more we can do in Browscap to support this unfortunately. Sorry :/
