### ISSUE TITLE
Unable to detect Safari browser version (15.5 onwards)

### ISSUE THREAD

**Issue by jainarvi** [browscap/browscap#2717]
**Describe the bug**
Unable to detect Safari browser version (15.5 onwards)

**To Reproduce**
Use below user Agent string for detecting browser version:

Mozilla/5.0 (iPhone; CPU iPhone OS 15_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Mobile/15E148 Safari/604.1

It gives browser version as 0.0

**Expected behavior**
It should give browser version as 15.6

**Screenshots**
NA
**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari
 - Version: 15.6

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS15.6
 - Browser Safari

**Additional context**
N/A

**Comment by asgrim** [comment]
I believe this will be fixed in #2715

**Comment by jainarvi** [comment]
Ok, I'll wait for #2715 review and merging.

**Comment by asgrim** [comment]
The 6.1.2 release is now [available](http://browscap.org/) and has this fix :+1:
