### ISSUE TITLE
windows 11 is detected as windows 10

### ISSUE THREAD

**Issue by WarHead** [browscap/browscap#2720]
My System:
Microsoft Windows 11 Pro N
10.0.22000 Build 22000

Detected as:
<html><body>

platform | Win10
-- | --
platform_version | 10.0
platform_description | Windows 10

</body>
</html>

I know why it's shown as Win10, but it should consider "Microsoft Windows 11 Pro N" to get the right version. ;-)

**Comment by jesusrodriguezmjp** [comment]
I have the same problem, Windows 11 is detected as Windows 10.

**Comment by sanchezzzhak** [comment]
windows 11 can only be identified through client hints

**Comment by asgrim** [comment]
See also #2706
