### ISSUE TITLE
Chrome, Edge and Firefox versions 108 and 109 are not detected using browscap

### ISSUE THREAD

**Issue by nileshpawarJIEM** [browscap/browscap#2734]
Chrome, Edge and Firefox versions 108 and 109 were not detected using browcap. It returns version 0 for them.

**Comment by asgrim** [comment]
Since you did not select the correct issue template, please provide

 * the full user agent(s) - not just partial UA strings
 * which Browscap version you tested on <e.g. 6001000 (or 6.1.0)> - full_asp_browscap.ini
 * Current result on http://browscap.org/ua-lookup

**Comment by nileshpawarJIEM** [comment]
- I am using latest php_browscap.ini file for detecting user agents
- User-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

**Comment by asgrim** [comment]
@nileshpawarJIEM please provide ALL information requested, the following is also needed:

 * which browscap version you tested on (e.g. 6.1.2)
 * Current result on http://browscap.org/ua-lookup

**Comment by nileshpawarJIEM** [comment]
- I am using php_browscap.ini Version=6001002

- Current result on http://browscap.org/ua-lookup
- ![browscap_ua](https://user-images.githubusercontent.com/109579466/201095241-f27424ac-1a12-4338-b506-b61fca05de30.png)

I am seeing the same issue for Edge version 108 also in Win10 and Mac both

**Comment by nileshpawarJIEM** [comment]
Chrome will be released version 108 stable on November 29 - https://chromiumdash.appspot.com/schedule
Can we please fix this issue before that?

**Comment by asgrim** [comment]
@nileshpawarJIEM yes, you can of course submit a PR with a new test and a UA - there is plenty of information available to help new contributors here: https://github.com/browscap/browscap/wiki thank you :)

**Comment by sanchezzzhak** [comment]
@asgrim how about creating a git-action that will automatically add versions?

it is enough for us to analyze the tag versions with a script
https://chromium.googlesource.com/chromium/src.git/+refs

versions are the same for webview+android
for chrome-desktop  will 107.0.0.0 etc.. be depersonalized

**Comment by asgrim** [comment]
> @asgrim how about creating a git-action that will automatically add versions?
> 
> it is enough for us to analyze the tag versions with a script https://chromium.googlesource.com/chromium/src.git/+refs
> 
> versions are the same for webview+android for chrome-desktop will 107.0.0.0 etc.. be depersonalized

We would need the UA strings to add tests against, not sure where they can be sourced from programmatically

**Comment by sanchezzzhak** [comment]
I hope this helps

* [ ] Mozilla/5.0 (Linux; Android 10; Nokia 7 plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36
* [ ] Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
* [ ] Mozilla/5.0 (Linux; Android 10; Redmi Note 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Mobile Safari/537.36 EdgA/109.0.0.0
* [ ] Mozilla/5.0 (Linux; Android 11; RMX3261 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.8 Mobile Safari/537.36
* [ ] Mozilla/5.0 (Linux; Android 12; 220333QAG Build/SKQ1.211103.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.44 Mobile Safari/537.36 OPX/1.8
* [ ] Mozilla/5.0 (Linux; Android 12; Mi Note 10 Lite Build/SKQ1.210908.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5394.3 Mobile Safari/537.36
* [ ] Mozilla/5.0 (Linux; Android 9; TA-1021 Build/PKQ1.181105.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 YaBrowser/22.8.0.214 (lite) Mobile Safari/537.36
* [ ] Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 Mobile DuckDuckGo/5 Safari/537.36
* [ ] Mozilla/5.0 (Linux; Android 12; SM-A135F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/396.0.0.21.104;]
* [ ] Mozilla/5.0 (Linux; U; Android 12; RMX3363 Build/RKQ1.210503.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 Mobile Safari/537.36 OPR/66.2.2254.64268

not found android platform version 
* [ ] Mozilla/5.0 (Linux; U; Android 13; A063 Build/TKQ1.220915.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 Mobile Safari/537.36 OPR/66.2.2254.64268

**Comment by paulrutter** [comment]
Please see https://github.com/browscap/browscap/pull/2599 for chrome versions up until version 107 as reference.

We are now also using client hints alongside of browscap, which gives us latest chrome versions automatically. Thats one of the reasons we're less active in creating new PRs.
