### ISSUE TITLE
Chrome 113 not detected with php_browscap Version=6001003

### ISSUE THREAD

**Issue by nileshpawarJIEM** [browscap/browscap#2827]
User Agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'

browser_name_regex | /^mozilla\/5\.0 \(.*windows nt 10\.0.*win64. x64.*\).*applewebkit.*\(.*khtml.*like.*gecko.*\).*chrome\/.* safari\/.*$/
-- | --
browser_name_pattern | mozilla/5.0 (*windows nt 10.0*win64? x64*)*applewebkit*(*khtml*like*gecko*)*chrome/* safari/*
parent | Chrome Generic
comment | Chrome Generic
browser | Chrome
browser_type | Browser
browser_bits | 64
browser_maker | Google Inc
browser_modus | unknown
version | 0.0
majorver | 0
minorver | 0
platform | Win10
platform_version | 10.0
platform_description | Windows 10
platform_bits | 64
platform_maker | Microsoft Corporation
alpha | false
beta | false
win16 | false
win32 | false
win64 | true
frames | true
iframes | true
tables | true
cookies | true
backgroundsounds | false
javascript | true
vbscript | false
javaapplets | false
activexcontrols | false
ismobiledevice | false
istablet | false
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 3
aolversion | 0
device_name | Windows Desktop
device_maker | unknown
device_type | Desktop
device_pointing_method | mouse
device_code_name | Windows Desktop
device_brand_name | unknown
renderingengine_name | Blink
renderingengine_version | unknown
renderingengine_description | a WebKit Fork by Google
renderingengine_maker | Google Inc

Checked on Windows 10 machine, php_browscap,ini Version=6001003

Chrome 113 not detected

**Comment by nileshpawarJIEM** [comment]
can anyone please let me know when this issue going to fix?

**Comment by asgrim** [comment]
> can anyone please let me know when this issue going to fix?

When someone has time and inclination to submit a PR to fix it :) feel free to do that! There are help files in the Wiki, should you need help getting started, thank you!

**Comment by sivann** [comment]
@asgrim so isn't browscap maintained any more? I have noticed it does not detect Chrome version for months. As Chrome support is pretty basic, it would be beneficial to denote lack of maintainers in the main page.

**Comment by asgrim** [comment]
> @asgrim so isn't browscap maintained any more? I have noticed it does not detect Chrome version for months. As Chrome support is pretty basic, it would be beneficial to denote lack of maintainers in the main page.

Yes, Browscap is still maintained. I'm happy to merge PRs to add this, and make releases when things are added, as I said previously.

If I get to it in the very little spare time I have, maybe I'll add it myself.

In the mean time, perhaps instead of complaining, submit a PR yourself. There is a guide on how to contribute in the wiki! Should be a case of adding some values to the JSON, and adding a test case with a sample user agent.

**Comment by JoergFF** [comment]
Hello,

the same with firefox 115.0.2 and some versions before.

With PHP_BrowsCapINI and Full_PHP_BrowsCapINI Version 6001004

CU
Jörg

**Comment by paulrutter** [comment]
See for a similar pr: https://github.com/browscap/browscap/pull/2599

We used to put in PRs for new versions, but with the introduction of user agent client hints it's less of a priority for us, as we can get the missing information from there (at least for chromium based browsers).

That said, it would still be good to keep adding new versions to this project.

**Comment by paulrutter** [comment]
Added a PR that adds the recent and future (up until 125) chromium based browsers in https://github.com/browscap/browscap/pull/2880.

We should also check iOS and Mac OS platform and browser versions, those might need an update as well.
