### ISSUE TITLE
BingBot ua missing

### ISSUE THREAD

**Issue by LiFiCode** [browscap/browscap#2891]
# User agent(s)

```
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36
```

# Browscap version tested on

< 6001005 > -  http://browscap.org/ua-lookup

# Current result on http://browscap.org/ua-lookup

```
browser_name_regex | /^.*$/
-- | --
browser_name_pattern | *
parent | DefaultProperties
comment | Default Browser
browser | Default Browser
browser_type | unknown
browser_bits | 0
browser_maker | unknown
browser_modus | unknown
version | 0.0
majorver | 0
minorver | 0
platform | unknown
platform_version | unknown
platform_description | unknown
platform_bits | 0
platform_maker | unknown
alpha | false
beta | false
win16 | false
win32 | false
win64 | false
frames | false
iframes | false
tables | false
cookies | false
backgroundsounds | false
javascript | false
vbscript | false
javaapplets | false
activexcontrols | false
ismobiledevice | false
istablet | false
issyndicationreader | false
crawler | false
isfake | false
isanonymized | false
ismodified | false
cssversion | 0
aolversion | 0
device_name | unknown
device_maker | unknown
device_type | unknown
device_pointing_method | unknown
device_code_name | unknown
device_brand_name | unknown
renderingengine_name | unknown
renderingengine_version | unknown
renderingengine_description | unknown
renderingengine_maker | unknown
```

# Description / Further information

the UA is missing.
according to https://explore.whatismybrowser.com/useragents/explore/software_name/bingbot/ this ua is "Very common".

thank you for your service, it's highly appreciated!

**Comment by ElJ3ffy** [comment]
I have cloned the repo, created a new branch for this issue, updated the bingbot.js file, and added an integration test file at tests/issues/issue-2891.php. However, I'm not sure what else I need to do to run the tests. The docs are not up to date. Can anyone provide any tips? If I can get this working, I'm willing to add other missing UAs.

Thanks in advance.

**Comment by asgrim** [comment]
@ElJ3ffy you can make a pull request - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork thanks!
