### ISSUE TITLE
browscap is compatible with PHP-FPM 

### ISSUE THREAD

**Issue by wescleycarvalho** [browscap/browscap#2899]
Hi everyone,

I'm facing the problem with browscap with php-fpm. When i activate it on php.ini, the service of php-fpm does not start and returns error below:

<br />
 <b>Warning</b>:  Cannot open "/opt/php/extra/browscap.ini" for reading in <b>Unknown</b> on line <b>0</b><br />
 <br />
 <b>Fatal error</b>:  Unable to start standard module in <b>Unknown</b> on line <b>0</b><br />
 php-fpm.service: Main process exited, code=exited, status=254/n/a
 php-fpm.service: Failed with result 'exit-code'.
 systemd[1]: Failed to start The PHP FastCGI Process Manager.

When disable, the service runs ok. Can anyone help with this?

**Comment by asgrim** [comment]
Can the user that PHP running as read that file (permissions, etc), and does it exist?

**Comment by wescleycarvalho** [comment]
Yes, apache is owner of files

**Comment by asgrim** [comment]
How are you including the browscap.ini please?

**Comment by wescleycarvalho** [comment]
> How are you including the browscap.ini please?

Hi man, sorry for delay.

Here a piece of may Containerfile for browscap

RUN mkdir /etc/php.d/extra
RUN wget -O browscap.ini https://browscap.org/stream?q=PHP_BrowsCapINI && mv ./browscap.ini /etc/php.d/extra/

**Comment by asgrim** [comment]
I meant the php.ini setting you're using. Usually that error is because you're trying to include browscap.ini alongside other php.ini files, but you need to include it differently. Please refer to the php manual for how to do it. Thanks!

**Comment by wescleycarvalho** [comment]
Thanks man! i'll try it.
