### ISSUE TITLE
ua return unknown result

### ISSUE THREAD

**Issue by scottwang0611** [browscap/browscap#2906]
ua : Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/116.0.0.0 Safari\/537.36

return result:
{
"browser_name_regex": "/^.*$/",
        "browser_name_pattern": "*",
        "parent": "DefaultProperties",
        "comment": "Default Browser",
        "browser": "Default Browser",
        "browser_type": "unknown",
        "browser_bits": "0",
        "browser_maker": "unknown",
        "browser_modus": "unknown",
        "version": "0.0",
        "majorver": "0",
        "minorver": "0",
        "platform": "unknown",
        "platform_version": "unknown",
        "platform_description": "unknown",
        "platform_bits": "0",
        "platform_maker": "unknown",
        "alpha": false,
        "beta": false,
        "win16": false,
        "win32": false,
        "win64": false,
        "frames": false,
        "iframes": false,
        "tables": false,
        "cookies": false,
        "backgroundsounds": false,
        "javascript": false,
        "vbscript": false,
        "javaapplets": false,
        "activexcontrols": false,
        "ismobiledevice": false,
        "istablet": false,
        "issyndicationreader": false,
        "crawler": false,
        "isfake": false,
        "isanonymized": false,
        "ismodified": false,
        "cssversion": "0",
        "aolversion": "0",
        "device_name": "unknown",
        "device_maker": "unknown",
        "device_type": "unknown",
        "device_pointing_method": "unknown",
        "device_code_name": "unknown",
        "device_brand_name": "unknown",
        "renderingengine_name": "unknown",
        "renderingengine_version": "unknown",
        "renderingengine_description": "unknown",
        "renderingengine_maker": "unknown"
}

**Comment by asgrim** [comment]
Please update your Browscap ini. This UA is already supported in the latest version.
