### ISSUE TITLE
My IP has been permanently banned.

### ISSUE THREAD

**Issue by barthol0** [browscap/browscap#3020]
**Describe the bug**
My IP has been permanently banned. 
Do you have any other channel where I could safely provide my IP so you can remove the ban?

**Comment by asgrim** [comment]
Please can you provide the full HTTP response body and headers you are receiving.

You may contact `banned@` (the domain) by email with sensitive information. I will respond on here accordingly.

**NOTE: we cannot reply from `banned@` email, we can only reply on Github.**

**Comment by barthol0** [comment]
Email sent. Thank you

**Comment by asgrim** [comment]
Should be fixed now, thanks
