### ISSUE TITLE
IP Address Permanently Banned

### ISSUE THREAD

**Issue by shieldsi** [browscap/browscap#3023]
Hi, we are currently in the early development stages on a project that I am testing and I have unfortunately been permanently banned. I was wondering what the process is to get un-banned. Thanks.

**Comment by asgrim** [comment]
Please can you provide the full HTTP response body and headers you are receiving.

You may contact `banned@` (the domain) by email with sensitive information. I will respond on here accordingly.

**NOTE: we cannot reply from `banned@` email, we can only reply on Github.**

**Comment by asgrim** [comment]
@shieldsi thanks for the info, you should be good to go now.

**Comment by shieldsi** [comment]
Thanks!
