### ISSUE TITLE
TikTok ua missing

### ISSUE THREAD

**Issue by Sirozha1337** [browscap/browscap#3050]
# User agent(s)

```
Mozilla/5.0 (iPhone; CPU iPhone OS 17_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Mobile/15E148 Safari/604.1 musical_ly_34.3.1 JsSdk/2.0 NetType/4G Channel/App Store ByteLocale/en Region/US isDarkMode/1 WKWebView/1 RevealType/Dialog
Mozilla/5.0 (Linux; Android 10; moto g(7) Build/QP6_S30.52-23-13-4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 musical_ly_2022704050 JsSdk/1.0 NetType/WIFI Channel/googleplay AppName/musical_ly app_version/27.4.5 ByteLocale/en ByteFullLocale/en Region/US Spark/1.2.4-alpha.5 AppVersion/27.4.5 PIA/1.5.10 BytedanceWebview/d8a21c6
Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 BytedanceWebview/d8a21c6 trill_34.9.0 JsSdk/2.0 NetType/4G Channel/App Store ByteLocale/en Region/MY FalconTag/31CFA6E0-CAE5-4ECF-A13A-ADFCAFC2428F
```

# Description / Further information

Hi, can you please add TikTok browser to your database? Here are a couple of UserAgents. You can also find more [here](https://explore.whatismybrowser.com/useragents/explore/software_name/tiktok/).

I can add those UAs myself, but I don't understand how to test my additions. I'm not very knowledgable about PHP and I couldn't find the instruction in your docs. If you can point me in the right direction, that would have been great.

**Comment by asgrim** [comment]
Sure - some info which may help:

 - Guide here; https://github.com/browscap/browscap/blob/6.1.x/CONTRIBUTING.md
 - Example MR from previous contributions: https://github.com/browscap/browscap/pull/2944/files

Thank you!

**Comment by Sirozha1337** [comment]
Hi @asgrim, unfortunately I've already seen those pages and they didn't help me much. Thanks for the example MR, I will try to use it as a template.

Also links to functions in your wiki seem to be broken, they all lead to 404 pages: https://github.com/browscap/browscap/wiki/Testing 

I tried running `phpunit --configuration phpunit.xml.dist`, but it shows a lot of failing tests:
```
1) BrowscapTest\Command\RewriteBrowsersCommandTest::testExecuteWithWongLoggerHelper
Failed asserting that exception of type "Error" matches expected exception "AssertionError". Message was: "Call to undefined method MockObject_ValidateHelper_2e1c719a::create()" at
/mnt/d/Projects/browscap/src/Browscap/Command/RewriteBrowsersCommand.php:55
/mnt/d/Projects/browscap/tests/BrowscapTest/Command/RewriteBrowsersCommandTest.php:76


2) BrowscapTest\Command\RewriteBrowsersCommandTest::testExecuteWithoutResourcesOption
Psr\Log\LoggerInterface::info('Resource folder: ', []): void was not expected to be called.

/mnt/d/Projects/browscap/src/Browscap/Command/RewriteBrowsersCommand.php:62
/mnt/d/Projects/browscap/tests/BrowscapTest/Command/RewriteBrowsersCommandTest.php:142

...
```

So, my questions are:
1. What do I need to install in order to run tests?
2. Which command will run all tests in the repo?
3. Which command will run only the test I've written?

**Comment by Sirozha1337** [comment]
Is there anyone who can help? Looks to me like this library is missing more than just this browser, but it's impossible to make a contribution if you're not familiar with PHP. Even though the database itself is in Regex and JSON and its output is an .ini file, which can be used in any programming language.

It would be much easier to contribute if there was a docker image with all the php requirements preinstalled, so I could just mount my working directory to it, see test results and then commit my changes.

**Comment by asgrim** [comment]
Such a contribution would be great 👍 I agree. We rely on third party contributions for this project entirely, so anything that makes that easier would be a benefit!
