### ISSUE TITLE
UA is missing

### ISSUE THREAD

**Issue by mvqit** [browscap/browscap#3067]
# User agent(s)

```
mozilla/5.0 (android; android 5.0; htc [m8
mozilla/5.0 (linux; android 4.4; [hm note
... see other posts
```

# Browscap version tested on

full_php_browscap.ini, 6001007

# Description / Further information

<describe what the issue is, e.g. the UA is missing, the UA needs correcting etc.>
UA is missing

**Comment by mvqit** [comment]
UA is missing, full_php_browscap.ini, 6001007

**Chrome.***
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; .NET CLR 2.0.50727; .NET4.0C)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 2.0.50727; QQBrowser/7.5.19314.400)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; .NET4.0C; .NET4.0E)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; InfoPath.2; .NET CLR 2.0.50727; SE 2.X MetaSr 1.0)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Chrome)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; 2345Explorer/8.0.0.13547
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Core/1.50.1414.400 QQBro
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; SE 2.X MetaSr 1.0)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; SE 2.X MetaSr 1.0)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/5.0) Core/1.47.1322.400 QQBrowser/9.4.9211.400
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/5.0) Core/1.47.933.400 QQBrowser/9.4.8699.400
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Chrome)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; SE 2.X MetaSr 1.0)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; ms-office)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/6.0)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/6.0; .NET CLR 2.0.50727; SLCC2; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/6.0; 2345Explorer 5.0.0.14138)
Chrome (AppleWebKit/537.1; Chrome50.0; Windows NT 6.3; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E)
Chrome (AppleWebKit/537.1; MSIE 10.0; Windows NT 6.3; Trident/6.0) LBBROWSER
Chrome (AppleWebKit/537.1; MSIE 8.0; Windows NT 6.3; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; LBBROWSER)

**Comment by mvqit** [comment]
Mozilla/5.0 researchscan.comsys.rwth-aachen.de
mozilla/5.0 (linux; u; android 4.4; xt1021 build/[kxb20.9

**Comment by mvqit** [comment]
UA is missing, full_php_browscap.ini, 6001007

**Microsoft Office.***
Microsoft Office Excel 2013 (15.0.4701) Windows NT 6.1
Microsoft Office Excel 2013 (15.0.4867) Windows NT 10.0
Microsoft Office Excel 2013 (15.0.4867) Windows NT 6.1

**Comment by mvqit** [comment]
UA is missing, full_php_browscap.ini, 6001007

**Mozilla .***
Mozilla/1.22 (compatible; MSIE 10.0; Windows 3.1)
Mozilla/4.0 (BindOk; SocketInit; AckOutTime; Compatible win32 67.118.4.166; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NE
Mozilla/4.0 (Compatible win32 126.238.206.208; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET
Mozilla/4.0 (compatible; MSIE 5.5;)
Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)
Mozilla/4.0 (compatible;MSIE 5.5; Windows 98)
Mozilla/4.047745454 Mozilla/4.0 (compatible; MSIE 5.00; Windows 98)
Mozilla/4.054101423 Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)
Mozilla/4.074482891 Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0
Mozilla/45.0 (compatible; MSIE 6.0; Windows NT 5.1)
Mozilla/5.0 (Android; Android 5.0; HTC [M8
Mozilla/5.0 (BindOk; SocketInit; CardNotInit; Compatible win32 10.85.108.244; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)
Mozilla/5.0 (Linux; Android 4.4.1; XT1043 Build/[KXB20.9
Mozilla/5.0 (Linux; Android 4.4; [HM NOTE
Mozilla/5.0 (Linux; Android 5.0; HTC [M8
Mozilla/5.0 (Linux; U; Android 4.4; XT1021 Build/[KXB20.9
Mozilla/5.0 (Linux; U; Android 5.0.1; HTC [M8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) 5.122092
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) nyt_xwords_ios/5.17.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2)
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) freeridegamesPlayer/11.3311.0.60
Mozilla/5.0 (Windows NT 10.0; Win64; x64)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Mozilla/5.0 (Windows NT 5.2) AppleWebKit/534+ (KHTML like Gecko) OpenWebKitSharp
Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/528.8 (KHTML, like Gecko)
Mozilla/5.0 (Windows; U; Windows NT 5.1; ru; rv:1.9.0.1) Gecko/2008070208
Mozilla/5.0 (Windows; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/20.0
Mozilla/5.0 (compatible) SemanticScholarBot (+https://www.semanticscholar.org/crawler)
Mozilla/5.0 (compatible; Example3/1.0; +https://www.example3.com/domain/kvetena-sk.com)
Mozilla/5.0 (compatible; Example3/1.0; +https://www.example3.com/domain/zahrada-cs.com)
Mozilla/5.0 (compatible; Example3/1.0; +https://www.example3.com/domain/zahrada-sk.com)
Mozilla/5.0 (compatible; MSIE 10.0; Macintosh; Intel Mac OS X 10_7_3; Trident/6.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows 95; Trident/4.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows 95; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows 98; Trident/3.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows 98; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows 98; Win 9x 4.90; Trident/3.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 11.0; Trident/4.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 4.0; Trident/5.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 5.01; Trident/3.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 5.01; Trident/4.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 5.01; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 5.2; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 6.0; Trident/5.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 6.1; Trident/4.1)
Mozilla/5.0 (compatible; MSIE 5.0; Windows NT 6.1; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 9.11; Windows NT 6.2; Trident/5.0)
Mozilla/5.0 (compatible; RedekenBot/0.1; +https://www.redeken.com/bot/)
Mozilla/5.0 (compatible; ev-crawler/1.0; +https://headline.com/legal/crawler)
Mozilla/5.0 (compatible; t3versionsBot/1.0; +https://www.t3versions.com/bot)
Mozilla/5.0 (compatible; wpbot/1.1; +https://forms.gle/ajBaxygz9jSR8p8G9)
Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.2; +https://openai.com/gptbot)
Mozilla/5.081397758 Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)

mozilla/5.0 (android; android 5.0; htc [m8
mozilla/5.0 (linux; android 4.4; [hm note
mozilla/5.0 (linux; android 5.0; htc [m8
mozilla/5.0 (linux; u; android 4.4; xt1021 build/[kxb20.9

User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; 360SE)
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; TencentTraveler 4.0)
User-Agent:Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0) IKU/7.0.5.9226;IKUCID/IKU;

**Comment by asgrim** [comment]
@mvqit thank you for listing all these user agents, but in general, someone won't just come along and add them all for you I'm afraid. If you are able to help by submitting a PR, a good place to start is here: https://github.com/browscap/browscap/blob/6.1.x/CONTRIBUTING.md

thanks!

**Comment by mvqit** [comment]
@asgrim  unfortunately, I can't add Pull Requests due to time constraints. I can only report strings that I catch in my site's log.

**Comment by asgrim** [comment]
Fair enough, it is the same for the maintainers here! Unless someone else picks this up, it is not likely these will be added I'm afraid.

**Comment by mvqit** [comment]
UA is missing, full_php_browscap.ini, 6001007

**VIZIO .***
VIZIO D24f4-J01 ViziOS/1.4.512.845.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D24h-J09 ViziOS/1.0.67.121 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO D24h-J09 ViziOS/1.0.92.150 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO D32f-J04 ViziOS/1.4.512.845.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D32f4-J01 ViziOS/1.0.67.121 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D32fM-K01 ViziOS/1.3.170.234 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D32h-J04 ViziOS/1.0.92.150 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D32h-J04 ViziOS/1.4.507.835.1 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO D32h-J04 ViziOS/1.4.512.845.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D40fM-K09 ViziOS/1.3.176.261 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO D43f-J04 ViziOS/1.4.512.845.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M43Q6-J04 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M506x-H9 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M55Q6-L4 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M55Q7-H1 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M65Q6-J09 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M65Q6-J09 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M65Q6-L4 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M65Q6M-K04 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO M70Q6-J03 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V405-H9 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V435-H1 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V435-J01 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V435-J01 ViziOS/1.0.69.130 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V435-J01 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V505-H9 ViziOS/1.4.507.837.1 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO V505-J01 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V505-J09 ViziOS/1.3.329.403.0 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO V505-J09 ViziOS/1.4.497.821.1 WatchFree/24.03.28.1 FancyPlayer/1.1.26-qa
VIZIO V505-J09 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V505M-K09 ViziOS/1.3.170.234 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V505M-K09 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V555-H1 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V555-J01 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V555-J01 ViziOS/1.0.69.130 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V555-J01 ViziOS/1.0.91.149 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V555-J01 ViziOS/1.3.329.403.0 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V555-J01 ViziOS/1.4.507.837.1 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO V585-H1 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V585-H1 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V585-J01 ViziOS/1.0.91.149 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V585M-K01 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V585x-H1 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V655-H9 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO V655-J04 ViziOS/1.0.75.134 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V655-J04 ViziOS/1.4.507.837.1 WatchFree/24.06.13.2 FancyPlayer/1.1.26-qa
VIZIO V655-J09 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705-J01 ViziOS/1.0.69.130 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705-J01 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705-J03 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705x-H3 ViziOS/1.0.67.124 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705x-J01 ViziOS/1.0.92.150 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705x-J03 ViziOS/1.0.68.127 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V705x-J03 ViziOS/1.0.69.130 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa
VIZIO V755x-K04 ViziOS/1.4.512.847.1 WatchFree/24.06.13.2 FancyPlayer/1.1.30-qa

**Comment by mvqit** [comment]
UA is missing, full_php_browscap.ini, 6001007

**Other**

MLBot (www.metadatalabs.com/mlbot)
MOTORIZR-Z8/46.00.00 Mozilla/4.0 (compatible; MSIE 6.0; Symbian OS; 356) Opera 8.65 [it] UP.Link/6.3.0.0.0
Mozilla/5.0 (compatible; WebwikiBot/2.1; +https://www.webwiki.de)
Mozilla/5.0 (compatible; ev-crawler/1.0; +https://headline.com/legal/crawler)
NOF/3.9.0.17/Win_10.0 SP0.0
SeznamReadLaterBot
SonyEricssonT68/R201A
Wget/1.12 (freebsd8.1)
Wget/1.9 cvs-stable (Red Hat modified)
acebookexternalhit/1.0 (+http://www.facebook.com/externalhit_uatext.php)
eBot / v.0.1f (http://alfa.elchron.cz)
trafilatura/1.11.0 (+https://github.com/adbar/trafilatura)
trafilatura/1.12.0 (+https://github.com/adbar/trafilatura)

**Comment by notflorian** [comment]
UA version is missing, full_php_browscap.ini, 6001007

**Safari**
Mozilla/5.0 (Macintosh; Intel Mac OS X 14_6_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15

**Comment by asgrim** [comment]
Please stop just dumping user agents here. I'm closing & locking this issue, as unless someone actually contributes a PR with tests to add these, it'll never get done.
