### ISSUE TITLE
Include JSON download on browscap.org

### ISSUE THREAD

**Issue by DaAwesomeP** [browscap/browscap#471]
I saw a pull that adds support for creating JSON, but it is not available for download on browscap.org. I think that most people (including me) would rather not compile it themselves, especially since automatic updates will be even more difficult with that.

**Comment by alcohol** [comment]
I don't know why, but the current version (6014) returns malformed JSON:

``` shell
curl -s 'http://browscap.org/stream?q=BrowsCapJSON' | python3 -m json.tool
Invalid \escape: line 2791 column 14 (char 543516)

curl -s 'http://browscap.org/stream?q=BrowsCapJSON' | jq . -
parse error: Invalid escape at line 2791, column 24
```

Offending line in question is:

``` json
"Friendica \'*\' 3.4*": "{\"Parent\":\"Friendica\",\"Version\":\"3.4\",\"MajorVer\":\"3\",\"MinorVer\":\"4\"}",
```

**Comment by mimmi20** [comment]
@alcohol Could you open a new issue for this error?
