### ISSUE TITLE
Please restore `->isbanned` property. Thanks.

### ISSUE THREAD

**Issue by quentin389** [browscap/browscap#5]
Please find the issue discussion here:
https://groups.google.com/forum/#!topic/browscap/vy_3S35Zt58

I've requested to add `->isbanned` property back.

After I add it to my project, I'm going to send you a file with this property from latest browscap version that had it. Less work for you :)

**Comment by jaydiablo** [comment]
Are there any plans to work on this?

I feel that this is entirely too subjective to be something that belongs in a user-agent parsing library.  One could build a library/script (really just needs to be an `in_array` sort of thing) on top of browscap's parser that keeps a list of "banned" browsers, and just match the "Browser" string returned from `get_browser` or whichever parser is used, and make their own decisions if the UA should be "banned" or not.

This could be turned into a custom formatter as well, which would be easy for others to use and mostly transparent to the end user (if using `browcap-php` 3.x or `crossjoin`).  That formatter could be maintained in a separate repo.

I think the discussion in https://github.com/quentin389/UserAgentInfo/issues/8 is more reason to not include data like this in the browscap project directly.

**Comment by mimmi20** [comment]
Not really.

**Comment by mimmi20** [comment]
@asgrim Could we close this?
