### ISSUE TITLE
Safari 8.0 on OS X identified as PaleMoon

### ISSUE THREAD

**Issue by edwinveldhuizen** [browscap/browscap#535]
Safari 8.0 on Mac OS X seems now to be wrongly identified as PaleMoon 24 Win8:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit/600.3.10 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.10

**Comment by mimmi20** [comment]
@edwinveldhuizen How did you detect this? Which version of Browscap did you use?

**Comment by edwinveldhuizen** [comment]
The latest browscap-php, tested on two MacBooks before and after running updateCache()

**Comment by edwinveldhuizen** [comment]
@mimmi20 Of course, this is the result I get:

```javascript
{
    "browser_name": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit\/600.3.10 (KHTML, like Gecko) Version\/8.0.3 Safari\/600.3.10",
    "browser_name_regex": "^mozilla\/5\\.0 \\(.*mac os x 10_10.*\\) applewebkit\/.* \\(khtml, like gecko\\) .*version\/(\\d)\\.(\\d).* safari\/.*$",
    "browser_name_pattern": "Mozilla\/5.0 (*Mac OS X 10_10*) AppleWebKit\/* (KHTML, like Gecko) *Version\/8.0* Safari\/*",
    "Parent": 76664,
    "Platform": "Win8",
    "Platform_Version": "6.2",
    "Win64": true,
    "Comment": "Palemoon 24.5",
    "Browser": "PaleMoon",
    "Version": "24.5",
    "MajorVer": "24",
    "MinorVer": "5",
    "CssVersion": "2",
    "Alpha": false,
    "Beta": false,
    "Win16": false,
    "Win32": false,
    "Frames": false,
    "IFrames": false,
    "Tables": false,
    "Cookies": false,
    "BackgroundSounds": false,
    "JavaScript": false,
    "VBScript": false,
    "JavaApplets": false,
    "ActiveXControls": false,
    "isMobileDevice": false,
    "isTablet": false,
    "isSyndicationReader": false,
    "Crawler": false,
    "AolVersion": "0"
}
```

**Comment by mimmi20** [comment]
@edwinveldhuizen Detecting PaleMoon without `PaleMoon` in the Useragent should not be possible. The `Parent` entry in the dump also should be a string, not a number. Could you check if you got any errors while creating the cache?

**Comment by edwinveldhuizen** [comment]
No errors and I start to think it's indeed more an issue with the php library than wrong metadata, since I've just found a macbook on which I don't have the issue, while 2 others still have this issue. On all three of them the cache.php is 13.439.359kb so nothing seems to go wrong in terms of building up the cache file.

**Comment by edwinveldhuizen** [comment]
@mimmi20 After I manually removed the cache.php file and ran the updateCache() again it all works again. I'll create an issue on the php-library instead, sorry for the false alarm and thanks for your help.
