### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by jota78** [browscap/browscap#548]
Some people are already using the preview version of Windows 10 (they just can't wait!)) and we started seeing some user agents with the "Windows NT 10.0" fragment. These are being classified as "Fake Browser" and Crawler=True which is obviously not true. Windows 10 should probably be added to the database already.

**Comment by mimmi20** [comment]
Windows 10 uses `Windows NT 6.4`

**Comment by jota78** [comment]
No it doesn't. Microsoft changed that.

**Comment by mimmi20** [comment]
Ok I saw this now.

**Comment by asgrim** [comment]
Can confirm: https://msdn.microsoft.com/en-us/library/ie/hh869301%28v=vs.85%29.aspx

**Comment by jota78** [comment]
http://www.theverge.com/2014/11/24/7274727/windows-10-nt-version-10

**Comment by asgrim** [comment]
yep :) the MSDN link confirms, I'd prefer to use Microsoft as a source for Microsoft user agents, over The Verge ;)
