### ISSUE TITLE
Fifth and Otter Request

### ISSUE THREAD

**Issue by kaminary** [browscap/browscap#554]
Hello.
I haven't found the Fifth Browser (https://github.com/clbr/fifth) on the list.
The Otter Browser is missing too. (http://otter-browser.org/)

**Comment by mimmi20** [comment]
@kaminary Du you have any useragents for these browsers?

**Comment by kaminary** [comment]
No, sorry.
Looking at the Fifth Browser i noted they use firefox user agent on windows, so we can forget to identify it.
