### ISSUE TITLE
Browser version is not correct

### ISSUE THREAD

**Issue by eugenzor** [browscap/browscap#565]
Useragent:
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.11 Safari/537.36

Browscap asserts that browser version is 0

**Comment by asgrim** [comment]
Looks like we're just missing Chrome 42 from [chrome-30-on.json](https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/chrome/chrome-30-on.json)
