### ISSUE TITLE
Missing Useragent

### ISSUE THREAD

**Issue by LeeUDO** [browscap/browscap#567]
This user agent is not being detected correctly. It comes from a Samsung Galaxy S5 using the Andoird Browser and Android Version 5.0

Mozilla/5.0 (Linux; Android 5.0; SAMSUNG SM-G900F Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36

It detects as Safari Generic.

Thanks

**Comment by mimmi20** [comment]
Its looks like this is a Samsung Browser. Samsung modified the default Android Browser and replaced the original one on some devices.
