### ISSUE TITLE
crawler UserAgent

### ISSUE THREAD

**Issue by sebbio** [browscap/browscap#590]
MegaIndex.ru crawler:
Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +https://www.megaindex.ru/?tab=linkAnalyze)

Begun.ru crawler:
Mozilla/5.0 (compatible; BegunAdvertising/3.0; +http://begun.ru/begun/technology/indexer/)

SEOGraph.net crawler:
Mozilla/5.0 (compatible; HyperCrawl/0.2; +http://www.seograph.net/bot.html)

iZSearch.com crawler:
iZSearch.com

Archive.org.ua crawler:
Mozilla/2.0 (compatible; ARCHIVE.ORG.UA crawler)

**Comment by mimmi20** [comment]
The first UA is already part of Issue #588.
