### ISSUE TITLE
UserAgent, added to 6000 version, are not diagnosable (Linux Android 4.4.2 / Lenovo A3300-HV / 4.0 Chrome)

### ISSUE THREAD

**Issue by cyrax-02** [browscap/browscap#598]
User Agent:
Mozilla/5.0 (Linux;U;Android 4.4.2;zh-cn;Lenovo A3300-HV Build/KOT49H) AppleWebkit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/537.306;

Version=6000
Released=Thu, 12 Mar 2015 10:42:22 +0000
Format=php
Type=FULL

This issue
https://github.com/browscap/browscap/issues/544
was marked as added into 6000 milestone and was closed. But in 6000 version this user agent are not diagnosable as before.

full_php_browscap.ini of 6000 version has expression:
[Mozilla/5.0 (*Linux*Android?4.4*Lenovo A3300-HV Build/*) AppleWebKit/* (KHTML, like Gecko)*Version/4.0*Chrome*]
but this expression for some reason do not fit user agent...

**Comment by cyrax-02** [comment]
Why expression:
[Mozilla/5.0 (LinuxAndroid?4.4Lenovo A3300-HV Build/) AppleWebKit/* (KHTML, like Gecko)Version/4.0Chrome*]
do not fit user agent:
Mozilla/5.0 (Linux;U;Android 4.4.2;zh-cn;Lenovo A3300-HV Build/KOT49H) AppleWebkit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/537.306;
?

**Comment by cyrax-02** [comment]
[Mozilla/5.0 (*Linux*Android?4.4*Lenovo A3300-HV Build/*) AppleWebKit/* (KHTML, like Gecko)*Version/4.0*Chrome*]

**Comment by cyrax-02** [comment]
Expression in full_php_browscap.ini place in 52120 line.
When i insert this expresiion hear, asterisk symbol are disappear.

**Comment by mimmi20** [comment]
@cyrax-02 Did you use that expression as regex for your search?

**Comment by cyrax-02** [comment]
>Did you use that expression as regex for your search?
No, i use get_browser function.
Now i checked once again - the user agent diagnosable successfull. Apparently, taken place an error in my self code, acting as a wrapper for get_browser function. Excuse for troubling.
