### ISSUE TITLE
CSV version 6000 missing crawler and other fields

### ISSUE THREAD

**Issue by robertlabrie** [browscap/browscap#599]
Was this intentional? Lots of fields missing win_16 and aolversion probably won't be missed, but crawler, frames, cookies, etc are also gone.

Thanks for adding pointing device and ismobile!

**Comment by asgrim** [comment]
@robertlabrie this is already resolved, so the fields will return in version 6001 - I'll try and get a release out this week!

**Comment by asgrim** [comment]
(see #583)
