### ISSUE TITLE
Error found in new version 6001_full

### ISSUE THREAD

**Issue by beppejo** [browscap/browscap#613]
line nr. 810720
section [Qt Generic for Desktop]
Parent="DefaultProperties"
the subsequent sections have reference to Parent="Qt Generic"
I belive, instead of Parent="Qt Generic for Desktop"
the section [Qt Generic]
is the next section at line nr. 810812
Hello and have a nice day. Bye, Giuseppe from Italy.

**Comment by mimmi20** [comment]
@beppejo Why should this be an error?

**Comment by beppejo** [comment]
because the general structure section use for "parent" the section before, not a section after, and also in this case the declared section [Qt Generic for Desktop] is useless because it's never used. The name section are similar, so it seem a typing error. Hello.
