### ISSUE TITLE
Lack of default in PHP LITE file

### ISSUE THREAD

**Issue by addw** [browscap/browscap#620]
The other 2 have a line near the end:
[*]
This is useful not just as a default but also checking (via script) that the download has completed fully.
Please can we have this, or some other end-of-file marker that can be checked.
Thanks

**Comment by asgrim** [comment]
Which version of the file are you using?

**Comment by addw** [comment]
I downloaded  http://browscap.org/stream?q=Lite_PHP_BrowsCapINI a few minutes ago, size is 8744244 and the last entry is
 [Mozilla/5.0 (*Android*Tablet*)*Gecko/*Firefox/ anonymized by Abelssoft*]

**Comment by asgrim** [comment]
6001

**Comment by addw** [comment]
Yes - 6001

**Comment by asgrim** [comment]
Re-opening to check for regressions - I am adding unit test to ensure the * section is present when generating the files.

**Comment by asgrim** [comment]
Need #617 to be merged so I can work on this as a base
