### ISSUE TITLE
Indistinguishable (duplicate?) patterns

### ISSUE THREAD

**Issue by vlsergey** [browscap/browscap#622]
[GJK_Browscap_Version]
    Version=6001
    Released=Tue, 07 Apr 2015 07:57:27 +0000
    Format=php
    Type=FULL

    [Mozilla/5.0 (*Linux*Android?4.2*)*AppleWebKit/*(*KHTML, like Gecko*)*Version/4.2*Safari*]
    Parent="Android Browser 4.2"
    Platform_Version="4.2"

    [*Mozilla/5.0 (*Linux*Android?4.2*) AppleWebKit/* (KHTML, like Gecko) Version/4.2*Safari*]
    Parent="Android Browser 4.2"
    Platform_Version="4.2"

**Comment by mimmi20** [comment]
The reason for these nearly duplicate rules is the fact that there exists user agents with something before the `Mozilla` token. This is also an result of the changed caching strategy in the version 3.x of the browscap-php lib to make that library faster.
