### ISSUE TITLE
UC Browser Mini - Not getting Detected

### ISSUE THREAD

**Issue by deadmantfa** [browscap/browscap#627]
UC Browser Mini - 10.1.1
Does not get detected as a mobile browser.

**Comment by mimmi20** [comment]
@deadmantfa Do you have an useragent?

**Comment by deadmantfa** [comment]
'HTTP_X_UCBROWSER_UA' => 'dv(GT-S6102);pr(UCBrowser/9.8.5.442);ov(Android 2.3.6);ss(240*301);bt(GJ);pm(1);bv(0);nm(0);im(0);sr(0);nt(2);',

This is what I got

Not the normal user agent
