### ISSUE TITLE
Another 1k user agents without device names

### ISSUE THREAD

**Issue by vlsergey** [browscap/browscap#635]
http://pastebin.com/FYB8VKtk

let me know if you would like to see all 740375 of them from my current database of user agents :smile: 
If would be nice to have some kind of short instruction to create patch for devices info

**Comment by mimmi20** [comment]
@vlsergey see the example from your list:
`Mozilla/5.0 (Linux; U; Android 4.2.2; ru-ru; HUAWEI P6 S-U06 Build/HuaweiP6S-U06) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30 ACHEETAHI/2100501044`

The device information for Android devices you find between the Token `Android x.x.x` (with optional language Token) and the Token `Build/`. In this UA the device key is `HUAWEI P6 S-U06`.

With the device key you can goole for more information.

For device information we have four properties.
- Device_Code_Name: Is the device key from the UA expect we find something else with Google.
- Device_Name: Is the marketing name for the device. Some device makers (e.g. Samsung) have more than one code name for one marketing name. This may be different for market regions, features or vendors.
- Device_Maker: The Comany who builds the device
- Device_Brand_Name: The Company which the device is branded with (e.g. Google for the Nexus series)

In your list are some UAs from Opera Mini. Opera Mini uses a second Header for the device information, but the most free php libraries don't support that header.

To your last question about your 740375 UAs. It would not be helpful to add all of them here. For our tests we use travis-ci.org. The tests have a time limit of 10 minutes before the test is killed. With out actual 2700-3000 tested Uas we already need around 8 minutes.

**Comment by asgrim** [comment]
@mimmi20 if you have time, could you possibly add this information to the wiki somewhere please?

**Comment by mimmi20** [comment]
@asgrim I have added this page: https://github.com/browscap/browscap/wiki/Resource:-Device-Database

**Comment by asgrim** [comment]
thanks

**Comment by mimmi20** [comment]
fixed
