### ISSUE TITLE
Split unit tests & user agent regression tests

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#646]
At the moment running `vendor/bin/phpunit` runs the entire test suite... which is fine, but it can take quite some time to run locally.

I propose (once #617 is merged) the following break up of the tests:

* Tool tests (i.e. the regular unit tests regarding the build tool itself)
* UA regression smoke tests (these would be a subset of the full tests that would only test major browsers to sanity check) - the point of this is to do a quick sanity check, so I'm wondering if we can speed up the generation of the files for this part somehow...? I know much of the time taken to run the test suite is made up from generating the files themselves, so I'm keen to reduce this as much as possible to make the testing process faster
* Full UA regression tests (for lite, standard and full versions together)

Travis CI should still run all tests, but it means that locally we can run just a subset of the tests (e.g. the Tool tests and the smoke tests)

**Comment by mimmi20** [comment]
@asgrim Could you check if your proposals are already implemented?
