### ISSUE TITLE
Increase minimum PHP version to PHP 5.5 or 5.6

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap#647]
I'm on PHP 5.6 now, PHP 5.5 is still pretty fast. I'm wondering if we can turn off PHP 5.4, possibly even 5.5?

**Comment by asgrim** [comment]
@mimmi20 could you report which PHP version you use please?

**Comment by mimmi20** [comment]
@asgrim I use PHP 5.6 on every system I have.

**Comment by asgrim** [comment]
Shall we turn off 5.5 and below on Travis then?

**Comment by mimmi20** [comment]
@asgrim If we dont need it, we can switch it off.
