### ISSUE TITLE
iPhone iOS 8.3 user-agent informations aren't included

### ISSUE THREAD

**Issue by atacank** [browscap/browscap#672]
I recognized this situation when i try to parse user agent data from an iPhone which has iOS 8.3.

[ExtendedUserAgent]
TLT_BROWSER=
TLT_BROWSER_VERSION=
TLT_BROWSER_PLATFORM=
TLT_TRAFFIC_TYPE=UNKNOWN
TLT_BROWSER_JAVASCRIPT=FALSE
TLT_BROWSER_COOKIES=FALSE

HTTP_USER_AGENT=Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F70 Safari/600.1.4

**Comment by asgrim** [comment]
What version of the files are you using? This UA correctly identifies on the UA lookup tool using 6003 on http://browscap.org/ua-lookup ...

**Comment by atacank** [comment]
I'm using 6003. I opened browscap.csv. I searched for 8_3. But I couldn't find this UA. And parsed datas come null.

**Comment by atacank** [comment]
Is there any reason for this issue?

**Comment by asgrim** [comment]
![ua](https://cloud.githubusercontent.com/assets/496145/7980330/6e50e10c-0a9e-11e5-92ee-88e6499224c1.png)

The UA is definitely present (see image above), although searching for 8_3 won't find it - as you can see it is matching `(iPhone*CPU iPhone OS * like Mac OS X*)` for the platform.

If you search for the UA in http://browscap.org/ua-lookup and the information is correct, then the data is not the issue, it would be the way you are using the data. See https://github.com/browscap/browscap/wiki/Using-Browscap for more information :)

Hope this helps!

**Comment by atacank** [comment]
Thank you @asgrim !

I will research it. If I find something, I write here.

**Comment by asgrim** [comment]
For further reference, https://github.com/browscap/browscap/blob/master/resources/user-agents/browsers/mobile-safari/mobile-safari-7-1-on.json is the definition that generates those UA strings, and you can see that mobile Safari 7.1+ is available on the specified platforms:

```json
        {
          "match": "Mozilla\/5.0*(iPhone#PLATFORM#)*AppleWebKit\/*(*KHTML, like Gecko*)*Version\/#MAJORVER#.#MINORVER#*Safari\/*",
          "device": "iPhone",
          "platforms": [
            "iOS_A_3_0", "iOS_A_3_1", "iOS_A_3_2", "iOS_A_4_0", "iOS_A_4_1", "iOS_A_4_2", "iOS_A_4_3",
            "iOS_A_5_0", "iOS_A_5_1", "iOS_A_6_0", "iOS_A_6_1", "iOS_A_7_0", "iOS_A_7_1", "iOS_A_8_0", "iOS_A_8_0_B",
            "iOS_A_8_1",
            "iOS_A",
            "iOS_B",
            "iOS_C_4_2", "iOS_C_4_3", "iOS_C_5_0", "iOS_C_5_1", "iOS_C_6_1", "iOS_C_6_0", "iOS_C_7_1", "iOS_C_7_0",
            "iOS_C_8_1", "iOS_C_8_0",
            "iOS_C"
          ]
        },
```

Basically, it is being matched by a more generic rule because we do not have anything specific for iOS 8.3 in this definition. A solution (for completeness) would be to create/use the `iOS_?_8_3` platform and apply it for mobile Safari, but nevertheless, the UA pattern I identified should definitely match the UA you have provided.

**Comment by mimmi20** [comment]
iOS 8.3 is not available in our database yet.
