### ISSUE TITLE
php_browsecap.ini 6004 matches Firefox 38.0 wrong

### ISSUE THREAD

**Issue by Newcomer01** [browscap/browscap#678]
I'm on Firefox 38 (Desktop Win7 32bit) and full_php_browsecap.ini matches my Browser as "Firefox Generic" with Firefox 37 was all right.

Firefox 37:  [parent] => Firefox 37.0
Taken from $_SERVER['HTTP_USER_AGENT'] = Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0

Firefox 38: [parent] => Firefox Generic
Taken from $_SERVER['HTTP_USER_AGENT'] = Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by mimmi20** [comment]
@Newcomer01 The missing version was added in release 6004. Could you check if the cache was updated without errors during the update?

**Comment by Newcomer01** [comment]
i have update the browsecap.ini on my webserver. i'm beginner which cache you mean?

**Comment by mimmi20** [comment]
@Newcomer01 If you are using the browscap-php library then in the directory where your browscap.ini is located should be a file `cache.php`. Could you remove that file and call your site after that. Then this cache file is recreated.
If you dont use that libary, please tell us the name of the implementation. May we can look into this.

**Comment by Newcomer01** [comment]
@mimmi20 here in this folder /etc/apache2 i don't have a cache.php
I have linux debian apache 2.0

**Comment by mimmi20** [comment]
@Newcomer01 Do you use the native PHP function `get_browser` or do you use any kind of libarry?

**Comment by Newcomer01** [comment]
@mimmi20 i use the native function get_browser()

**Comment by mimmi20** [comment]
@Newcomer01 Can you restart your Apache? If you are working with PHP as Apache Module, the php.ini and the browscap.ini are read only when the server is starting.

**Comment by Newcomer01** [comment]
@mimmi20 sorry i'm on a productive system and if i restart it can happen that tables from my mySQL can be broken and this i cannot fix.

**Comment by mimmi20** [comment]
@Newcomer01 Can you try to use the library broscap-php (https://github.com/browscap/browscap)?

**Comment by Newcomer01** [comment]
@mimmi20 sorry i need a working version of full_php_browscap.ini so that i can update it on my server... i'm new on gitHub and new on server thats not the best start to get things fixed i know ;-)

**Comment by asgrim** [comment]
@Newcomer01 I recommend you use the browscap-php component: http://github.com/browscap/browscap-php we officially support this component, so if you use it we are able to help you.

**Comment by Newcomer01** [comment]
@asgrim how can i install this on my pc? sorry i don't understand the steps

**Comment by asgrim** [comment]
@Newcomer01 the recommended usage is via Composer. https://getcomposer.org/

**Comment by Newcomer01** [comment]
@asgrim i don't have locale server enviroment here

**Comment by asgrim** [comment]
@Newcomer01 I'm afraid we can't help with that... maybe start with reading http://www.phptherightway.com/ :)
