### ISSUE TITLE
Not detecting Thunderbird properly

### ISSUE THREAD

**Issue by rpfennin** [browscap/browscap#689]
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Thunderbird/38.0.1 Lightning/4.0.0.1

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Thunderbird/38.0.1 Lightning/4.0.0.1

Should both detect Thunderbird but are coming back Firefox.

**Comment by realalex** [comment]
To follow up on this, it appears the .ini is out of date and does not contain new versions of Thunderbird (major version 38 that we're aware of).
