### ISSUE TITLE
Windows 10 Edge browser incorrectly recognized as Chrome

### ISSUE THREAD

**Issue by fberzau** [browscap/browscap#698]
This user agent string from the most current Windows 10 build recognizes the Edge browser as Chrome:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by magorinahory** [comment]
Hi, this issue should be addressed in 6006.
Please review this closed issue https://github.com/browscap/browscap/issues/688
and code https://github.com/browscap/browscap/commit/815b20f9a28fb56e2b9e8612c33d85131f39a5f5
