### ISSUE TITLE
Microsoft Edge $browser['parent'] as Chrome 

### ISSUE THREAD

**Issue by torroba3364** [browscap/browscap#707]
Hello.  

When running Browscap on Microsoft Edge 20.10240.16384.0 $browser['parent'] reports as Chrome 42.0

**Comment by mimmi20** [comment]
@torroba3364 Could you add the full Useragent?

**Comment by torroba3364** [comment]
Here it is:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

**Comment by mimmi20** [comment]
This was fixed with Issue #698.

**Comment by torroba3364** [comment]
Hi Thomas.

Below is print_r from my application.  I am also including the comments
from my full_php_browscap.ini.  The article you referred me to seems to
indicate that this should be fixed in 6006.  It does not appear to be
fixed.

[GJK_Browscap_Version]
Version=6006
Released=Sun, 19 Jul 2015 22:36:58 +0000
Format=php
Type=FULL


Array ( [browser_name_regex] => §^mozilla/5\.0 \(.*windows nt 10\.0.*win64.
x64.*\) applewebkit/.* \(khtml, like gecko\) chrome/42\..*safari/.*$§
[browser_name_pattern] => Mozilla/5.0 (*Windows NT 10.0*Win64? x64*)
AppleWebKit/* (KHTML, like Gecko) Chrome/42.*Safari/* [parent] => Chrome
42.0 [browser_bits] => 64 [platform] => Win10 [platform_version] => 10
[platform_description] => Windows 10 [platform_bits] => 64 [platform_maker]
=> Microsoft Corporation [win32] => [win64] => 1 [device_name] => Windows
Desktop [device_code_name] => Windows Desktop [comment] => Chrome 42.0
[browser] => Chrome [browser_type] => Browser [browser_maker] => Google Inc
[version] => 42.0 [majorver] => 42 [frames] => 1 [iframes] => 1 [tables] =>
1 [cookies] => 1 [javascript] => 1 [javaapplets] => 1 [cssversion] => 3
[device_maker] => Various [device_type] => Desktop [device_pointing_method]
=> mouse [renderingengine_name] => Blink [renderingengine_description] => a
WebKit Fork by Google [renderingengine_maker] => Google Inc [browser_modus]
=> unknown [minorver] => 0 [alpha] => [beta] => [win16] =>
[backgroundsounds] => [vbscript] => [activexcontrols] => [ismobiledevice]
=> [istablet] => [issyndicationreader] => [crawler] => [aolversion] => 0
[device_brand_name] => unknown [renderingengine_version] => unknown )

**Comment by mimmi20** [comment]
@torroba3364 Which library do you use in comination with the ini file?

**Comment by torroba3364** [comment]
My apologies.  I copied the new browscap.ini file incorrectly.  I have it
working now.  Thanks much for your help!
