### ISSUE TITLE
Crawler field missing from XML in 6006?

### ISSUE THREAD

**Issue by RoBorg** [browscap/browscap#708]
The browscap.xml file (http://browscap.org/stream?q=BrowsCapXML) does't seem to have the Crawler field - is this intentional?

**Comment by asgrim** [comment]
The file is already ~80mb... if we add in every field, it would be huge due to XML tag overhead. Therefore XML only has "common" fields.

The CSV file has every field, perhaps use this?

**Comment by RoBorg** [comment]
Thanks for the response :) That's what I figured - just wanted to make sure it was intentional because it used to have the Crawler field in (it's been a long time since I last updated!)
