### ISSUE TITLE
bad useragents

### ISSUE THREAD

**Issue by rpfennin** [browscap/browscap#710]
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/4.0; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.5.30729)

Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/4.0; .NET CLR 1.0.3705; .NET CLR 1.1.4322; Media Center PC 4.0; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; .NET4.0C; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET4.0E; yie8)

These are both (i believe incorrectly) coming back as "Fake IE".

Also,  Thunderbird 38.1 is missing:

Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Thunderbird/38.1.0 Lightning/4.0.1

ryan

**Comment by mimmi20** [comment]
The both IE useragents are marked as fake because of the mismatch between the `MSIE` and `Trident` tokens. `Trident/4.0` belongs to IE8, IE9 includes Trident 5. see here: https://msdn.microsoft.com/en-us/library/ms537503(v=vs.85).aspx.

Thunderbird 38.1 was added with Issue #705.
