### ISSUE TITLE
missing user agent

### ISSUE THREAD

**Issue by gjohncock** [browscap/browscap#715]
i use browscap-php - version info from the browscap class is:
    const VERSION = '2.0';
    const CACHE_FILE_VERSION = '2.0b';
i update the cache at 3am every morning via a cron job - current cache is from 3am (+10) this morning

IP Address: 49.197.29.82

missing agent info...
User-Agent: Mozilla/5.0 (Linux; Android 4.4.4; SAMSUNG SM-J100Y Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.0
Chrome/34.0.1847.76 Mobile Safari/537.36

**Comment by mimmi20** [comment]
This Ua is covered within Issue #712.
