### ISSUE TITLE
Fake Firefox real Fake? 

### ISSUE THREAD

**Issue by mwunderwald** [browscap/browscap#716]
Hallo, we are detecting A Millions of UserAgents from various web users based on browscap.ini. 

In the past two-three month we recognise a increase of browsers identified as Fake Browser without OS and Version. For Example:

Fake Browsers:
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:39.0) Gecko/20100101 Firefox/39.0

Non-Fake Detected as Firefox 39 on Win7
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

Question is, what are the rules based on when determining a browser as Fake?
Is it just, that browscap.ini does not yet know about the combination of OS and Browser like Win NT 10 and FF 39 or some other sources that state that there can't be any real Browser like that?

Thank you in Advance!
Martin

**Comment by mimmi20** [comment]
We have to fix the rules for Firefox. Do you have more Uas where you think these are no fakes?

**Comment by mwunderwald** [comment]
Oh, thank you for fast reply!

I tried to order it after amount of people we detected with them and that seems suspicious: 
With * as wildcard

Mozilla/5.0 (Windows NT 10.0; WOW64; rv:*.0) Gecko/20100101 Firefox/*.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:*.0) Gecko/20100101 Firefox/*.0
Mozilla/5.0 (Windows NT 10.0; rv:*.0) Gecko/20100101 Firefox/*.0
* = 36,37,38,39,40

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/* Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/* Safari/537.36
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/* Safari/537.36
* = 40.* to 43.*

Some IE 11 like those:
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Thats it basically for this issue.

Another Issue is with the new Microsoft Edge Browser which is detected as Chrome because its part of the UA String for compatibility issues:

https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.<OS build number>

Thank you!

Martin

**Comment by mimmi20** [comment]
@mwunderwald Could you add one Ua for each missing variant?

**Comment by mwunderwald** [comment]
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:39.0) Gecko/20100101 Firefox/39.0
Mozilla/5.0 (Windows NT 10.0; rv:38.0) Gecko/20100101 Firefox/38.0
