### ISSUE TITLE
Missing Samsung Browser useragent

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap#726]
>Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G920F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.2 Chrome/38.0.2125.102 Mobile Safari/537.36

6006's lookup:

![screen shot 2015-08-13 at 9 33 40 am](https://cloud.githubusercontent.com/assets/136907/9254029/70c38246-419e-11e5-977a-9a7b18c3cbad.png)

**Comment by mimmi20** [comment]
This Ua is part of Issue #705.
