### ISSUE TITLE
Can be a missing?

### ISSUE THREAD

**Issue by beppejo** [browscap/browscap#727]
The general/default section for "BitTorrent Clients" have property "Browser" (line 8686 in full version 6006) equal to empty string, it is the only general property section that haven't a default Browser name. Hallo and thank you, have a nice day. Giuseppe from Italy.

**Comment by mimmi20** [comment]
@beppejo Do you have an Useragent for testing?

**Comment by beppejo** [comment]
Hello, yes we have write it.
We have an application and for using the full version of browscap, 
without load all in memory, we go through a DB.
For load the DB we make a parsing of browscap, if this can be useful to 
you too, you can tell us what kind of test do you like on 
full_php_browscap.ini and we can insert it in the parser. However, every 
time there is a new version of browscap we write to you if the parser 
find sometingh strange.
Bye, Giuseppe.

Il 17/08/2015 20:33, Thomas Müller ha scritto:

**Comment by mimmi20** [comment]
@beppejo No I did not mean that. I mean that:
Did you have an useragent who triggered this error on your system? If you have that kind of Ua I would like to add this Ua to our tests.

**Comment by mimmi20** [comment]
I you find more strange things, please add more issues here to get them solved.
