### ISSUE TITLE
full_php_browscap.ini (version 6007) has syntax errors

### ISSUE THREAD

**Issue by cyrax-02** [browscap/browscap#761]
When i run this code:
get_browser();

i have 20-40 warning messages:
PHP warning: get_browser() [<a href='function.get-browser'>function.get-browser</a>]: Compilation failed: missing terminating ] for character class at offset 21

it seems that new (full_php_browscap.ini) has syntax errors.
In preview version (6006) these warnings absent.

**Comment by asgrim** [comment]
I will release 6008 tomorrow hopefully to fix this.
