### ISSUE TITLE
Safari 9.0

### ISSUE THREAD

**Issue by shrubsolej** [browscap/browscap#771]
Hi,

I'm testing with Safari 9.0, and the version is being mis-reported as 0.0.

The user-agent string is as follows:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.39 (KHTML, like Gecko) Version/9.0 Safari/601.1.39

Thanks,

Jamie.

**Comment by shrubsolej** [comment]
Hi,

Do you have an ETA for 6009?

Thanks,

Jamie.

**Comment by asgrim** [comment]
We've only just released 6008 a couple of days ago, and there's usually around a release per month (although no fixed schedule), but if you need fixes earlier I can always do another release :)

**Comment by shrubsolej** [comment]
Hi,

Ideally, we'd like a fix for this asap as it affects the latest version of Safari on the Mac.

Is this possible?

Many thanks,

Jamie.
