### ISSUE TITLE
Missing user agent for Windows Phone 8.1 and others

### ISSUE THREAD

**Issue by remluben** [browscap/browscap#775]
A couple of days ago I found out that Windows Phones are not detected using the Browscap PHP library.

The User-Agent I first ran into this issue is:

> Mozilla/5.0 (Mobile: Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Nokia; Lumia 730 Dual Sim

I am using Browscap PHP and the lite_php_browscap.ini version 6008, but I could not find any Windows Phone specific User-Agents in full_php_browscap.ini neither.

Am I missing something?

**Comment by mimmi20** [comment]
@remluben You should find them if you search for `Lumia` or `IEMobile`.
