### ISSUE TITLE
browscap is not getting enabled 

### ISSUE THREAD

**Issue by drashtikns** [browscap/browscap#777]
I have installed browscap on our litespeed server and successfully build browscap.ini file as per instructions given heer. The path of browscap.ini file is "/root/browscap/build/browscap.ini". I have enabled [browscap] settings in php.ini file and changed it's path to "/root/browscap/build/browscap.ini". I have restarted apache server and litespeed server but browscap still not getting enabled. In phpinfo(), it is still showing "no value". Is there some steps that I am missing in installation?

**Comment by mimmi20** [comment]
@drashtikns Is the changed php.ini used for your application? Is the user/group who is used for PHP able to read that file? Do you get any errors?

**Comment by drashtikns** [comment]
@mimmi20 I am getting this error: "PHP Warning:  Cannot open '/root/browscap/build/browscap.ini' for reading in Unknown on line 0"
browscap.ini file is at "/root/browscap/build/" directory.
php.ini file is at "/usr/local/lib/" directory.
and my site application is at "/home/tweaktow/public_html/" directory.

"root" directory has 750 permissions. and inside that all files and directories have 755 permissions.  It means inside "root" directory, "browscap" directory and all it's files have 755 permissions. 

Is it file permission issue?

**Comment by asgrim** [comment]
It depends what user the PHP process is running as, this typically might be
"httpd" or "www-data". Find out, and make sure that user can read the file.
A quick test (NOTE - INSECURE SO ENSURE YOU SORT PERMISSIONS PROPERLY) is
to set it to 777 to eliminate file permissions issues.
