### ISSUE TITLE
User-agent Safri 9 on OSX as version 0.0

### ISSUE THREAD

**Issue by Eroan** [browscap/browscap#795]
Safari 9 on OSX is recognized as version 0.0 instead of 9...
Thanks for the fix !

**Comment by mimmi20** [comment]
@Eroan Do you have an Useragent?

**Comment by Eroan** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
