### ISSUE TITLE
UA: Not detected as crawler

### ISSUE THREAD

**Issue by mapanet** [browscap/browscap#797]
User agent not reported as crawler:

mozilla/5.0 (iphone; cpu iphone os 8_3 like mac os x) applewebkit/600.1.4 (khtml, like gecko) version/8.0 mobile/12f70 safari/600.1.4 (compatible; googlebot/2.1; +http://www.google.com/bot.html)

**Comment by asgrim** [comment]
@mapanet both these UAs are detected fine in 6008 (see http://browscap.org/ua-lookup) - please ensure you have the latest verions

**Comment by mapanet** [comment]
Hello James, thanks for taking a look at it.

I am using the browscap.ini on Windows Server, is there something in the
syntax that makes a difference to php? any hint that may be the cause ?
The majority go well, just a few specific known crawlers are not tagged
(edited the file and added Crawler=true specifically on those and then they
work properly), so guess is some detail.


Regards
Carlos Blanco
admin@mapanet.eu

**Comment by mapanet** [comment]
Hello James,

Mozilla/5.0 (iphone; cpu iphone os 8_3 like mac os x) applewebkit/600.1.4
(khtml, like gecko) version/8.0 mobile/12f70 safari/600.1.4 (compatible;
googlebot/2.1; +http://www.google.com/bot.html)

Checked it at http://browscap.org/ua-lookup and shows: Crawler = false
 where clearly in the string says googlebot.

Regards
Juan Carlos




Regards
Carlos Blanco
admin@mapanet.eu
