### ISSUE TITLE
UA Not detected as crawler

### ISSUE THREAD

**Issue by mapanet** [browscap/browscap#798]
User agent:

Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on windows server;) Daumoa 4.0

Is listed in browscap but is not detected as crawler.

If I am correct, in browscap.ini, [Daumoa] especifies default.
Next, [Mozilla ... Daumoa?4.0*] has Parent indicating to use [Daumoa] defauls plus the ones defined.

Am I wrong assuming this?

[Daumoa]
Parent=DefaultProperties
Comment=Daumoa
Browser=Daumoa
Browser_Type=Bot/Crawler
Browser_Maker=Daum Communications Corp
Crawler=true

[Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on Windows server;*) Daumoa?4.0*]
Parent=Daumoa
Version=4.0
MajorVer=4

[Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on Windows server;*) Daumoa?3.0*]
Parent=Daumoa
Version=3.0
MajorVer=3

[Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on Windows server;*]
Parent=Daumoa

**Comment by asgrim** [comment]
Looks like it is detecting fine in 6008 version:
http://browscap.org/ua-lookup
using
`Mozilla/5.0 (compatible; MSIE or Firefox mutant; not on windows server;) Daumoa 4.0`

**Comment by mimmi20** [comment]
This Ua was part of Issue #712.
