### ISSUE TITLE
Missing User Agent

### ISSUE THREAD

**Issue by mylearningcenter** [browscap/browscap#805]
browsecap seems to be missing the following user agent:

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; BOIE9;ENGB; rv:11.0) like Gecko

Windows 7, IE 11

**Comment by asgrim** [comment]
@mylearningcenter please try the latest version (6009) - I looked that UA up on http://browscap.org/ua-lookup and it worked just fine...

**Comment by mylearningcenter** [comment]
Thanks.  Maybe I'm doing something wrong then because I was using v6008 but I just downloaded v6009 as you requested and I still don't see it.  I was using the browscap.csv file and I assume there aren't any differences between the file types as far as content.  As a simple test, I tried grepping BOIE9 in that CSV and found no matches so I was wondering how the ua-lookup used the files.  Maybe I'm using the CSV incorrectly.

Thank you.

**Comment by asgrim** [comment]
The CSV cannot be used directly, it is a CSV that contains "matching" patterns, that have tokens like `*`, i.e.:

```
Mozilla/5.0 (*Windows NT 6.1*WOW64*Trident/7.0*rv:11.0*)*
```

This pattern is associated to the metadata that can be seen on http://browscap.org/ua-lookup

You cannot search directly for a UA in any of the files we provide, you need to use a library to parse these (and most likely cache the matching patterns for performance) and look up the UA this way.

See: https://github.com/browscap/browscap/wiki/Using-Browscap for help

**Comment by mylearningcenter** [comment]
Thanks.  That explains it.  As a suggestion, it might be a good idea to post the wiki link on the main site page because I looked for some documentation and didn't see it right off.
Thanks for the help.

**Comment by asgrim** [comment]
@mylearningcenter thanks, will do :)

**Comment by asgrim** [comment]
@mylearningcenter FYI, this has been implemented ;)
