### ISSUE TITLE
Seems that Apache2 failing to restart with the latest version: 6009

### ISSUE THREAD

**Issue by itsazzad** [browscap/browscap#809]
Yesterday also it was working with the previous latest release: `6008`.
The new one is not seems to be working. `Apache2` is failing to `restart`. But after disabling the `browscap` in the `php.ini`, `Apache2` can `restart`.
Can you please provide me with a quick url for the 6008 version? 
`http://browscap.org/stream?q=PHP_BrowsCapINI`
I am not understanding how to download the older versions although its suggesting so: 
`http://browscap.org/stream?q=BrowsCapINI (replace BrowsCapINI with the appropriate version)`
I have tried with `http://browscap.org/stream?q=PHP_BrowsCapINI_6008` and `http://browscap.org/stream?q=PHP_6008` but unfortunately not working. Seems to be that I am missing something.

**Comment by asgrim** [comment]
I'm afraid we do not offer old versions to download. You can build old versions yourself, see:

https://github.com/browscap/browscap/wiki/Build-Command

**Comment by asgrim** [comment]
FTR, we highly recommend using https://github.com/browscap/browscap-php library over the native browscap functionality - we do not support the latter.

**Comment by mimmi20** [comment]
@itsazzad Could you provide an error message from your logs?

**Comment by itsazzad** [comment]
`vagrant@my_project:/$ sudo service apache2 restart
Job for apache2.service failed. See "systemctl status apache2.service" and "journalctl -xe" for details.
vagrant@my_project:/$ systemctl status apache2.service
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
   Active: failed (Result: exit-code) since Wed 2015-10-28 13:12:14 UTC; 1min 45s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 14973 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 14998 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)
vagrant@my_project:/$ journalctl -xe
No journal files were found.
~
~
~
...skipping...
~
~
~`
I am using `ubuntu/vivid64`: https://atlas.hashicorp.com/ubuntu/boxes/vivid64
`PHP Version 5.6.4-4ubuntu6.3`
`Apache/2.4.10 (Ubuntu)`

**Comment by asgrim** [comment]
@itsazzad that is not the error log, try `/var/log/apache2/error_log` or similar path

**Comment by itsazzad** [comment]
@asgrim no error in the log. Only Apache fails to restart in activating `browscap` in the `php.ini` file.

**Comment by itsazzad** [comment]
Only the lite version working with me:
lite_php_browscap.ini : working
php_browscap.ini : not working
full_php_browscap.ini : not working

https://github.com/browscap/browscap/issues/812
