### ISSUE TITLE
360safe browser support

### ISSUE THREAD

**Issue by jhiswin** [browscap/browscap#816]
360safe browser is without a doubt the most used browser here in China, and could benefit from support.  It has two modes: IE (just embeds trident) and Webkit (equivalent to Chrome 31 with some features missing, most notable native Promise).

I'll make further posts with more information and try forking a patch (currently looking at CONTRIBUTING), but I'd appreciate some quick tips for where to look and what to do.

I don't currently use browscap directly (I'm using it through FT polyfill as a service), so I'm unfamiliar with browscap.  Related issue here: https://github.com/Financial-Times/polyfill-service/issues/500

**Comment by jhiswin** [comment]
https://github.com/cloudcome/alien/blob/master/src/core/navigator/shell.js
For reference, here is an attempt by a Chinese dev to target 360safe.

**Comment by mimmi20** [comment]
@jhiswin Do you have useragents for the two modes?

**Comment by jhiswin** [comment]
So they have two different browsers.  One of them is literally translated to 360 secure browser (I assume this is 360 safe) and the other is translated to 360 speed browser.  In trident mode, it's just the IE user agent.  Below are user agent strings for the webkit mode.

360 "secure" browser 8.0.1.250 beta "360se.*.exe", has a green "e" icon
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36"

360 "secure" browser 7.1.1.810 "360se.*.exe", has a green "e" icon
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 QIHU 360SE"

360 "speed" browser 8.5.0.118 has a flower like icon "360cse.*.exe"
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36 QIHU 360EE"

**Comment by mimmi20** [comment]
@jhiswin If the browser just send the IE useragent, then this browser can not be detected. The same goes for the first Ua you posted, This is just The useragent from Chrome. The zwo other Uas can be used for detection, but the browser version is not part of the Ua.

**Comment by jhiswin** [comment]
@mimmi20 Just a note: that is the beta version that doesn't have the extra string in the UA.  Hopefully the stable release will have it.

It's unfortunate, but it looks like the only way to detect version will be to use the Chrome version.

**Comment by mimmi20** [comment]
@jhiswin I asume you dont have a map from Chrome version to this browsers version?

**Comment by jhiswin** [comment]
@mimmi20 Sorry, ya, I'm actually not fluent in reading Chinese myself.  I do know that all Chinese computers I have encountered use primarily the latest 360safe browser with Chrome 31 engine, some using the "flower" icon one as well.  They are almost always up to date due to the somewhat intrusive automatic update using 360 security software, so it's reasonably safe to start from there.  If you have a test suite I can try to run it on them.

**Comment by mimmi20** [comment]
@jhiswin We dont have a test suite. We just analyze useragents.
