### ISSUE TITLE
UA no tagged with crawler=true

### ISSUE THREAD

**Issue by mapanet** [browscap/browscap#825]
I am using the latest browscap.ini version is 6009 (27th Oct 2015) on classic ASP

The following UA seem to be a yahoo crawler according to yahoo specs:
https://help.yahoo.com/kb/search/SLN22600.html?impressions=true

Browscap does not report crawler=true

Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit (KHTML, like Gecko) Mobile (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)

**Comment by mimmi20** [comment]
was part of Issue #817
