### ISSUE TITLE
Submission of New User Agents

### ISSUE THREAD

**Issue by dczaretsky** [browscap/browscap#827]
Would be great if there was an easy form on browscap.org to submit and fill in the info for new user agents. Maybe others can then help more to contribute and test. Seems the current method of posting to Github is a bit more cumbersome.

Just a thought.

**Comment by asgrim** [comment]
Ultimately, the entire project is handled on GitHub now, so the workflow would need to create new user agents via a bot account of sorts.

**Comment by asgrim** [comment]
Closed in favour of browscap/browscap-site#27 - thanks @dczaretsky :+1: :)
