### ISSUE TITLE
IE8 on XP is showing version number as 0.0

### ISSUE THREAD

**Issue by JFK1980** [browscap/browscap#829]
As above.

IE7 on XP and IE8 on Win7 are both behaving as expected, please read this thread for more details:

https://wordpress.org/support/topic/ie8-xp-on-browserstack-showing-as-version-00

**Comment by asgrim** [comment]
@JFK1980 thanks for the report, could you give a couple of example user agents please? That way we can determine if they're fake, or just missing patterns :) thanks!

**Comment by JFK1980** [comment]
![screen shot 2015-11-10 at 15 29 00](https://cloud.githubusercontent.com/assets/4904696/11066438/22da08e4-87c0-11e5-87b9-184d59948cc3.png)

Apologies, as this is stepping outside of my comfort zone and into areas that I'm unfamiliar with. I have attached a screen shot from IE8, first showing the user agent details and then the details I'm getting back from the WP plugin.

As you can see, the WP plugin is showing version as 0.0, along with unknown platform and device. These are the same results that we found on a fresh install on a native XP machine running IE8.

If there's more details that you need from me, then please let me know and I'll happily supply.

**Comment by asgrim** [comment]
```
Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; Trident/4.0; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.648; .NET CLR 3.5.21022)
```

**Comment by asgrim** [comment]
@JFK1980 thanks for the UA. It seems in the latest version of Browscap, this is correct. Try updating your browscap.ini to the latest version (6009)...

**Comment by JFK1980** [comment]
Excellent. That seems to have fixed the issue.

It seems that Browscap needs updating in the plugin, I shall inform the author and point him towards this discussion.

Thanks for all your help, most appreciated.

**Comment by asgrim** [comment]
You're very welcome! Thanks :)
