### ISSUE TITLE
New: Mozilla/5.0 (compatible; DeuSu/5.0.2; +https://deusu.de/robot.html)

### ISSUE THREAD

**Issue by mapanet** [browscap/browscap#833]
Mozilla/5.0 (compatible; DeuSu/5.0.2; +https://deusu.de/robot.html)

Now reporting browser = unknown
funn-asp-browscap.ini 6009 27 Oct 2015
Using browscap.ini using Classic ASP, via Server.CreateObject("MSWC.BrowserType")

**Comment by mimmi20** [comment]
was added with Issue #806.
