### ISSUE TITLE
IE Mobile 7 and 8 detected as IE 6

### ISSUE THREAD

**Issue by tt-jeremye** [browscap/browscap#841]
These two user agents were correctly detected with browser name IEMobile in Browscap 6009, but are now showing up as (desktop) IE 6 in 6010.
- `Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 7.11) Sprint:MotoQ9c`
- `Mozilla/4.0 (compatible; MSIE 6.0; Windows CE; IEMobile 8.12; MSIEMobile 6.0) T-Mobile_LEO`

**Comment by mimmi20** [comment]
@tt-jeremye Which version of the browscap file do you use? `Standard` or `Full`?

**Comment by tt-jeremye** [comment]
Sorry I missed your question, @mimmi20, but for posterity, it was `Full`.
