### ISSUE TITLE
AdBeat UA Not Matched

### ISSUE THREAD

**Issue by parisholley** [browscap/browscap#857]
Mozilla/5.0 (X11; Linux x86_64) adbeat.com/policy AppleWebKit/537.21 (KHTML, like Gecko) Firefox/34.0 Safari/537.21

**Comment by parisholley** [comment]
Trying to create a pull for this, but lost as to why local tests and the remote build are failing off these simple diffs:

https://travis-ci.org/parisholley/browscap/jobs/94564352

Even checking out master doesn't pass locally, with mostly the same problem. It is as if the cache'd ini files aren't being read right?

**Comment by mimmi20** [comment]
@parisholley Actually there is an error inside the browscap/browscap-php libary. This error makes that the cache is not created.

**Comment by mimmi20** [comment]
@parisholley Please rename the key inside your test from `issue-827-A` to `issue-857` to make it match to the testcase.

**Comment by mimmi20** [comment]
I created PR #858 for this Issue.
