### ISSUE TITLE
Overlapping patterns

### ISSUE THREAD

**Issue by wggdeveloper** [browscap/browscap#885]
Overlapping patterns are fine if they are sorted in decreasing specificity, but there are a significant amount (3.2%) of patterns that can mask each other out due to their ordering.

Using a8657c0 I generated an [HTML file](https://github.com/browscap/browscap/files/85144/overlaps.zip) to show these maskings. Patterns are sorted into blocks where each pattern matches the _exact same browser_. The first pattern of each block masks the others, so theoretically these other patterns can safely be removed. Every pattern is prefixed with the corresponding line number in the INI.

Overall, these maskings are harmless, but render a lot of patterns redundant.

**Comment by mimmi20** [comment]
@wggdeveloper The rules inside the browscap.ini files are not used in the order they are listed there, if you are using one of the libraries `browscap-php` or `crosscoin/browscap`. The rules are ordered by length and used from the longest to the shortest. So sometimes it is nessesary to create nearly duplicate rules to prevent to get the wrong result .

I will look into the duplicate device definition first.

**Comment by mimmi20** [comment]
@wggdeveloper Could you share the script you used for this check?

**Comment by wggdeveloper** [comment]
[Here](https://gist.github.com/wggdeveloper/1994ebe9400744ff353d) is the script I used. You will need at least Python 3.4 to run it:
```
$ python overlaps.py < browscap.ini > overlaps.html
```

**Comment by mimmi20** [comment]
@wggdeveloper Thanks
