### ISSUE TITLE
Incorrect device detection for Nokia 630

### ISSUE THREAD

**Issue by joereynolds** [browscap/browscap#907]
Hi,

A user has reported that when she visits our site on her Nokia 630, she's given the desktop styling of the site.

Browscap details:
```
Version=6012
Type=Lite
Format=PHP
```

We're using PHP built-in to parse the file.

And here's the user agent

```Mozilla/5.0 (Windows Phone 8.1; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 630) like Gecko```

To replicate:

- Get or emulate(?) a Nokia 630
- Go to sykescottages.co.uk

You'll be greeted with a squished desktop styling which looks like this:
![desktop](https://cloud.githubusercontent.com/assets/9536682/13640594/2a6b19ee-e60d-11e5-80c1-32f009f13142.png)

But really, we want you to be seeing this: 
![mobile](https://cloud.githubusercontent.com/assets/9536682/13640602/3440849a-e60d-11e5-8d10-d4d408f3e137.png)

**Comment by ThaDafinser** [comment]
@joereynolds with the full version of `6012` it tells me that it's detected as mobile
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+Phone+8.1%3B+ARM%3B+Trident%2F7.0%3B+Touch%3B+rv%3A11.0%3B+IEMobile%2F11.0%3B+NOKIA%3B+Lumia+630%29+like+Gecko

**Comment by asgrim** [comment]
@joereynolds indeed - with our own lookup tool, we also see it's detected as mobile:

**Comment by asgrim** [comment]
I'd suggest using the full version in the mean time, but I think IEMobile is a reasonable contender to be added to the `lite` files.

**Comment by joereynolds** [comment]
So all we need to do is update to the full version then? neat! thanks guys
