### ISSUE TITLE
New version 6013, missing DefaultProperties

### ISSUE THREAD

**Issue by beppejo** [browscap/browscap#915]
New version 6013. In the first session [Instagram/2.0* CFNetwork/459*] for a  Browser, the "Parent" (Instagram App 2.0) is not (DefaultProperties).
Bye and thank you.

**Comment by asgrim** [comment]
@beppejo Really sorry, but I'm unclear on what the problem is here?

If you believe a UA is incorrectly identified could you provide an example UA and what you think is wrong please?

**Comment by beppejo** [comment]
Yes you are right, the problem is different and isn't an error, is a comment.
Normally the file has the comment with a lot of ";" before a section that describes the "DefaultProperties" and the name of the section is equal to the comment..
for example:

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Instagram App 2.0

[Instagram App 2.0]
Parent="DefaultProperties"
Comment="Instagram App 2.0"
...
...

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Instagram App 1.1

[Instagram App 1.1]
Parent="DefaultProperties"
Comment="Instagram App 1.1"
...
...

But in one point you use the comment without this rules, but is only a comment, and my parser scan for all rules.
This is the example:

[Instagram/2.1* CFNetwork/758*]
Parent="Instagram App 2.1"
Platform_Version="9.0"

[Instagram/2.1* CFNetwork/*]
Parent="Instagram App 2.1"

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Instagram App 2.0

[Instagram/2.0* CFNetwork/459*]
Parent="Instagram App 2.0"
Platform_Version="3.1"

[Instagram/2.0* CFNetwork/467.12*]
Parent="Instagram App 2.0"
Platform_Version="3.2"

Excuse me, I'll put and exception into my parser for the comments, that isn't so important like the code. I test the comment too for standardize all the file and rules, but I understand that the comments aren't so important for the final result.

Best regards, Giuseppe.

**Comment by mimmi20** [comment]
This is an error because the section `Instagram App 2.0` must be defined twice in the resources.

**Comment by asgrim** [comment]
Yes, it shouldn't be defined twice - but also the comments shouldn't be read by machines, they are there for humans ;)
