### ISSUE TITLE
6013 CSV file

### ISSUE THREAD

**Issue by shrubsolej** [browscap/browscap#916]
Hi,

Our import broke while loading 6013.

This is apparently because there are extra columns in the file (isAnonymized, isModified and isFake).

Is this an error or will these new fields always be present? Are we likely to see more new fields in future?

When the CSV structure changes we have to recompile and re-issue our SSIS package to the clients.

If the file structure is likely to change again, we might need to change our approach.

Thanks,

Jamie.

**Comment by asgrim** [comment]
Nope, not an error, just new additional data added. We do add additional fields from time to time, but it's not often. Apologies for the inconvenience!
