### ISSUE TITLE
Missing user agent Firefox 43, 44

### ISSUE THREAD

**Issue by martinchiquet** [browscap/browscap#917]
Hi,

Firefox 43.0 , 43.0.1, 44.0.2 is missing from the data:
Mozilla/5.0 (Windows NT 6.1; WOW64%; rv:4%) Gecko/% Firefox/4% Firefox/44%

Thanks,

Martin

**Comment by mimmi20** [comment]
@martinchiquet Do you have any real useragent without any placeholders?

**Comment by Tomefa** [comment]
Here is the real useragent : Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by martinchiquet** [comment]
@Tomefa thx!
