### ISSUE TITLE
XML invalid characters

### ISSUE THREAD

**Issue by shrubsolej** [browscap/browscap#918]
Hi,

We've found ampersands in the XML data which are obviously invalid characters in XML. This is causing the XML parser to throw an exception.

Do you plan to replace invalid characters in the XML, or is this something we will need to deal with?

Thanks,

Jamie.

**Comment by mimmi20** [comment]
Could you tell us the location (name of the rule) of that invalid Charakter?

**Comment by shrubsolej** [comment]
There are ampersands throughout the data.

I'm not sure there's a rule as such, but it's described in section 2.4 here: https://www.w3.org/TR/REC-xml/

Values such as "SEO & Analytics" are causing the XML parser to error.
