### ISSUE TITLE
Missing user agent Opera36

### ISSUE THREAD

**Issue by coanny** [browscap/browscap#919]
Hi,

Opera 36(http://www.opera.com/docs/changelogs/unified/3600/) is missing from the data:
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 OPR/36.0.2130.32

Thanks,

Seongho

**Comment by Bob0t** [comment]
Hey,

In fast it is detected, but as Chrome 49

Here is my record : 

`{
    "id":"1",
    "hash":"d3422c8a60ec3f03a0c5d9cf536d45d5ef770268",
    "rawdata":"Mozilla\/5.0 (Windows NT 6.1; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/49.0.2623.75 Safari\/537.36 OPR\/36.0.2130.32",
    "browser":"Chrome",
    "browser_bits":"32",
    "browser_type":"Browser",
    "version":"49.0",
    "majorver":"49",
    "comment":"Chrome 49.0",
    "cssversion":"3",
    "device_code_name":"Windows Desktop",
    "device_maker":"Various",
    "device_name":"Windows Desktop",
    "device_pointing_method":"mouse",
    "device_type":"Desktop",
    "cookies":"1",
    "javascript":"1",
    "parent":"Chrome 49.0",
    "platform":"Win7",
    "platform_bits":"64",
    "platform_description":"Windows 7",
    "platform_version":"6.1"
}`

**Comment by turbohz** [comment]
This is the UA for the latest Opera 36 on Linux:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 OPR/36.0.2130.46
```
