### ISSUE TITLE
AdobeAIR on iOS not detected

### ISSUE THREAD

**Issue by wggdeveloper** [browscap/browscap#928]
These user-agents belong to the Adobe AIR runtime on iOS, and none of them are detected in v6013.

```
Mozilla/5.0 (iOS; U; en) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0
Mozilla/5.0 (iOS; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0
Mozilla/5.0 (iOS; U; en-GB) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/13.0
```

There is no iOS variant in `apps/adobe-air.json`, and I didn't find an appropriate pattern for `#PLATFORM#` in `platforms.json` either.

**Comment by mimmi20** [comment]
@wggdeveloper Do you have any information if the iPhone or the iPad was used?

**Comment by wggdeveloper** [comment]
@mimmi20 Sorry, no information about that.
