### ISSUE TITLE
Question: Which pattern match is the right one?

### ISSUE THREAD

**Issue by ziege** [browscap/browscap#929]
Hi,

I am working on a new parser and in my tests I got a case in which multiple patterns match a user agent. Both matches contain the same data, so one gets the correct data, but how is it defined which of them is the rigth one (also for other cases)?
- Position in the ini file (first/last match)?
- Length of the pattern (with/without place holders)?
- ...?

**User Agent:**
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Match 1 (PHP-Ini-Version 6013):**
[Mozilla/5.0 (*Windows NT 10.0*WOW64*) Gecko* Firefox/45.0*]
Parent="Firefox 45.0"
Browser_Bits="32"
Platform="Win10"
Platform_Version="10.0"
Platform_Description="Windows 10"
Platform_Bits="64"
Platform_Maker="Microsoft Corporation"
Win64="true"
Device_Name="Windows Desktop"
Device_Code_Name="Windows Desktop"

**Match 2 (PHP-Ini-Version 6013):**
[Mozilla/5.0 (*Windows NT 10.0*WOW64*rv:45.0*) Gecko* Firefox*]
Parent="Firefox 45.0"
Browser_Bits="32"
Platform="Win10"
Platform_Version="10.0"
Platform_Description="Windows 10"
Platform_Bits="64"
Platform_Maker="Microsoft Corporation"
Win64="true"
Device_Name="Windows Desktop"
Device_Code_Name="Windows Desktop"

Thanks,
Christoph

**Comment by asgrim** [comment]
The longest (more specific) match is the correct way of sorting:)

**Comment by ziege** [comment]
Thanks! I guess that the length is "length without *-placeholders", right? But what if the length is the same for multiple matching patterns?

PS: *more specific* in this example is a bit difficult, because both contain information which the other pattern doesn't contain - "rv:45.0*" and "/45.0", but if it's defined this way, that's okay.

**Comment by mimmi20** [comment]
I my opinion the first match should be the correct one. The second match was added (as I remember) for the cases when an anonymizer removes the version from the `Firefox` Token, but both matched should return the same result.
To use the rules as they are defined in the ini file, it would require a lot of resorting the rules. Actually it is nessesary to sort the rules by length.

**Comment by mimmi20** [comment]
If the length is the same for multiple pattern, they are actually sorted as they are in the ini file.

**Comment by ziege** [comment]
Thanks, this helps me.
