### ISSUE TITLE
missing samsung internet browser user agent (used in the Samsung Gear VR headset)

### ISSUE THREAD

**Issue by abuisine** [browscap/browscap#933]
**version and type**
6013, Standard

**tool**
crossjoin/browscap

**missing user agents**
* `Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G920F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile VR Safari/537.36`
* `Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G920F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`
* `Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-G920F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.2 Chrome/38.0.2125.102 Mobile Safari/537.36`

**other information**
* samsung internet browser is used both for samsung mobiles and inside [Samsung Gear VR](http://www.samsung.com/global/galaxy/wearables/gear-vr/) headset.
* please note the presence of the `VR` tag in the first missing user agent (might be interesting the track VR capable devices in the future).

**Comment by mimmi20** [comment]
the Samsung Gear VR is a Addon for Mobile Phones, so we may detect the used Phone.
