### ISSUE TITLE
Safari 9.1 on OS X 10.11.4

### ISSUE THREAD

**Issue by gmishkin** [browscap/browscap#954]
Example user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

Safari is detected as browser but version not detected.

Browscap 6013, tried directly from the main web site.

**Comment by mimmi20** [comment]
This should be fixed with Issue #921.

**Comment by Crash58** [comment]
is browscap 6014 available for download?

**Comment by mimmi20** [comment]
no, not yet
