### ISSUE TITLE
Opera detected as Chrome

### ISSUE THREAD

**Issue by shrubsolej** [browscap/browscap#955]
In version 6013, Opera 36 is detected as Chrome 49.

The user agent string is:

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36 OPR/36.0.2130.46

**Comment by mimmi20** [comment]
Should be fixed with Issue #919. This not released yet.
