### ISSUE TITLE
Edge 14 is detected as Chrome 48

### ISSUE THREAD

**Issue by calvinwyoung** [browscap/browscap#984]
With the current version of `browscap.ini` (6014), Edge 14 on Windows 10 is detected as Chrome 48. The full user agent string is:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 Edge/14.14316

**Comment by ThaDafinser** [comment]
Can confirm it, with all types (lite, standard, full)
http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F48.0.2564.82+Safari%2F537.36+Edge%2F14.14316
