### ISSUE TITLE
Trident/8 identifies non-existent IE12

### ISSUE THREAD

**Issue by ToolsTeamLee** [browscap/browscap#995]
Internet Explorer 12 doesn't exist, yet I have some user agent strings that contain Trident/8, so the browscap file is identifying them as IE12.

Example:
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/8.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

All the UA strings identified are on PCs running Windows 10.

**Comment by asgrim** [comment]
It's okay, these people come from the future :)

**Comment by mimmi20** [comment]
I found this answer (https://social.msdn.microsoft.com/Forums/en-US/c671bcbd-c46b-4f62-becd-19c738b6b222/use-of-trident8-string-in-useragent?forum=iewebdevelopment):

> From further research I had undertaken, it certainly appears to me that Microsoft may have originally planned on using the "Trident/8.0" token for IE11 on Windows 10, but then changed their mind and went back to using "Trident/7.0". It appears that the "Trident/8.0"  version token will only appear on the initial release of IE11 on Windows 10.

**Comment by ToolsTeamLee** [comment]
Thanks, I had seen that article too, however it doesn't explain why the browscap file has manual entries that show IE12.

What would make more sense would be to identify Trident/8 and use IE11, then if Microsoft do use Trident/8 for a future version of IE, the newest version of browscap can be updated at that time.
